import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('cache', 'runNoteCache', 'Coalesces real memory-cache reads, isolates owner keys, invalidates, expires and recovers a failed lookup.', 'Node.js 24. Real bounded memory store; tests advance time. No Redis or SQL claim.');

export const cacheArticle: DocArticle = {
	id: 'cache', area: 'services', group: 'Application', label: 'Cache', title: 'Cache an expensive lookup', summary: 'Cache a note summary, keep account keys separate and invalidate it after a write.', packageName: '@db3.ai/app/cache', sourcePath: 'packages/app/src/cache/README.md', examplePaths: ['packages/app/src/cache/examples/runNoteCache.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Start with a memory cache', paragraphs: ['Complete Installation and copy this lab. It uses the real bounded memory driver; its counted lookup stands in for expensive application work without requiring a database.', 'Use `app().cache` in an application. The standalone lab constructs and closes `Cache` so its ownership is visible.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'run', title: 'Run and inspect the lookup count', paragraphs: ['Expect `firstLoads: 1` for two concurrent reads, `refreshed: { count: 2 }` after invalidation, an unchanged second-owner result and `recovered: "ready"` after a failed factory. `cleared` is true.', 'The lab closes its cache in `finally`. It only clears the store it created, not a shared application or Redis store.'], codeSampleId: 'run-lab' },
		{ id: 'lookup', title: 'Read through the cache', paragraphs: ['`getOrSet(key, factory, { ttl })` computes only on a miss. Concurrent misses share one in-flight computation within the same cache instance/process. This is not a cross-process lock or exactly-once business operation.', 'Build keys from the authorized owner, operation, inputs and a format version. A key is not an authorization check; authorize before looking up private data. Use plain serializable values, not a live ActiveRecord instance or open connection.'], codeSampleId: 'cache-source' },
		{ id: 'invalidation', title: 'Invalidate after changing the source', paragraphs: ['After a successful database write/commit, call `forget()` for affected cache keys. Deleting a summary does not change the source data; the next lookup recomputes it. TTL is a backstop, not a consistency guarantee.', '`forget()` reports acceptance of deletion, not whether a row or value existed. `clear()` removes every key owned by the selected store. Avoid using it for routine single-record changes.'] },
		{ id: 'ttl', title: 'TTL, refresh and values', paragraphs: ['TTL is in milliseconds. Configure a positive store default or supply a per-write TTL. Omitting a default leaves no default expiry; the bounded memory store can still evict entries.', '`refreshThreshold` returns the current value while refreshing near expiry. Only use this when serving stale data is acceptable. The factory can derive TTL and threshold from its result; those signatures are in the reference.', '`undefined` means a miss and cannot be stored. `null`, `false`, zero and empty strings are valid cached values. Generic types do not validate deserialized values.'], links: [{ label: 'TTL and refresh options', articleId: 'cache-api', sectionId: 'operations' }] },
		{ id: 'configuration', title: 'Choose one named store', paragraphs: ['Pass `config: { cache: { default, stores } }` to App. Cache selects one named store; it is not a tiered or automatically failing-over collection. Memory defaults to a maximum of 1,000 entries and cloned values.', 'Separate API/worker processes do not share memory entries. For shared data configure a Redis store with `driver`, `url` and a nonempty `namespace`; isolate app and environment, for example `notes:staging:cache`.', 'Redis options include connection timeout, clear batch size and strict error flags. Namespaced clear scans/unlinks that namespace, never flushes the entire database. Keep credentials server-side. This lab does not exercise a live Redis connection.'], links: [{ label: 'Store configuration', articleId: 'cache-api', sectionId: 'options' }, { label: 'App configuration', articleId: 'app-config' }] },
		{ id: 'failures', title: 'Handle misses and failures deliberately', paragraphs: ['A rejected factory is not cached and later callers can retry. An undefined result rejects. Blank keys reject; surrounding whitespace is trimmed.', 'Cache is an optimization, never the only copy of required state. Decide which operations may fall back to the source when storage is unavailable, and monitor that path. Read/refresh errors follow the selected driver behavior; do not assume every outage throws or silently recovers.', '`App.close()` closes its cache; a manually created cache needs `close()`. Do not close the shared app cache at the end of every request.'] },
		serviceLabTesting('cache', 'runNoteCache'),
		{ id: 'run-tests', title: 'Test cache behavior without sleeping', paragraphs: ['The copied tests use real stores. They cover concurrent reads, owner keys, invalidation, recovery, valid falsy values, store isolation and millisecond expiry. Only the clock is controlled for the expiry assertion.', 'For your feature, count source reads and prove a write invalidates the right owner/key. Add live Redis conformance before choosing Redis for a deployment.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: memory read/write, get-or-set, same-instance coalescing, invalidation, clear, TTL, failed factory recovery, key/value validation, independent stores and close. Configuration, LRU bounds, cloning and background refresh are explained/reference-covered; background refresh and live Redis are not proved by this lab.', 'There is no cache-tag API, distributed mutex, multi-store failover or durable transaction. Use database/Queue primitives for durable work.'], links: [{ label: 'Full Cache API', articleId: 'cache-api' }, { label: 'Durable background work', articleId: 'queue-overview' }] },
	], codeSamples: [...serviceLabSamples('cache', 'runNoteCache'), { id: 'cache-source', title: 'examples/runNoteCache.ts', language: 'typescript', code: sources.runNoteCache ?? '' }], relatedIds: ['cache-api', 'app-config', 'events'],
};

export const cacheApiArticle = createApiReference({ id: 'cache-api', label: 'Cache API', packageName: '@db3.ai/app/cache', sourcePath: 'packages/app/src/cache/README.md', guideId: 'cache', references: [['cache', 'Cache service', 'dist/cache/Cache.d.ts'], ['options', 'Named store options', 'dist/cache/contracts/CacheOptions.d.ts'], ['operations', 'TTL and factory options', 'dist/cache/contracts/CacheOperations.d.ts'], ['repository', 'Repository contract', 'dist/cache/contracts/CacheRepository.d.ts'], ['driver', 'Driver lifecycle', 'dist/cache/contracts/CacheDriver.d.ts']] });
