import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('config', 'runConfig', 'Boots typed application settings, rejects malformed configuration, preserves dot-path semantics and keeps credentials out of the displayed result.', 'Node.js 24; no database, listening port, provider or credentials.');

export const configArticle: DocArticle = {
	id: 'config', area: 'services', group: 'Foundation', label: 'Config', title: 'Configuration',
	summary: 'Read settings once at boot. Parse environment values, validate the bits your application needs and pass them into the services that use them.',
	packageName: '@db3.ai/app/config', sourcePath: 'packages/app/src/config/README.md',
	examplePaths: ['packages/app/src/config/examples/loadNotesConfig.ts', 'packages/app/src/config/examples/runConfig.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Configure a notes application', paragraphs: ['Complete Installation, then run this small configuration lab from your independent app directory. It needs no SQL, HTTP server or API key. The example reads a page size and local port, controls debug mode and requires a webhook key only when that optional integration is enabled.', 'There is no automatic config-folder discovery. Import your own config files explicitly. The runner loads `.env` through `dotenv/config` before reading values; the Config service itself does not load environment files. Keep `.env` out of Git.'], codeSampleId: 'copy-lab', links: [{ label: 'Install the preview and development tools', articleId: 'installation' }] },
		{ id: 'run', title: 'Run it', paragraphs: ['With no application overrides, expect `name: "My notes"`, `port: 3000`, `pageSize: 20`, `debug: false` and `notesUrl: "http://localhost:3000/notes"`. It builds the URL but does not start a listener.', 'Run the override command to change the page size and port. Setting `APP_PORT=abc` produces an error naming `APP_PORT` before App construction. Correct it and run again. Existing shell variables take precedence over values loaded by dotenv.'], codeSampleId: 'config-commands' },
		{ id: 'load', title: 'Parse and validate at the boundary', paragraphs: ['`createEnv(source)` makes an isolated reader. Tests can pass an ordinary object without changing global environment state. `defineConfig()` preserves inferred types; it does not validate values, merge files or make them immutable.', '`env.integer()` rejects fractions, but a valid integer can still be an invalid port or page size. Keep those application rules beside the configuration. Do not call `env.required()` for an optional feature until that feature is enabled.'], codeSampleId: 'config-source' },
		{ id: 'app', title: 'Pass settings into App', paragraphs: ['`new App({ config: { notes } })` exposes the repository through `application.config`. The example passes URL settings separately through `url`; a value stored under `config.url` would not configure that service.', 'Read typed application settings directly from the returned object when practical. `config.get<T>()` is useful for service boundaries, but its type argument is a TypeScript assertion, not runtime validation or checked dot-path autocomplete.'], codeSampleId: 'config-runner', links: [{ label: 'App configuration and process ownership', articleId: 'app-config' }] },
		{ id: 'read', title: 'Defaults and missing paths', paragraphs: ['`get(path, fallback)` uses the fallback only when the property is absent. Existing `null`, `undefined`, `false`, zero and empty strings are preserved. `has()` tests property presence, not truthiness.', 'Dot paths traverse own object properties, not array indexes. Read the array as a value. Empty paths or paths containing an empty segment throw. `all()` returns the original configuration object, not a clone; treat it as read-only and never return it from an API.'] },
		{ id: 'environment', title: 'Environment parser details', paragraphs: ['`env()` and `env.string()` return raw strings: an empty string is still a value. `env.required()` rejects missing or exactly empty strings, but does not trim whitespace. The example adds the whitespace check for its key.', 'Boolean, number, integer, array and JSON parsers trim input and use their fallback for missing or empty values. Boolean accepts `1`, `true`, `yes`, `on`, `0`, `false`, `no` and `off`, case-insensitively. Invalid booleans, non-finite numbers, fractions passed to `integer()` and malformed JSON throw.', '`env.array()` splits comma-separated values, trims entries and removes empty entries. `env.json<T>()` parses JSON but does not validate its shape against `T`; use Validation or an explicit shape check before trusting it. Readers see later changes to their source object, while your constructed settings are a boot-time snapshot.'], links: [{ label: 'All parser overloads', articleId: 'config-api', sectionId: 'environment' }, { label: 'Validate application input', articleId: 'validation' }] },
		{ id: 'safety', title: 'Secrets, changes and cleanup', paragraphs: ['Only expose a deliberate public subset of settings. Do not log `config.all()`, serialize it into a browser page or prefix a server key with `VITE_`. The lab output intentionally omits its webhook key.', 'Restart the process after changing boot-time configuration. Mutating an object or environment variable will not recreate already initialized services. The Config repository owns no handles; the lab still closes its App in `finally`.'] },
		serviceLabTesting('config', 'runConfig'),
		{ id: 'run-tests', title: 'Run and extend the tests', paragraphs: ['The three copied tests cover defaults, overrides, redaction, malformed input, range limits, optional credentials, raw/parsed values and property presence. Change the maximum page size, update its boundary assertion and rerun.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Taught and tested: boot-time settings, integer/boolean/array parsing, required values, application ranges, Config reuse, fallback/presence, JSON/number parsing and secret-safe output. The service suite covers the remaining parser failures.', 'Reference-only details are the generic overloads and every individual malformed input. There is no config-file discovery, automatic hot reload, schema validation or secret manager. Those are not hidden framework features.'], links: [{ label: 'Config API reference', articleId: 'config-api' }, { label: 'Build the first HTTP app', articleId: 'create-app' }] },
	],
	codeSamples: [...serviceLabSamples('config', 'runConfig'),
		{ id: 'config-commands', title: 'Defaults, an override and a deliberate failure', language: 'bash', code: 'npx tsx examples/runConfig.ts\nAPP_PORT=3100 NOTES_PAGE_SIZE=50 APP_DEBUG=yes npx tsx examples/runConfig.ts\n# This should fail; correct the value and repeat.\nAPP_PORT=abc npx tsx examples/runConfig.ts' },
		{ id: 'config-source', title: 'examples/loadNotesConfig.ts', language: 'typescript', code: sources.loadNotesConfig ?? '' },
		{ id: 'config-runner', title: 'examples/runConfig.ts', language: 'typescript', code: sources.runConfig ?? '' },
	], relatedIds: ['config-api', 'app-config', 'app', 'validation'],
};

export const appConfigArticle: DocArticle = {
	id: 'app-config', area: 'start', group: 'Get started', label: 'App & config', title: 'Configure the application runtime',
	summary: 'Keep application settings explicit. Boot one App, give each service its options and leave HTTP and worker startup to the host.',
	packageName: '@db3.ai/app/server', sourcePath: 'packages/app/src/server/README.md', includeSourceDocument: false,
	sections: [
		{ id: 'start', title: 'Run a small configuration example', paragraphs: ['The Config walkthrough boots a real App without a database or listener. Copy its two files, run the command, change a port or page size, then trigger a configuration error. Start there before wiring more services.'], links: [{ label: 'Copy, run and test configuration', articleId: 'config', sectionId: 'setup' }] },
		{ id: 'options', title: 'Repository values are not service options', paragraphs: ['Use `config` for application values and the configuration sections consumed by Cache, Auth, Media and Security. Pass `storage`, `url`, `queue`, `log`, `serializer`, `auth`, `db` and `dbOptions` through their supported App options.', 'For example, `config.notes.pageSize` is yours to read; `url.baseUrl` constructs the URL service. Do not assume every nested config key configures a same-named service.'], codeSampleId: 'boot' },
		{ id: 'schema', title: 'Give the application its own database', paragraphs: ['The generated starter owns its model registry and committed migrations. Keep `dbOptions.syncColumns: false` for migration-owned schemas. Run migrations explicitly, not each time an HTTP request or worker starts.', 'Normal model code uses the active App database. Do not pass optional database connections through feature functions. A test or transaction can supply its deliberate connection through App construction or `ActiveRecord.withDb()`.'], links: [{ label: 'Starter database setup', articleId: 'starter-app', sectionId: 'database' }, { label: 'ActiveRecord', articleId: 'active-record' }] },
		{ id: 'lifecycle', title: 'Boot once and close what you own', paragraphs: ['Constructing App makes it process-global. Do not create it per HTTP request; use request context for users and request IDs. Service getters reuse the same service instance.', 'App does not listen for HTTP or install signal handlers. Your host starts and closes HTTP, drains workers, closes custom transports and then closes App. The first HTTP app demonstrates that boundary.'], links: [{ label: 'HTTP factory and shutdown', articleId: 'create-app' }, { label: 'App lifecycle details', articleId: 'app' }, { label: 'Worker shutdown', articleId: 'queue-overview', sectionId: 'shutdown' }] },
		{ id: 'testing', title: 'Test the configuration before booting the feature', paragraphs: ['Pass a plain environment object to your config loader. Assert defaults, invalid values and missing required settings. Then instantiate the real App with those options and close it in `finally`. The Config page supplies the exact tests and command.'], links: [{ label: 'Run the configuration tests', articleId: 'config', sectionId: 'testing' }] },
		{ id: 'coverage', title: 'Coverage and reference', paragraphs: ['This page connects the tested Config example to the existing App and starter workflows. It is not a second implementation or a full dependency-injection system. Custom service lifecycle and production process supervision remain application responsibilities.'], links: [{ label: 'Configuration API', articleId: 'config-api' }, { label: 'App service guide', articleId: 'app' }] },
	], codeSamples: [{ id: 'boot', title: 'The same tested bootstrap from the Config lab', language: 'typescript', code: sources.runConfig ?? '' }], relatedIds: ['config', 'app', 'starter-app', 'create-app'],
};

export const configApiArticle = createApiReference({ id: 'config-api', label: 'Config API', packageName: '@db3.ai/app/config', sourcePath: 'packages/app/src/config/README.md', guideId: 'config', references: [['repository', 'Config and defineConfig', 'dist/config/Config.d.ts'], ['environment', 'Environment readers and parser overloads', 'dist/config/env.d.ts']] });
