import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { noteEvidence, noteExamplePaths, noteTestPath } from './activeRecord';
import { serviceLabSamples, serviceLabTesting } from './serviceLab';

const samples = [...serviceLabSamples('db', 'runWorkspaceNotes', 'workspaceNotes'), { id: 'model', title: 'examples/KnowledgeNote.ts', language: 'typescript', code: serviceExampleSources.knowledgeNote }, { id: 'operations', title: 'examples/workspaceNotes.ts', language: 'typescript', code: serviceExampleSources.workspaceNotes }, { id: 'transaction', title: 'examples/createNotesTogether.ts', language: 'typescript', code: serviceExampleSources.createNotesTogether }];

export const modelDataArticle: DocArticle = {
	id: 'guide-model-data', area: 'guides', group: 'Application guides', label: 'Model your data', title: 'Take a note from input to stored data', summary: 'Choose fields, protect ownership, persist the model and return its public shape.', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/README.md', examplePaths: noteExamplePaths, testPath: noteTestPath, verifiedExample: noteEvidence, includeSourceDocument: false,
	sections: [
		{ id: 'setup', title: 'Start with the working notes lab', paragraphs: ['Complete the Workspace notes installation and test-only SQL setup first. If starting from the full app shell, use the starter’s model/migration workflow instead; do not put disposable database setup into server startup.', 'Copying all database examples also copies the expected output used by the tests. Run from the same app directory with Node 24 and the Installation development dependencies.'], codeSampleId: 'copy-lab', links: [{ label: 'Workspace notes setup', articleId: 'guide-workspace-notes', sectionId: 'configure' }, { label: 'Full Notes starter', articleId: 'starter-app' }] },
		{ id: 'run', title: 'Run before changing it', paragraphs: ['The lab creates a workspace-owned note, excludes another workspace’s note, rejects invalid input, rolls back a two-note failure and deletes its test data. The owned database is removed in `finally`.', 'Keep that baseline passing while adding a field. A successful TypeScript build alone does not prove storage conversion or ownership.'], codeSampleId: 'run-lab' },
		{ id: 'model', title: 'Declare the product data', paragraphs: ['The model uses a ULID, trusted workspace ownership, required title, body and creation timestamp. Database names belong to fields: createdAt maps to created_at, while normal application code uses createdAt.', 'Use a specific field when it already owns your conversion. Do not add a JSON.parse(), date cleanup or lowercase helper to every route. For genuinely reusable behavior, implement a small custom field.'], codeSampleId: 'model', links: [{ label: 'Reusable fields and nested JSON', articleId: 'fields' }] },
		{ id: 'write', title: 'Separate user input from trusted ownership', paragraphs: ['The function fills only allowed title/body values, then assigns the already-authorized workspace. `new Model()` and `Model.create()` are in-memory operations; `save()` persists.', 'Scope read, edit and delete by both the trusted workspace and record identity. Request validation and fillable lists do not establish membership or permission. The full starter’s authentication/HTTP tests cover that separate boundary.'], codeSampleId: 'operations', links: [{ label: 'Authenticated API workflow', articleId: 'guide-api' }] },
		{ id: 'schema', title: 'Ship the schema with the feature', paragraphs: ['Register the model in your application’s model list, generate a migration, review it, apply it and run schema check. Commit the model, migration, snapshot and behavior test together.', 'The lab uses `Database.install()` only because its database is disposable. For an existing app, use an additive migration and consider old data before making a new field required.'], links: [{ label: 'Run a safe schema change', articleId: 'migrations' }] },
		serviceLabTesting('db', 'workspaceNotes'),
		{ id: 'run-tests', title: 'Extend the behavior test', paragraphs: ['The copied tests prove in-memory versus persisted creation, validation, ownership, edits/deletes, date output and rollback using real SQL. Add the new field to input, reread it and assert its display output.', 'Try a value that should fail and prove no row was inserted or changed. Keep an explicit second workspace in the test so a successful happy path does not hide an authorization leak.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'What this recipe proves', paragraphs: ['This is the end-to-end model workflow using the existing tested notes lab. It does not claim a complete multi-tenant membership system or a migration deployment.', 'Fields, Queries, Migrations and the authenticated starter expand the named boundaries; use their focused tests as you add those capabilities.'], links: [{ label: 'Fields', articleId: 'fields' }, { label: 'Queries', articleId: 'queries' }, { label: 'Migrations', articleId: 'migrations' }] },
	], codeSamples: samples, relatedIds: ['active-record', 'fields', 'queries', 'migrations', 'guide-api'],
};

export const transactionsArticle: DocArticle = {
	id: 'cookbook-transactions', area: 'cookbook', group: 'Common problems', label: 'Scoped transactions', title: 'Save related records together or not at all', summary: 'Use the active database transaction without adding database parameters to every model and feature function.', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/README.md', examplePaths: noteExamplePaths, testPath: noteTestPath, verifiedExample: noteEvidence, includeSourceDocument: false,
	sections: [
		{ id: 'setup', title: 'Prepare the notes lab', paragraphs: ['Use the Workspace notes test-only MariaDB account and copied examples. The lab creates its own database and never wraps a production schema change in a transaction.'], codeSampleId: 'copy-lab', links: [{ label: 'SQL setup and permissions', articleId: 'guide-workspace-notes', sectionId: 'configure' }] },
		{ id: 'run', title: 'Force the second write to fail', paragraphs: ['Run the lab and expect `rollbackPreservedCount: true`. The first proposed note has a valid title; the second is invalid. When validation rejects, the earlier insert rolls back.', 'The original pre-transaction note remains. Repair the invalid title in your copied example and assert both new notes persist after commit.'], codeSampleId: 'run-lab' },
		{ id: 'scope', title: 'Enter the connection scope once', paragraphs: ['Start with `app().db.knex.transaction()`, then run the work inside `ActiveRecord.withDb(transaction, callback)`. Ordinary feature functions keep using model APIs and resolve the scoped connection.', 'Construct and query the records inside the scope. An existing record already bound to another connection is not magically rebound. Await every operation before returning from the transaction callback.'], codeSampleId: 'transaction' },
		{ id: 'errors', title: 'Let failure reach the transaction', paragraphs: ['An error must reject the callback for rollback. Do not catch validation/database errors inside it and return success unless committing the earlier work is intentional.', 'Treat SQL constraints as the final authority for concurrent writes. Application checks can race. Decide whether a retry is safe and keep it bounded; a transaction does not make arbitrary external calls duplicate-safe.'] },
		{ id: 'external', title: 'Database atomicity stops at the database', paragraphs: ['Sending email, charging a card, dispatching through a separate queue connection or calling an AI provider is not rolled back with these model writes. Avoid slow external work while holding locks.', 'For a required post-commit handoff, use a deliberately designed outbox/reconciliation workflow. This framework recipe does not claim a transactional Queue outbox or exactly-once delivery.'], links: [{ label: 'Queue delivery guarantees', articleId: 'queue-overview' }, { label: 'Mail retry boundary', articleId: 'mail' }] },
		serviceLabTesting('db', 'workspaceNotes'),
		{ id: 'run-tests', title: 'Test rollback and success', paragraphs: ['The copied SQL tests assert that a later validation failure leaves the count unchanged. Add a successful two-note case when adapting the recipe, and check both notes after the transaction returns.', 'Never use a framework-owned mock database to prove transaction semantics. Cleanup removes only the generated lab database.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: scoped ActiveRecord connection, normal feature reuse and rollback after an earlier real insert. Isolation levels, deadlock retries, cross-database work and external outbox delivery are not demonstrated.', 'Use the exact API for connection escape hatches only when working on framework/test/transaction infrastructure; ordinary app/model APIs should not grow optional database parameters.'], links: [{ label: 'ActiveRecord connection API', articleId: 'active-record-api' }] },
	], codeSamples: samples, relatedIds: ['active-record', 'guide-model-data', 'queue-overview'],
};
