import type { DocArticle, DocContentSection } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('db', 'runFieldNotes', 'Persists custom, list and JSON fields; verifies scoped/projection reads, rejected saves and encrypted storage/output boundaries.', 'Node.js 24 and a disposable MariaDB database. Test account needs CREATE/DROP DATABASE. Synthetic ephemeral encryption key only.');
const examples = ['NoteCodeField.ts', 'FieldNote.ts', 'runFieldNotes.ts'].map(file => `packages/app/src/db/examples/${file}`);
const setup: DocContentSection = { id: 'setup', title: 'Prepare the disposable SQL lab', paragraphs: ['Complete Installation and its local MariaDB test-account setup. Use Node.js 24 and a test account allowed to create/drop `db3_app_test_*` databases. Copy the shipped database examples from your independent app directory.', 'Set your test-only `DB_CONNECTION=mariadb`, `DB_HOST`, `DB_PORT`, `DB_USER` and `DB_PASSWORD` in `.env`. `DATABASE_URL` overrides these connection values: unset it if it points elsewhere. This lab creates and removes its own database, not your app database.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation and local MariaDB', articleId: 'installation' }] };
const run: DocContentSection = { id: 'run', title: 'Run the field workflow', paragraphs: ['Expect code `BRIEF-1`, tags `["SEO", "Agency"]`, decoded nested client metadata and `scopedCount: 1`. Every protection/result flag is true, including `countUnchanged` after an invalid save.', 'No plaintext or ciphertext is printed. The lab owns its temporary database and key and cleans up in `finally`. A forcibly killed process can leave a generated test database; inspect its exact name before removing it.'], codeSampleId: 'run-lab' };
const samples = [...serviceLabSamples('db', 'runFieldNotes'), { id: 'model-source', title: 'examples/FieldNote.ts', language: 'typescript', code: sources.fieldNote ?? '' }, { id: 'custom-source', title: 'examples/NoteCodeField.ts', language: 'typescript', code: sources.noteCodeField ?? '' }, { id: 'runner-source', title: 'examples/runFieldNotes.ts', language: 'typescript', code: sources.runFieldNotes ?? '' }];
const testSection: DocContentSection = { id: 'run-tests', title: 'Run and extend the SQL test', paragraphs: ['Run with the same disposable test-only SQL credentials. This test uses real fields, model queries, database storage and encryption. It asserts a failed save leaves the count unchanged.', 'Add a different input and expected result to the example/test together. Do not replace the database with a mock or silently skip it when verifying a release.'], codeSampleId: 'test-lab' };

export const fieldsArticle: DocArticle = {
	id: 'fields', area: 'services', group: 'Data', label: 'Fields', title: 'Keep conversion in the field', summary: 'Define a reusable value once, from input and validation through storage and public output.', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/README.md', examplePaths: examples, testPath: evidence.testPath, verifiedExample: evidence, includeSourceDocument: false,
	sections: [setup, run,
		{ id: 'model', title: 'The field is the reusable unit', paragraphs: ['A record groups fields. Each field owns how its value enters the app, validates, becomes a database value and comes back as application or display data. Keep this close to the database rather than inventing a second query language.', 'The example combines a custom code, normalized tags, nested JSON and an encrypted integration field. `owner` maps to `owner_id` in storage; application code still uses the logical name.'], codeSampleId: 'model-source', links: [{ label: 'Why this is field-first ActiveRecord', articleId: 'active-record' }] },
		{ id: 'reuse', title: 'Add one reusable conversion', paragraphs: ['`NoteCodeField` extends `StringField` and changes only `parse()`. It inherits trimming, required/max-length validation, varchar schema and display behavior. Reuse it by placing a new instance in another model’s field map.', 'A field definition is shared metadata; per-record values belong to field state. Do not put a current user, connection or mutable request data on a reusable definition. Query conversion is a separate hook: if input normalization must also apply to query values, implement and test `getQueryValue()`.'], codeSampleId: 'custom-source' },
		{ id: 'lifecycle', title: 'Input, app, database and display values', paragraphs: ['The main types are `FieldType<TValue, TDbValue, TDisplayValue, TInput, TState>`. `setValue()`/`parse()` handle input, `setFromDb()`/`fromDbValue()` handle storage reads, and `getDataForDb()`/`toDbValue()` handle writes.', '`toJSON()` is display/transport output, not an unrestricted dump of in-memory state. Use `toAppData()` only on the trusted server when you need application values. Hidden fields and excluded selects are different controls.', 'For ordinary model operations, assign logical values and let fields run the lifecycle. Use the low-level hooks when authoring a field, not to repeat conversion in every route.'], links: [{ label: 'FieldType and concrete fields', articleId: 'fields-api' }] },
		{ id: 'request', title: 'Keep request policy on the model', paragraphs: ['`requestFillable` allows code, tags and metadata. The payload cannot set owner or integration; trusted application code assigns them separately. `assign()` is for trusted values, while `setFromRequest()` applies request policy.', '`save()` validates field state before writing. This lab attempts a blank code and four tags with `truncate: false`; it receives `RecordValidationError` and inserts nothing. Return selected field/code/message details rather than reflecting submitted secrets.'], codeSampleId: 'runner-source' },
		{ id: 'json', title: 'Nested data and specialized JSON', paragraphs: ['`json<T>()` accepts decoded JSON or a JSON string and preserves nested shapes. It is permissive: the generic does not validate client.name at runtime, and it does not turn nested objects into model relations.', '`stringList()` trims and deduplicates case-insensitively. `maxItems` truncates by default; use `truncate: false` when excess entries should produce validation errors.', 'Use a specialized field when several models need the same conversion/rules. Nested document support is not a promise of a complete document mapper or automatic deep request validation.'] },
		{ id: 'secrets', title: 'Password hashing is not encryption', paragraphs: ['`password()` hashes on save, hides its public value and verifies rather than decrypting. `encryptedJson()` stores reversible authenticated ciphertext and always hides display output.', 'Our integration opts out of default selection. Server code must explicitly select it with `withField()` and authorize the owner before using it. Randomized encryption cannot be searched with equality queries.'], links: [{ label: 'Encrypted model recipe', articleId: 'cookbook-secrets' }, { label: 'Password authentication', articleId: 'auth' }] },
		serviceLabTesting('db', 'runFieldNotes'), testSection,
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Taught/tested: custom string input conversion, validation, logical column mapping, normalized lists, nested JSON round trip, request ownership, encrypted storage and hidden output. Concrete numeric, choice, timestamp, link, password and vector options are in the reference and their owning tests.', 'This lab does not prove vector-index support, generic embedding generation, a nested schema validator or all custom-field lifecycle hooks. Use focused tests for the field you add, including input/query/storage/display differences.'], links: [{ label: 'Full Fields API', articleId: 'fields-api' }, { label: 'Queries', articleId: 'queries' }, { label: 'Commit a schema change', articleId: 'migrations' }] },
	], codeSamples: samples, relatedIds: ['fields-api', 'active-record', 'queries', 'migrations', 'cookbook-secrets'],
};

export const queriesArticle: DocArticle = {
	id: 'queries', area: 'services', group: 'Data', label: 'Queries', title: 'Query with logical fields', summary: 'Scope private data, select what you need and keep the database work visible.', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/ActiveQueryBuilder.ts', examplePaths: examples, testPath: evidence.testPath, verifiedExample: evidence, includeSourceDocument: false,
	sections: [setup, run,
		{ id: 'scope', title: 'Start with authorized ownership', paragraphs: ['Use `FieldNote.where({ owner, id }).firstOrFail()` when the caller must own the note. The logical owner field maps to owner_id; do not duplicate that mapping in normal queries.', '`first()` returns a record or null. `firstOrFail()` throws `RecordNotFoundError`. A missing record and a different owner should normally have the same public response. `wherePk()` alone does not enforce ownership.'], codeSampleId: 'runner-source' },
		{ id: 'bounds', title: 'Bound reads and aggregate in SQL', paragraphs: ['`all()` hydrates every matching row. Add `limit()` and a deterministic `orderBy()` before collecting lists. For ordinary paging use `limit()`/`offset()` and a stable tie-break such as id; deep offset paging may need a database-specific strategy.', '`count()` runs an aggregate without hydrating every record. `select("code")` requests logical fields, while the primary key is retained for model identity. An unselected property may look null/default: that does not prove the stored value is empty. Do not treat partial records as complete DTOs.'] },
		{ id: 'filters', title: 'Filters, hidden selects and relationships', paragraphs: ['Use `where()`, `whereIn()`, `whereNull()` and `whereNotNull()` for field-aware filtering. `withField()` deliberately adds a normally excluded field; it does not override hidden JSON output.', '`with()` eagerly loads declared link relations to avoid repeated lookups when you already know the relations needed. It is not permission to traverse an unbounded graph. Select bounded data and inspect query counts when adding loops.', 'Soft-delete models exclude trashed records by default. `withTrashed()`, `onlyTrashed()`, `restore()` and `forceDelete()` change that behavior. Force deletion is destructive; design permissions and retention before using it.'], links: [{ label: 'Every query signature', articleId: 'active-record-api', sectionId: 'query-methods' }] },
		{ id: 'writes', title: 'Bulk writes are a deliberate choice', paragraphs: ['`patch()` converts and validates dirty fields for a bulk update, but does not hydrate each row and run an entire per-record business workflow. Select only trusted writable keys and include an ownership predicate.', '`delete()` and `forceDelete()` can affect all matching records. An unscoped builder is not made safe by ActiveRecord. Prefer a scoped record workflow until a bulk operation is justified and tested.'] },
		{ id: 'escape', title: 'Use SQL when SQL is the right tool', paragraphs: ['`toKnex()`, `whereColumn()` and `whereRaw()` are database-level escape hatches. At that boundary you own physical column names, parameter binding, result hydration and authorization. Never interpolate user input into raw SQL.', 'The lab reads one raw row solely to prove ciphertext is stored. Normal model data stays on the field-aware API. For joined read shapes, use `ActiveProjection` to reuse field conversion instead of manual JSON/date cleanup.', '`whereVectorSimilarTo()` is a specialist dialect-aware query, not an embedding generation service. Verify actual database/version/index support before relying on it.'], links: [{ label: 'Projection and query APIs', articleId: 'active-record-api' }] },
		serviceLabTesting('db', 'runFieldNotes'), testSection,
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['The shared SQL lab proves logical filters, owner scope, selected fields, default/excluded secret loading and aggregate counts. The Workspace notes lab also proves bounded stable ordering and cross-workspace edit/delete denial.', 'Eager loading, soft-delete recovery, bulk writes, joins and vector similarity are explained/reference-linked, not claimed as demonstrated by this lab. Their existing service tests remain separate evidence.'], links: [{ label: 'Scoped notes workflow', articleId: 'guide-workspace-notes' }, { label: 'Advanced query API', articleId: 'active-record-api' }] },
	], codeSamples: samples, relatedIds: ['fields', 'active-record-api', 'guide-workspace-notes', 'cookbook-transactions'],
};

export const encryptedFieldsArticle: DocArticle = {
	id: 'cookbook-secrets', area: 'cookbook', group: 'Common problems', label: 'Encrypted fields', title: 'Store an integration secret safely', summary: 'Persist an encrypted model value, load it only in authorized server code and keep it out of public JSON.', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/fields/EncryptedJsonField.ts', examplePaths: examples, testPath: evidence.testPath, verifiedExample: evidence, includeSourceDocument: false,
	sections: [setup, run,
		{ id: 'field', title: 'Declare a hidden, opt-in field', paragraphs: ['The model declares `integration` with `encryptedJson()` and `selectedByDefault: false`. It stores versioned ciphertext in integration_secret, not JSON that can be queried.', 'The request fillable list excludes it. Assign a credential only from a trusted integration workflow; never offer arbitrary access to decrypted data.'], codeSampleId: 'model-source' },
		{ id: 'read', title: 'Authorize, select, use and forget', paragraphs: ['The runner assigns a synthetic token, saves it and proves that the ordinary read does not load it. A scoped `withField("integration")` read recovers it while `toJSON()` still omits it.', 'Only the lab uses a fresh ephemeral key and low-level SQL inspection. Persistent applications must retain one securely provisioned APP_KEY across API/worker processes, backups and restarts. Do not print secrets to prove storage worked; compare in a test and return a boolean.'], codeSampleId: 'runner-source', links: [{ label: 'Persistent keys and integrity failures', articleId: 'security' }] },
		{ id: 'failure', title: 'Protect unreadable data', paragraphs: ['A wrong key or changed table/column context makes decryption fail. Do not treat failure as a blank secret or overwrite the existing ciphertext. Preserve it while diagnosing configuration and key restore.', 'The field automatically authenticates table/column, not row ownership. Query authorization still matters. Renaming a table/column with existing encrypted data requires a deliberate decrypt/re-encrypt plan, not only a schema rename.'] },
		serviceLabTesting('db', 'runFieldNotes'), testSection,
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['The SQL test proves ciphertext storage, authorized selection, default exclusion, request protection and hidden public output. The Security lab separately proves tampering/context/wrong-key failure and original-key recovery.', 'Key rotation, external key management, searchable encryption and an integration settings UI remain application work.'], links: [{ label: 'Security lab', articleId: 'security' }, { label: 'Encrypted field contract', articleId: 'fields-api', sectionId: 'encrypted-json' }] },
	], codeSamples: samples, relatedIds: ['fields', 'security', 'queries'],
};

export const fieldsApiArticle = createApiReference({ id: 'fields-api', label: 'Fields API', packageName: '@db3.ai/app/db', sourcePath: 'packages/app/src/db/README.md', guideId: 'fields', references: [['lifecycle', 'Field lifecycle and configuration', 'dist/db/FieldType.d.ts'], ['factory', 'Model field factory', 'dist/db/fields/field.d.ts'], ...(['String', 'Text', 'Boolean', 'Integer', 'Decimal', 'ChoiceString', 'Email', 'Url', 'Timestamp', 'Ulid', 'CharUuid', 'Json', 'JsonString', 'StringList', 'Password', 'Link', 'Vector'] as const).map(name => [name.toLowerCase(), `${name} field`, `dist/db/fields/${name}Field.d.ts`] as const), ['encrypted-json', 'Encrypted JSON field', 'dist/db/fields/EncryptedJsonField.d.ts']] });
