import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const fileEvidence = serviceLabEvidence('media', 'runPrivateFiles', 'Authenticates two users, uploads a private text file, rejects foreign reads/deletes and invalid uploads, then deletes and uploads again.', 'Disposable MariaDB/MySQL, temporary local storage and injected HTTP requests; no listening port or external API.');

export const privateFilesArticle: DocArticle = {
	id: 'guide-files', area: 'guides', group: 'Application guides', label: 'Files and media', title: 'Upload and download private files',
	summary: 'A file ID is not permission to read it. Start with a small, authenticated text-file endpoint and keep the policy visible.',
	packageName: '@db3.ai/app/media', sourcePath: 'packages/app/src/media/README.md', examplePaths: ['packages/app/src/media/examples/createPrivateFileServer.ts', 'packages/app/src/media/examples/runPrivateFiles.ts'], testPath: fileEvidence.testPath, verifiedExample: fileEvidence,
	sections: [
		{ id: 'setup', title: 'Set up the lab', paragraphs: ['Use Node.js 24, the installed app and development tools from Installation, and a dedicated SQL account allowed to create/drop `db3_app_test_*` databases. The lab creates the Auth and Media tables, two users and a temporary storage directory; it removes them afterwards.', 'Install Fastify explicitly because this application owns its HTTP adapter. No public account registration route or web UI is added by this lab.'], codeSampleId: 'http-install', links: [{ label: 'Installation and test database', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Password and token lifecycle', articleId: 'auth' }] },
		{ id: 'copy', title: 'Copy the files', paragraphs: ['Copy the shipped Media examples into your independent application. The endpoint and runner stay separate so your application can reuse the routes with its own boot and shutdown policy.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run the workflow', paragraphs: ['Expect upload `201`, missing authentication `401`, another user’s read/delete `404`, empty or JSON uploads `400`, oversized input `413`, deletion `204`, and a successful retry `201`. Unsupported content types such as `application/octet-stream` are rejected earlier by Fastify with `415`. The test checks that rejected uploads create no file rows and that deletion removes the bytes.'], codeSampleId: 'run-lab' },
		{ id: 'routes', title: 'Keep authorization next to the file lookup', paragraphs: ['`POST /files` accepts non-empty `text/plain` up to 64 KiB. Auth resolves the user from a bearer token. The owner and generated path come from the application, never a submitted owner ID or filename.', '`GET /files/:id` and `DELETE /files/:id` resolve the current user’s library, then query by both file ID and library. A missing or foreign file gets the same `404`. Scope metadata does not enforce permissions by itself.', 'Each request enters `application.requestContext.run()`. The response selects only the upload ID/name/size, rather than returning storage paths or auth records.'], codeSampleId: 'routes-source' },
		{ id: 'delivery', title: 'Deliver privately', paragraphs: ['Download responses stream the already-authorized file with `private, no-store`, attachment disposition and `nosniff`. The filename is fixed, so request input cannot become a response header.', 'Use HTTPS outside the local lab. Keep bearer tokens out of logs, URLs and public browser storage. For a browser application, follow the starter’s server-side HttpOnly cookie transport and origin checks instead of inventing a token-storage policy.'], links: [{ label: 'Starter authentication', articleId: 'starter-app' }] },
		{ id: 'limits', title: 'Choose the next boundary deliberately', paragraphs: ['This small upload is bounded and buffered by Fastify. It is not a large-file upload protocol. Multipart parsing, resumable offsets, quotas, virus scanning, expiring temporary files and client-disconnect handling need an adapter with their own tests.', 'For images, validate the detected type and use canonical reconstruction, not this text endpoint. Public publication needs a separate policy. Deletion across SQL and storage is not atomic; references, recovery and orphan reconciliation remain application work.'], links: [{ label: 'Image reconstruction and variants', articleId: 'media', sectionId: 'images' }, { label: 'Large streamed exports', articleId: 'cookbook-streams' }] },
		{ id: 'scenario', title: 'Run without opening a port', paragraphs: ['The runner uses real framework services and `server.inject()`, so the same route code is tested without a listening socket. It never prints tokens or passwords.'], codeSampleId: 'runner-source' },
		serviceLabTesting('media', 'runPrivateFiles'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the brief and add a third user. Keep assertions for unauthorized deletion, unchanged row count after failure, byte cleanup and successful retry. Socket disconnects and proxy behavior require additional real-network tests; injection does not prove those.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Tested: real authentication, per-user library authorization, bounded text input, controlled errors, private response headers, streamed download, deletion and retry. Not implemented here: project memberships, browser upload UI, arbitrary file formats or public sharing.'], links: [{ label: 'Media API', articleId: 'media-api' }, { label: 'Storage API', articleId: 'storage-api' }] },
	], codeSamples: [...serviceLabSamples('media', 'runPrivateFiles'), { id: 'http-install', title: 'Install the HTTP adapter', language: 'bash', code: 'npm install fastify@5' }, { id: 'routes-source', title: 'examples/createPrivateFileServer.ts', language: 'typescript', code: serviceExampleSources.createPrivateFileServer }, { id: 'runner-source', title: 'examples/runPrivateFiles.ts', language: 'typescript', code: serviceExampleSources.runPrivateFiles }], relatedIds: ['auth', 'media', 'storage', 'cookbook-streams'],
};

const streamEvidence = serviceLabEvidence('storage', 'runStreamExport', 'Streams 50,000 CSV rows, interrupts a staged write, preserves the previous export, removes partial bytes and retries.', 'Temporary local filesystem, no SQL, HTTP socket or remote provider.');

export const streamsArticle: DocArticle = {
	id: 'cookbook-streams', area: 'cookbook', group: 'Common problems', label: 'Large files', title: 'Stream an export and clean up failure', summary: 'Write incrementally, publish only a completed file, and leave the last successful export available when generation fails.',
	packageName: '@db3.ai/app/storage', sourcePath: 'packages/app/src/storage/README.md', examplePaths: ['packages/app/src/storage/examples/writeCsvExport.ts', 'packages/app/src/storage/examples/runStreamExport.ts'], testPath: streamEvidence.testPath, verifiedExample: streamEvidence,
	sections: [
		{ id: 'setup', title: 'Set up', paragraphs: ['Use the standalone app and development tools from Installation. This example needs only Node.js and temporary local storage. It does not open a database or contact a provider.'], links: [{ label: 'Install the tools', articleId: 'installation' }] },
		{ id: 'copy', title: 'Copy the export', paragraphs: ['The writer accepts an already-selected disk and authorized destination. The runner owns its temporary directory and removes it in `finally`.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect `lines: 50001` (header plus 50,000 rows), `pendingFiles: 0`, and true values for completion, interruption rejection, preserving the previous file and recovery. Counting the returned stream does not retain the whole export.'], codeSampleId: 'run-lab' },
		{ id: 'write', title: 'Stage before publishing', paragraphs: ['`Readable.from()` produces one row at a time. `writeStream()` consumes the stream before `move()` publishes it. A unique staging path prevents a failed producer from truncating the previous destination.', 'The catch path destroys the source and removes its partial staging object. Storage may wrap the original stream error in `cause`. If cleanup itself fails, surface that failure and reconcile the owned temporary path; do not pretend the operation completed.', 'These synthetic CSV values are safe. Real exports must escape delimiters, quotes and newlines, and consider spreadsheet formula injection when handling untrusted cells.'], codeSampleId: 'writer-source' },
		{ id: 'read', title: 'Consume without buffering', paragraphs: ['Use `pipeline()` to connect the readable to a writable and propagate errors. Avoid `readToBuffer()` or `readToString()` when the file size is unbounded. The runner counts bytes/newlines incrementally and compares the byte count with storage metadata.'], codeSampleId: 'runner-source' },
		{ id: 'boundaries', title: 'Know what the stream does not solve', paragraphs: ['Local rename and remote object moves do not share an atomicity guarantee. Serialize competing publishers or use immutable versioned destinations plus an application-owned pointer. This test does not certify an S3 provider.', 'An HTTP adapter must authorize before streaming and stop work on client disconnect. A queue export should be retry-safe and avoid publishing duplicate side effects. This lab proves producer failure cleanup, not network cancellation or crash recovery.'], links: [{ label: 'Private HTTP download', articleId: 'guide-files' }, { label: 'Background work', articleId: 'guide-background' }] },
		serviceLabTesting('storage', 'runStreamExport'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the row count and move the controlled failure to another row. Keep the old-destination and empty-staging assertions. Test your real driver with a dedicated bucket before relying on its move behavior.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage', paragraphs: ['Tested: real local streaming, complete output, producer failure, previous-file preservation, partial cleanup and retry. Still to build: a socket-disconnect trial, resumable uploads and remote-driver failure/concurrency conformance.'], links: [{ label: 'Complete Storage API', articleId: 'storage-api' }] },
	], codeSamples: [...serviceLabSamples('storage', 'runStreamExport'), { id: 'writer-source', title: 'examples/writeCsvExport.ts', language: 'typescript', code: serviceExampleSources.writeCsvExport }, { id: 'runner-source', title: 'examples/runStreamExport.ts', language: 'typescript', code: serviceExampleSources.runStreamExport }], relatedIds: ['storage', 'guide-files', 'queue-overview'],
};

export const storageApiArticle = createApiReference({ id: 'storage-api', label: 'Storage API', packageName: '@db3.ai/app/storage', sourcePath: 'packages/app/src/storage/README.md', guideId: 'storage', references: [['manager', 'Manager and disk configuration', 'dist/storage/Storage.d.ts'], ['disk', 'Disk operations and values', 'dist/storage/types.d.ts'], ['listing', 'Lazy listings', 'dist/storage/contracts/StorageListing.d.ts'], ['paths', 'Path validation', 'dist/storage/path.d.ts'], ['contents', 'Content conversion', 'dist/storage/storageContentsToBuffer.d.ts'], ['mime', 'MIME helpers', 'dist/storage/mimeTypeFromPath.d.ts']] });
export const mediaApiArticle = createApiReference({ id: 'media-api', label: 'Media API', packageName: '@db3.ai/app/media', sourcePath: 'packages/app/src/media/README.md', guideId: 'media', references: [['manager', 'Managed file and library operations', 'dist/media/MediaManager.d.ts'], ['inputs', 'Inputs and results', 'dist/media/types.d.ts'], ['options', 'Service options', 'dist/media/contracts/MediaOptions.d.ts'], ['file', 'File model', 'dist/media/MediaFile.d.ts'], ['library', 'Library model', 'dist/media/MediaLibrary.d.ts'], ['item', 'Browser item model', 'dist/media/MediaItem.d.ts'], ['request', 'Image request parsing', 'dist/media/image/ImageVariantRequest.d.ts'], ['processor', 'Image processing contract', 'dist/media/image/contracts/ImageProcessor.d.ts'], ['variant', 'Variant results', 'dist/media/image/contracts/ImageVariant.d.ts'], ['cache', 'Variant cache options', 'dist/media/image/contracts/ImageVariantCacheOptions.d.ts'], ['error', 'Reconstruction failures', 'dist/media/image/ImageReconstructionError.d.ts']] });
