import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const evidence = serviceLabEvidence('flows', 'runTextFlow', 'Persists and runs a two-block graph, inspects steps/logs, fails blank input and replays original/latest definitions.', 'Disposable SQL queue, temporary file definition store, no provider or graph UI.');
export const flowsArticle: DocArticle = {
	id: 'flows', area: 'services', group: 'Application', label: 'Flows', title: 'Run a durable flow', summary: 'Use a flow when the steps, values and replay history matter. Start with a small sequential graph, not an arbitrary execution engine.',
	packageName: '@db3.ai/app/flows', sourcePath: 'packages/app/src/flows/README.md', examplePaths: ['FlowExampleApp', 'createTextFlow', 'normalizeTextBlock', 'uppercaseTextBlock', 'runTextFlow'].map(name => `packages/app/src/flows/examples/${name}.ts`), testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Wire the service into your app', paragraphs: ['Use the independent app/tools and test SQL credentials from Installation. Flows is an explicit app extension: the base `App` does not automatically provide a `flows` getter. The example subclass registers it through the normal `service()` cache.', 'Every producer and worker needs this boot wiring, definition store and block registry. Initializing `Flows` registers `FlowStepJob`; that queued job resolves `app().flows` when restored. Production apps migrate `QueuedJob`, `FailedJob` and `FLOW_MODELS` before running workers.'], codeSampleId: 'app-source', links: [{ label: 'Installation and test SQL', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Application services', articleId: 'app' }] },
		{ id: 'copy', title: 'Copy the flow', paragraphs: ['The five files separate app wiring, graph data, two executable blocks and the disposable runner. Definitions are stored in temporary files by this lab; keep application definitions in a deliberate versioned location.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run and inspect it', paragraphs: ['Expect `completed`, output `CLIENT NOTE`, two steps and a recorded progress log. Blank input fails with `Note text cannot be blank.`. Replaying repaired input with the original definition gives `FIXED NOTE`; replaying the latest definition gives `Updated: CLIENT NOTE`. All temporary tables and files are removed.'], codeSampleId: 'run-lab' },
		{ id: 'block', title: 'Give each block a small contract', paragraphs: ['`defineBlock()` describes named input/output ports, optional configuration and one executable function. The graph validates basic value types. Your block still validates business meaning, such as a string that contains more than whitespace.', 'Keep database work in app-owned blocks with scoped models. There is no generic arbitrary-SQL block. The context gives run/step identities and durable `log()`; avoid putting secrets or sensitive source values in it.'], codeSampleId: 'normalize-source' },
		{ id: 'configuration', title: 'Separate configuration from input', paragraphs: ['The formatting block has a `prefix` configuration default. Configuration is resolved from the block occurrence, while text arrives through a named connection. Editor hints can help a host render a form; they do not change runtime validation.'], codeSampleId: 'uppercase-source' },
		{ id: 'definition', title: 'Keep the graph as source data', paragraphs: ['The definition contains stable ULIDs, ports, connections and positions. Preserve IDs when editing an existing graph. `saveDefinition()` validates before writing; pass `expectedRevision` to detect a stale file-store edit.', 'The current compiler accepts one connected sequential path. Branches, merges and cycles are rejected. A visual position does not define execution order. The file store writes deterministic JSON and uses content revisions; it is not a multi-writer database transaction or untrusted filesystem sandbox.'], codeSampleId: 'definition-source' },
		{ id: 'worker', title: 'Dispatch and process the steps', paragraphs: ['`run()` creates durable run/step state and dispatches a flow-step job to `flows`. The lab drains ready jobs with a finite safety limit. Production needs a supervised queue worker consuming that same queue.', '`runDetails()` returns the run, ordered steps and lifecycle/log events. Captured input/output has a default one-megabyte boundary. There is no automatic secret redaction or tenant authorization; scope any history/API access in your app.'], codeSampleId: 'runner-source' },
		{ id: 'replay', title: 'Repair, then choose what to replay', paragraphs: ['Replay creates a new linked run. `definition: "original"` uses the stored graph snapshot; `"latest"` resolves current source. You can supply replacement input explicitly. The lab changes the second block configuration and proves the two modes differ.', 'The snapshot contains definitions, not a copy of executable JavaScript. Replaying an old graph still uses registered runtime code. Version block types when code changes would break historic behavior. Side-effecting blocks need idempotency: replay can repeat work.'] },
		{ id: 'nested', title: 'Compose a child flow', paragraphs: ['Structural `flow.input`, `flow.output` and `flow.subflow` blocks are registered by the service. A subflow occurrence supplies a child `flowId`; its public ports come from the child definition.', 'The parent waits while a linked child run executes. Nested definitions are captured for original replay; latest replay resolves current source. The service integration tests cover nested waiting/failure/replay, but the first lab stays a two-block path. A nested-flow cookbook and designer integration remain follow-ups.'] },
		serviceLabTesting('flows', 'runTextFlow'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the prefix or add another pure block. Keep the failure, repair, replay-link and original/latest assertions. This lab uses one attempt to make terminal failure immediate; configure retry policy for the actual operation rather than copying that as a production default.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and API', paragraphs: ['Tested: real file definitions and SQL queue, App boot, two blocks, input/business validation, progress, terminal failure and replay modes. Explained/reference: nested graphs, editor contracts, payload bounds, revisions and production safety. Branching, generic SQL execution, credentials in captured values and designer UI are not promised.'], links: [{ label: 'Complete Flows API', articleId: 'flows-api' }, { label: 'Queue operation', articleId: 'queue-overview' }] },
	], codeSamples: [...serviceLabSamples('flows', 'runTextFlow'), { id: 'app-source', title: 'examples/FlowExampleApp.ts', language: 'typescript', code: serviceExampleSources.flowExampleApp }, { id: 'normalize-source', title: 'examples/normalizeTextBlock.ts', language: 'typescript', code: serviceExampleSources.normalizeTextBlock }, { id: 'uppercase-source', title: 'examples/uppercaseTextBlock.ts', language: 'typescript', code: serviceExampleSources.uppercaseTextBlock }, { id: 'definition-source', title: 'examples/createTextFlow.ts', language: 'typescript', code: serviceExampleSources.createTextFlow }, { id: 'runner-source', title: 'examples/runTextFlow.ts', language: 'typescript', code: serviceExampleSources.runTextFlow }], relatedIds: ['queue-overview', 'scheduler', 'serialization'],
};

export const flowsApiArticle = createApiReference({ id: 'flows-api', label: 'Flows API', packageName: '@db3.ai/app/flows', sourcePath: 'packages/app/src/flows/README.md', guideId: 'flows', references: [['constants', 'Lifecycle and replay constants', 'dist/flows/constants.d.ts'], ['system-blocks', 'Built-in structural block registry', 'dist/flows/blocks/index.d.ts'], ['input-block', 'Flow input block', 'dist/flows/blocks/FlowInput.d.ts'], ['output-block', 'Flow output block', 'dist/flows/blocks/FlowOutput.d.ts'], ['subflow-block', 'Nested flow block', 'dist/flows/blocks/Subflow.d.ts'], ['models', 'Required model inventory', 'dist/flows/models/index.d.ts'], ['step-job', 'Registered flow-step job', 'dist/flows/FlowStepJob.d.ts'],['service', 'Flow operations and details', 'dist/flows/Flows.d.ts'], ['options', 'Service and worker contract', 'dist/flows/contracts/FlowsService.d.ts'], ['definition', 'Source and execution definitions', 'dist/flows/contracts/FlowDefinition.d.ts'], ['block', 'Blocks and context', 'dist/flows/contracts/FlowBlock.d.ts'], ['values', 'Values and editor hints', 'dist/flows/contracts/FlowValue.d.ts'], ['runs', 'Runs and replay', 'dist/flows/contracts/FlowRun.d.ts'], ['store', 'Definition store contract', 'dist/flows/contracts/FlowDefinitionStore.d.ts'], ['file-store', 'File store and conflicts', 'dist/flows/drivers/FileFlowDefinitionStore.d.ts'], ['define', 'Block factory', 'dist/flows/defineBlock.d.ts'], ['registry', 'Block registry', 'dist/flows/FlowBlockRegistry.d.ts'], ['compiler', 'Compiler', 'dist/flows/FlowCompiler.d.ts'], ['compile-contract', 'Compiled contracts', 'dist/flows/contracts/FlowCompiler.d.ts'], ['validation', 'Value validation', 'dist/flows/flowValueValidator.d.ts'], ['definition-errors', 'Definition errors', 'dist/flows/FlowDefinitionError.d.ts'], ['errors', 'Runtime errors', 'dist/flows/errors.d.ts'], ['run-model', 'Run model', 'dist/flows/models/FlowRun.d.ts'], ['step-model', 'Step model', 'dist/flows/models/FlowStepRun.d.ts'], ['event-model', 'Event model', 'dist/flows/models/FlowRunEvent.d.ts']] });
