import type { DocArticle } from '../docs';

export const introductionArticle: DocArticle = {
	id: 'welcome', area: 'start', group: 'Get started', label: 'Introduction', title: 'Build an app with db3.ai',
	summary: 'A TypeScript application framework for getting useful features built: models, authentication, files, background work and server-side AI.',
	packageName: '@db3.ai/app', sourcePath: 'packages/app/README.md', includeSourceDocument: false,
	sections: [
		{ id: 'start', title: 'Start with an app that already does something', paragraphs: ['The Notes + AI starter gives you a Vue and DOM Studio shell, a landing page, password login and private notes. Add your own OpenAI key on the server to enable note summaries. The app still works without a key.', 'Start with the starter guide. It covers MariaDB, migrations, running locally, tests and your first model change. You build in your own application directory.'], links: [{ label: 'Create the Notes + AI starter', articleId: 'starter-app' }] },
		{
			id: 'vision',
			title: 'The vision: software understood by humans, AI and machines',
			paragraphs: [
				'db3.ai is being designed for a new kind of software team: humans, AI collaborators and machines working through the same application knowledge. The aim is not to replace code with pictures. It is to make the framework understandable at multiple levels: source code and explicit contracts for depth, consistent self-describing definitions for AI and automation, and visual models for relationships, state and large-scale flows.',
				'Humans recognise structure visually much faster than they can reconstruct it from pages of text. When framework services can describe their models, actions, permissions, jobs, events and runtime state, tools can render those facts as maps and workflows instead of inventing a second version of the application. Teams can move between overview and code, focus on larger concepts and process, and keep every change inspectable.',
				'That relationship should work in both directions. Changes in code, configuration and runtime state should update the map. Where visual editing is supported, changing the map should use the same framework operations to produce validated, reviewable changes to normal application source, configuration and migrations. The visual workspace must never become an opaque second source of truth.',
				'This visual workspace is product direction. Today\'s public APIs, source-backed documentation, service contracts and telemetry are foundations for it; they do not yet constitute a complete visual editor.',
			],
			visual: 'framework-vision',
		},
		{ id: 'availability', title: 'Install the preview', paragraphs: ['The framework and creator are not published to npm yet. Follow the starter guide to install matching package tarballs. After npm publication, use the create command below.', 'That command creates an application. Running database-backed features still requires a database and the documented app configuration. Docker is optional; local MariaDB is supported.'], codeSampleId: 'create' },
		{ id: 'smaller', title: 'Start smaller if you prefer', paragraphs: ['Install the runtime and build a minimal HTTP app, or use one service in a script. The first HTTP example needs no database, Vue or cloud credentials. It includes runnable requests, validation, shutdown and tests.'], links: [{ label: 'Install the runtime', articleId: 'installation' }, { label: 'Run your first HTTP app', articleId: 'create-app' }] },
		{ id: 'model', title: 'Keep the database visible', paragraphs: ['ActiveRecord is a useful way to organise an application and move quickly. Fields own conversion and validation so the same rules can be reused across models. The framework does not remove the need to understand queries, transactions or indexes.', 'Use the normal model API for normal work and the database escape hatch when the problem needs it. Application permissions and business rules remain in your app.'], links: [{ label: 'ActiveRecord and the field-first model', articleId: 'active-record' }] },
		{ id: 'features', title: 'Build the next feature', paragraphs: ['Use Auth for accounts, Storage and Media for files, Queue for durable background work and Scheduler for recurring jobs. Each service guide separates the first useful result from advanced options and operational limits.', 'Build AI features with agent classes, function calls, saved conversations, image generation, embeddings and request tracking. Your app owns the features and billing policy; the framework manages provider execution and persistence.'], links: [{ label: 'Configure your application', articleId: 'app-config' }, { label: 'Queue a real report', articleId: 'queue-overview' }, { label: 'Find a guide by problem', articleId: 'solve-a-problem' }] },
		{ id: 'testing', title: 'Use the examples as working code', paragraphs: ['Service examples ship with the package. The website renders their source, expected output and copyable tests. Run the example tests as you adapt the code, and add integration tests for your own providers and deployment.', 'Keep the example test when you change a feature. Advanced references show emitted public signatures, and the source-backed Markdown and AI documentation use the same registered content.'] },
	], codeSamples: [{ id: 'create', title: 'After npm publication only', language: 'bash', code: 'npm create @db3.ai@latest my-app' }], relatedIds: ['starter-app', 'installation', 'app-config', 'active-record'],
};
