import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('logging', 'runNoteLogs', 'Captures real Pino records, tests child context and level filtering, and checks default/custom secret redaction.', 'Node.js 24. Real writable stream and Pino; development HTTP delivery disabled.');

export const loggingArticle: DocArticle = {
	id: 'logging', area: 'services', group: 'Delivery', label: 'Logging', title: 'Write useful, safe logs', summary: 'Record what happened with enough context to investigate it, without copying secrets into your logs.', packageName: '@db3.ai/app/logging', sourcePath: 'packages/app/src/logging/README.md', examplePaths: ['packages/app/src/logging/examples/runNoteLogs.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Capture a note workflow', paragraphs: ['Complete Installation and copy this lab. It uses the real Pino driver and a writable stream, with devtools delivery explicitly disabled. No running log server is required.', 'Application code normally uses `app().log`. The example owns its logger so capture, flush and shutdown are testable in isolation.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'run', title: 'Run and inspect three records', paragraphs: ['Expect `Note saved` at level 30, `Summary failed` at level 50 and `Diagnostics enabled` at level 20. The initial debug record is filtered. Password, token and the custom provider key are absent.', 'The output removes timestamps, process metadata and error stacks for readability. Real production records retain that diagnostic metadata. Only synthetic test secrets are used.'], codeSampleId: 'run-lab' },
		{ id: 'records', title: 'Use fields and a short message', paragraphs: ['Pass a structured object first and a short message second: `log.info({ noteId }, "Note saved")`. Use a child logger for stable request/job/owner context shared by several records.', 'Pass an Error under `err` to retain its type, message, stack and cause. A failure log does not repair the operation or change its HTTP response; the application still owns recovery.'], codeSampleId: 'logging-source' },
		{ id: 'levels', title: 'Control volume', paragraphs: ['Levels are `trace`, `debug`, `info`, `warn`, `error`, `fatal` and `silent`. Default output starts at info, or silent in tests. Supply an explicit level for deterministic tests.', '`log.level` reads/changes the root threshold. Use `enabled: false` to disable creation-time logging and `console: false` to disable stdout. A child shares destinations but is not a separately owned lifecycle resource.'] },
		{ id: 'configuration', title: 'Configure the app logger', paragraphs: ['Pass `log: { level: "info", source: "notes-api", devtools: false, bindings: { release }, redact: ["integration.apiKey"] }` in App options. These are `AppOptions.log`, not arbitrary values under `config.log`.', 'Logging supports these environment variables: `PLATFORM_LOG_LEVEL`, `PLATFORM_LOG_SOURCE`, `PLATFORM_LOG_FORMAT`, `PLATFORM_LOG_DEVTOOLS`, `PLATFORM_DEVTOOLS_EVENTS_URL`, `PLATFORM_DEVTOOLS_HOST` and `PLATFORM_DEVTOOLS_API_PORT`.', 'Development terminals show live pending requests, followed by grouped method, URL, status, duration and readable JSON bodies. Register `registerHttpExchangeMonitor(server)` before Fastify routes to capture bounded, recursively redacted development payloads; streams are never consumed. Production, tests and redirected stdout retain newline-delimited JSON. Set `log.consoleFormat` or `PLATFORM_LOG_FORMAT` to `auto`, `pretty` or `json`; explicit app options take precedence. `NO_COLOR` disables colour. Full redacted records still reach files and devtools; terminal output omits headers and explicitly limits long body previews. One `DevelopmentConsole` coordinates piped child output in multi-process launchers. Interactive development can automatically enable devtools; explicitly disable it when a script/test must not make HTTP requests.'], links: [{ label: 'Logging and devtools options', articleId: 'logging-api', sectionId: 'options' }] },
		{ id: 'redaction', title: 'Redaction is a backstop', paragraphs: ['Defaults remove common password, secret, token, authorization and cookie paths. Custom `redact` paths extend those defaults; `redact: false` disables them.', 'This is path-based removal, not a scanner for arbitrary sensitive text. A key inside a message string, deep unfamiliar field, URL query or Error message may still be logged. Select safe fields, avoid request bodies and test your own paths.', 'Do not send production credentials or customer data to a development ingestion endpoint. Logging is not an audit ledger or secure secret store.'] },
		{ id: 'delivery', title: 'Flush and close at shutdown', paragraphs: ['`flush()` waits for accepted records to reach the driver destination; `close()` flushes and ends an owned worker transport. `App.close()` owns this for the app logger. Avoid `process.exit()` immediately after logging.', 'Devtools delivery is bounded and best-effort: by default 25 records per batch, 100 ms partial-batch delay and up to 1,000 pending events. Failed batches can be discarded; later delivery pauses. Flush is not proof of durable remote ingestion.', 'A manually supplied stream belongs to its creator. This example closes Log then ends the stream. Do not close a shared app logger at the end of each request.'] },
		serviceLabTesting('logging', 'runNoteLogs'),
		{ id: 'run-tests', title: 'Assert records, not console formatting', paragraphs: ['The copied test asserts context, levels, error fields and the absence of three synthetic secrets using the real driver. Add a sensitive field used by your own app and prove its path is removed.', 'The example writes a controlled failure record then enables diagnostics. It does not claim to recover a failed provider request or prove remote devtools delivery.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: structured records, child context, errors, threshold filtering/change, default/custom redaction, flush and direct-stream close. App shutdown and controlled devtools batching/failure have separate service tests.', 'Remote ingestion, retention, indexing, alerting and compliance/audit policy are application/deployment responsibilities. Logs must not trigger business behavior.'], links: [{ label: 'Full Logging API', articleId: 'logging-api' }, { label: 'Application events', articleId: 'events' }] },
	], codeSamples: [...serviceLabSamples('logging', 'runNoteLogs'), { id: 'logging-source', title: 'examples/runNoteLogs.ts', language: 'typescript', code: sources.runNoteLogs ?? '' }], relatedIds: ['logging-api', 'app', 'events', 'security'],
};

export const loggingApiArticle = createApiReference({ id: 'logging-api', label: 'Logging API', packageName: '@db3.ai/app/logging', sourcePath: 'packages/app/src/logging/README.md', guideId: 'logging', references: [['log', 'Log service', 'dist/logging/Log.d.ts'], ['logger', 'Logger calls and bindings', 'dist/logging/contracts/Logger.d.ts'], ['options', 'Logging and devtools options', 'dist/logging/contracts/LoggingOptions.d.ts'], ['driver', 'Driver lifecycle', 'dist/logging/contracts/LoggerDriver.d.ts'], ['pino', 'Pino driver', 'dist/logging/drivers/PinoLoggerDriver.d.ts'], ['http', 'Development HTTP exchange records', 'dist/logging/contracts/HttpExchange.d.ts']] });
