import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('mail', 'runMailPreview', 'Writes and inspects one real file preview, rejects invalid messages and tests controlled provider failure/recovery without sending email.', 'Node.js 24; local temporary files. External HTTP is simulated in tests; no real key, provider or database.');

export const mailArticle: DocArticle = {
	id: 'mail', area: 'services', group: 'Delivery', label: 'Mail', title: 'Mail',
	summary: 'Build and preview an application email locally, then select a transport when you are ready to send it.',
	packageName: '@db3.ai/app/mail', sourcePath: 'packages/app/src/mail/README.md',
	examplePaths: ['packages/app/src/mail/examples/welcomeMessage.ts', 'packages/app/src/mail/examples/runMailPreview.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Preview a welcome email', paragraphs: ['Complete Installation and copy the shipped mail example from your independent app directory. The example deliberately constructs `FileMailTransport`; it cannot send external email even if your shell contains real provider settings.', 'Mail owns message normalization and transport selection. Your application owns the template, authorized recipients, when to send and whether a retry is safe. There is no built-in `app().mail` getter; construct one shared Mail instance or expose it from your own App subclass.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation and tools', articleId: 'installation' }] },
		{ id: 'run', title: 'Run and inspect the preview', paragraphs: ['Expect `transport: "file"`, `files: 1`, `rejectedEmptyRecipients: true` and subject `Welcome to your notes`. The text contains `Ada & team`; the HTML contains `Ada &amp; team`.', 'The lab tries an empty recipient list, repairs the message, writes a real JSON preview, reads it and prints the selected contents. It removes its temporary directory in `finally`. No message is delivered to an inbox.'], codeSampleId: 'run-lab' },
		{ id: 'template', title: 'Keep the template in the application', paragraphs: ['`welcomeMessage()` returns the public `MailMessage` shape. It checks the recipient and display name, produces plain text and escapes name text before putting it in HTML. Use a suitable template renderer when templates grow.', 'Mail itself only checks for a nonempty recipient list and some text or HTML. It does not validate email addresses, sanitize headers or escape HTML. Never turn this example into an unrestricted endpoint that accepts arbitrary recipients or HTML.'], codeSampleId: 'welcome-source' },
		{ id: 'send', title: 'Send once and inspect the result', paragraphs: ['`mail.send()` resolves the default sender and converts a single recipient into an array. A message-level `from` overrides the service default. Supply `text`, `html` or both.', '`MailDelivery` contains a transport, message ID, accepted/rejected addresses and a path for file previews. Provider acceptance is not inbox delivery. Current HTTP transports report submitted recipients as accepted after a successful response; they do not process bounces or delivery webhooks.'], codeSampleId: 'mail-runner' },
		{ id: 'configuration', title: 'Choose a transport explicitly', paragraphs: ['For application boot, `createMailFromEnv(process.env)` reads `MAIL_TRANSPORT`, `MAIL_FROM` and provider settings. Load your `.env` before calling it. Keep credentials on the server and outside Git.', 'Use `file` with a private `MAIL_FILE_DIRECTORY` for local inspection. Resend needs `RESEND_API_KEY`. Mailgun needs both `MAILGUN_API_KEY` and `MAILGUN_DOMAIN`. Select a sender/domain verified for your provider before attempting real delivery.', 'Missing selected-provider credentials fail during construction. A missing or unrecognized transport name currently falls back to file; production boot should allow-list its intended transport so a typo cannot silently become local-only delivery. `MAIL_MAILER` is a legacy fallback.'], codeSampleId: 'mail-environment' },
		{ id: 'app', title: 'Share Mail from your App', paragraphs: ['Create the mail service once during boot or expose a typed getter through `this.service()`. Keep delivery calls in application services and jobs, not in the reusable framework root.', 'File sends and HTTP requests are awaited operations. There is no Mail `close()` API or background retry loop. Custom transports that own pools or handles must expose and run their own cleanup.'], codeSampleId: 'mail-app', links: [{ label: 'App service ownership', articleId: 'app' }] },
		{ id: 'failures', title: 'Failures and retry policy', paragraphs: ['Await `send()` and handle rejection at the application boundary. Mailgun and Resend include provider rejection details; network failures propagate. Do not show raw provider errors to end users or log reset links, credentials and message bodies.', 'Mail makes one attempt. Queue can make delivery durable and retry failures, but an ambiguous timeout may mean the provider accepted the email. Replaying without idempotency can send twice. The current message API does not expose a provider idempotency key, and a custom message header is not a substitute for one. Treat provider-backed exactly-once delivery as a separate application/transport design.'], links: [{ label: 'Queue retries and failure recovery', articleId: 'queue-overview', sectionId: 'retries-and-failures' }] },
		{ id: 'capabilities', title: 'What each transport supports', paragraphs: ['All three built-in transports handle a sender, one or more recipients, subject, plain text and HTML. File and Resend preserve message `headers`; the current Mailgun transport does not forward them.', 'There is no first-class attachment, CC/BCC, reply-to, bulk-send, cancellation, scheduling, streaming, provider timeout/AbortSignal or template API. Use a documented custom transport boundary when your product needs more, and test it; do not pass undocumented fields and assume they are delivered.'], links: [{ label: 'Message and custom transport contracts', articleId: 'mail-api', sectionId: 'messages' }] },
		{ id: 'privacy', title: 'Keep previews private', paragraphs: ['The file transport writes plaintext JSON, including HTML, headers and recipients. Keep its directory outside public storage, restrict filesystem access and define retention. Password reset and invitation links are credentials too.', 'The lab deletes only its own temporary directory. In an app, delivery history and cleanup are product responsibilities; Mail does not prune previews or persist a delivery ledger.'] },
		serviceLabTesting('mail', 'runMailPreview'),
		{ id: 'run-tests', title: 'Run and extend the tests', paragraphs: ['The three tests run the real file transport, validate and escape a message, reject missing provider configuration and simulate an HTTP failure followed by an explicit successful retry. Only external `fetch` is controlled; Mail is real.', 'Change the welcome text and expected preview together. Add your own recipient-policy, safe-link and provider-error tests before exposing mail through a route.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Taught/tested: local preview, sender/recipient/message construction, HTML text escaping, presence validation, missing key, provider failure and explicit retry. Existing service tests also exercise Mailgun request formatting and rejection.', 'Live provider delivery, domain verification, deliverability, attachments, idempotency and webhooks are not proved by this lab. The reference renders every current Mail and built-in transport declaration. A scheduled email report remains a follow-on recipe until its delivery policy is tested.'], links: [{ label: 'Mail API reference', articleId: 'mail-api' }, { label: 'Schedule recurring work', articleId: 'scheduler' }] },
	],
	codeSamples: [...serviceLabSamples('mail', 'runMailPreview'),
		{ id: 'welcome-source', title: 'examples/welcomeMessage.ts', language: 'typescript', code: sources.welcomeMessage ?? '' },
		{ id: 'mail-runner', title: 'examples/runMailPreview.ts', language: 'typescript', code: sources.runMailPreview ?? '' },
		{ id: 'mail-environment', title: 'Local application .env, not required by the isolated lab', language: 'dotenv', code: 'MAIL_TRANSPORT=file\nMAIL_FROM="Notes <hello@example.test>"\nMAIL_FILE_DIRECTORY=storage/mail\n\n# Provider alternatives: set the selected provider and its real server-side key.\n# MAIL_TRANSPORT=resend\n# RESEND_API_KEY=replace-with-your-key\n# MAIL_TRANSPORT=mailgun\n# MAILGUN_API_KEY=replace-with-your-key\n# MAILGUN_DOMAIN=mg.your-domain.example' },
		{ id: 'mail-app', title: 'Application-owned service getter', language: 'typescript', code: "import { App } from '@db3.ai/app/server';\nimport { createMailFromEnv, type Mail } from '@db3.ai/app/mail';\n\nexport class Application extends App {\n\t/** Returns the application-owned mail service, configured once on first use. */\n\tget mail(): Mail {\n\t\treturn this.service('mail', () => createMailFromEnv());\n\t}\n}" },
	], relatedIds: ['mail-api', 'app', 'auth', 'queue-overview', 'scheduler'],
};

export const mailApiArticle = createApiReference({ id: 'mail-api', label: 'Mail API', packageName: '@db3.ai/app/mail', sourcePath: 'packages/app/src/mail/README.md', guideId: 'mail', references: [['messages', 'Message, delivery and custom transport contracts', 'dist/mail/Mail.d.ts'], ['file', 'File preview options', 'dist/mail/transports/FileMailTransport.d.ts'], ['resend', 'Resend options', 'dist/mail/transports/ResendTransport.d.ts'], ['mailgun', 'Mailgun options and error', 'dist/mail/transports/MailgunTransport.d.ts']] });
