import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('db', 'runNoteMigrations', 'Generates/applies initial and additive migrations, preserves an existing note and refuses an unsafe required column without changing source.', 'Node.js 24 with MariaDB and CREATE/DROP test-database permission. Only owned temporary migration files and generated SQL database.');

export const migrationsArticle: DocArticle = {
	id: 'migrations', area: 'services', group: 'Data', label: 'Schema & migrations', title: 'Change the schema without losing the data', summary: 'Generate a reviewable migration, apply it and check that models, files and the database agree.', packageName: '@db3.ai/app/db/migrations', sourcePath: 'packages/app/src/db/README.md', examplePaths: ['packages/app/src/db/examples/runNoteMigrations.ts'], testPath: evidence.testPath, verifiedExample: evidence, includeSourceDocument: false,
	sections: [
		{ id: 'setup', title: 'Use a disposable MariaDB database', paragraphs: ['Complete Installation and its local MariaDB/test-account setup, then copy the database examples. Set the test-only DB_* values in `.env`; unset DATABASE_URL if it points somewhere else. The account must create/drop generated test databases.', 'Generated model migrations currently support MariaDB only. The runner creates a temporary directory and database and removes both in `finally`. It never applies changes to an existing app.'], codeSampleId: 'copy-lab', links: [{ label: 'Install and configure MariaDB', articleId: 'installation' }] },
		{ id: 'run', title: 'Generate, fail safely and repair', paragraphs: ['Expect initialGenerated, unsafeBlocked, blockedPreservedSource, repairedGenerated, matches, titlePreserved and categoryNullable all true. pendingBefore and applied are both 1.', 'The example starts with one saved note. Adding a required category without a default is blocked. Changing the proposal to nullable generates a safe migration, applies it and preserves the note.'], codeSampleId: 'run-lab' },
		{ id: 'manager', title: 'One manager owns the workflow', paragraphs: ['`DatabaseMigrationManager` takes the complete app model registry, an app database connection, MariaDB dialect, absolute migration/snapshot paths and optional ledger policy. This is infrastructure configuration, not an optional db parameter threaded through feature services.', 'The three classes in the lab represent successive versions of the same source model. Never register all three together. Your app changes one model in source and uses the same configured manager from its CLI.'], codeSampleId: 'migration-source' },
		{ id: 'commands', title: 'Use the generated app commands', paragraphs: ['In the Notes starter, edit the model, then run `npm run db:make:migration -- add_note_category`. Review the generated file and snapshot before applying anything. Run `npm run db:migrate`, then `npm run db:check`.', 'Generation compares models to the committed snapshot, not your memory of the live database. It writes frozen source; migration execution applies committed files and does not regenerate models. Check requires snapshot/model agreement, no pending/missing files and compatible live schema.', 'These npm scripts invoke the shared framework CLI: `db3 db:make-migration`, `db3 db:migrate` and `db3 db:check`. The generation script also type-checks your app first. `server/cli.config.ts` registers `databaseCommands` from `@db3.ai/app/db/commands` and supplies the app factory; the framework owns execution and cleanup. Each action has its own file under the database service’s `commands/` directory and uses `app().db.migrations`, configured with `dbOptions: { migrations: { models } }`. The framework locates committed migrations in `server/database/migrations/` and the snapshot at `server/database/schema.snapshot.json` under the app root. No separate `migrations.ts` settings file or migration path configuration is needed. Run `npx db3 --help` from the app root to list registered commands.'], links: [{ label: 'Starter schema-change workflow', articleId: 'starter-app' }, { label: 'Manager methods and results', articleId: 'migrations-api' }] },
		{ id: 'review', title: 'Review generated changes', paragraphs: ['Safe generation includes nullable columns, required columns with static defaults, ordinary non-unique indexes and supported static-default changes. Data-dependent constraints, unsupported type changes and unsafe required columns are blocked for explicit review.', 'For a new required field on existing rows, consider add nullable, deploy compatible code, backfill deliberately, then add the requirement in a reviewed forward migration. Do not invent a default that changes product meaning just to satisfy the generator.', 'Generation uses a source lock and is refused in production. `allowDestructive` deliberately promotes certain removals; it is not a general approval of every risky change. Never use it casually on customer data.'] },
		{ id: 'deploy', title: 'Commit schema inputs and apply them once', paragraphs: ['Commit migration files and the desired snapshot with the model change. API/worker startup must not run install, sync or generation. Deployment applies reviewed files through the migration ledger/lock, then runs check.', 'Never edit an already applied migration. Add a new forward migration. MariaDB DDL is not generally transactionally reversible; a failed migration may leave partial schema changes requiring inspection and recovery.', 'Extra live tables/columns can remain compatible for additive blue/green releases, but missing required schema or mismatched indexes fails check. Baseline adoption is a narrow existing-schema operation, not a way to mark arbitrary migrations complete.'], links: [{ label: 'Full migration status and baseline options', articleId: 'migrations-api' }] },
		serviceLabTesting('db', 'runNoteMigrations'),
		{ id: 'run-tests', title: 'Test migrations against real existing data', paragraphs: ['The copied test creates a real row before the change, proves blocked generation leaves both snapshot and file count unchanged, then checks the repaired migration preserves that row.', 'Add a fixture representing the real data shape before deployment. A successful fresh install alone does not prove an upgrade is safe. Backups and restore verification remain application/deployment work.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: source generation, apply, status/pending, check, unsafe required-column refusal, unchanged source on refusal, nullable recovery and data preservation. Existing migration tests cover locks, defaults, indexes, baseline and production-generation refusal.', 'A production deployment, backfill, destructive rollback, database backup and non-MariaDB migration are not proved here. `Database.install()` is a disposable bootstrap utility, not the deployment workflow.'], links: [{ label: 'Migration API', articleId: 'migrations-api' }, { label: 'Model your data', articleId: 'guide-model-data' }] },
	], codeSamples: [...serviceLabSamples('db', 'runNoteMigrations'), { id: 'migration-source', title: 'examples/runNoteMigrations.ts', language: 'typescript', code: sources.runNoteMigrations ?? '' }], relatedIds: ['migrations-api', 'starter-app', 'fields', 'guide-model-data'],
};

export const migrationsApiArticle = createApiReference({ id: 'migrations-api', label: 'Migrations API', packageName: '@db3.ai/app/db/migrations', sourcePath: 'packages/app/src/db/README.md', guideId: 'migrations', references: [['manager', 'Migration manager', 'dist/db/migrations/DatabaseMigrationManager.d.ts'], ['options', 'Options and workflow results', 'dist/db/migrations/contracts/DatabaseMigration.d.ts'], ['changes', 'Schema change plans', 'dist/db/migrations/contracts/SchemaChange.d.ts'], ['snapshots', 'Schema snapshots', 'dist/db/migrations/contracts/SchemaSnapshot.d.ts'], ['errors', 'Migration errors', 'dist/db/migrations/errors.d.ts'], ['collector', 'Collect model schema', 'dist/db/migrations/ModelSchemaCollector.d.ts'], ['inspector', 'Inspect live schema', 'dist/db/migrations/DatabaseSchemaInspector.d.ts'], ['differ', 'Compare snapshots', 'dist/db/migrations/SchemaDiffer.d.ts'], ['renderer', 'Render frozen migrations', 'dist/db/migrations/renderKnexMigration.d.ts'], ['serialization', 'Serialize snapshots', 'dist/db/migrations/SchemaSnapshotSerializer.d.ts'], ['names', 'Schema naming', 'dist/db/migrations/SchemaNames.d.ts'], ['destructive', 'Explicit destructive promotion', 'dist/db/migrations/promoteDestructiveSchemaChanges.d.ts']] });
