import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const evidence = serviceLabEvidence('scheduler', 'runDailySummary', 'Evaluates a fixed minute, deduplicates a repeat, processes a real database-queued job and reads its successful occurrence.', 'A dedicated MariaDB/MySQL test account and temporary local storage. No clock sleeps or remote providers.');

export const schedulerArticle: DocArticle = {
	id: 'scheduler', area: 'services', group: 'Application', label: 'Scheduler', title: 'Scheduler',
	summary: 'Decide when a task is due, claim its occurrence and hand expensive work to Queue. Inspect what happened without hiding schedule definitions in a database.',
	packageName: '@db3.ai/app/scheduler', sourcePath: 'packages/app/src/scheduler/README.md',
	examplePaths: ['packages/app/src/scheduler/examples/WriteDailySummaryJob.ts', 'packages/app/src/scheduler/examples/registerDailySummary.ts', 'packages/app/src/scheduler/examples/runDailySummary.ts', 'packages/app/src/scheduler/examples/RecoverableSummaryJob.ts', 'packages/app/src/scheduler/examples/runScheduledReplay.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Set up schedules and the queue', paragraphs: ['Scheduler needs `ScheduledOccurrence` in the application database. The database queue also needs `QueuedJob` and `FailedJob`. The lab installs these in a disposable database; application deployments must use migrations.', 'Create one App and register schedules once at process boot. The same bootstrap must register queue job classes in every worker. Resolving `app().scheduler` also attaches the recorder that updates occurrence history from queue lifecycle events.'], links: [{ label: 'Install and configure the SQL lab', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Queue jobs and workers', articleId: 'queue-overview' }] },
		{ id: 'copy', title: 'Copy the daily-summary example', paragraphs: ['The example writes a small summary file through a queued job. It uses a fixed test minute and temporary storage, so it does not wait until tomorrow or dispatch real application work.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect one dispatched occurrence, one skipped duplicate, successful queue/occurrence states, and no due task in the following minute. The file contains `Daily summary ready`.'], codeSampleId: 'run-lab' },
		{ id: 'job', title: 'Put the work in a job', paragraphs: ['The job below has a stable durable name and an empty JSON payload. It replaces a summary file rather than appending duplicate output on retry. Real jobs still need an application-specific idempotency policy, particularly when sending messages or charging credits.'], codeSampleId: 'job-source' },
		{ id: 'definitions', title: 'Register a daily schedule', paragraphs: ['A zero-argument `QueueableJob` class supplies its durable name automatically. For a job with constructor data, pass a fresh-job factory and give the schedule an explicit stable `name()`. Inline `call()` definitions also need a name.', 'Use `daily()` for midnight, `dailyAt("HH:mm")` for a daily time, or `everyMinute()` for bounded background collection. Names must be unique. Daily times use UTC unless you set an IANA `timezone()`; minute schedules are timezone-independent. Weekly/monthly schedules and arbitrary cron expressions are not supported. Minute schedules also catch up after downtime, so jobs must safely check whether work is still due.'], codeSampleId: 'register-source' },
		{ id: 'evaluate', title: 'Evaluate, then process', paragraphs: ['`runDue()` evaluates the current minute. The lab passes a fixed Date explicitly, evaluates it twice, then calls `workNextJob()` to perform the queued work. Dispatch success is not job completion.', 'The unique occurrence claim is per schedule name and UTC minute. That prevents duplicate dispatch for the same claimed minute; it is not an exactly-once guarantee for external side effects.'], codeSampleId: 'runner-source' },
		{ id: 'time', title: 'Cover elapsed minutes and understand time zones', paragraphs: ['The worker evaluates every elapsed UTC minute in order. Jobs due together keep their original scheduled minute even when dispatch crosses later minute boundaries; those later minutes are evaluated next. Catch-up yields periodically without discarding the backlog.', 'For restart recovery, pass an application-owned `SchedulerCheckpoint` to the worker or console. Its `load(firstMinute)` atomically establishes the preceding minute on first use or returns the saved evaluated minute; `save(evaluatedFor)` advances progress after the whole batch and must never move backwards under concurrent writes. A replacement worker resumes after that cursor. Without a durable checkpoint, a new process starts in its current minute. One-off `runDue()` calls still evaluate only the supplied minute.', 'Catch-up uses current definitions and invokes job factories at dispatch time. Local wall-clock schedules follow their selected time zone. A skipped daylight-saving time will not occur; a repeated local time can correspond to two UTC minutes. Choose UTC or add an application business-date policy if the task must run once per business day.'] },
		{ id: 'production', title: 'Run a dedicated scheduler process', paragraphs: ['Use `SchedulerWorker` for a long-running process, or call `runDue()` from a supervised once-per-minute runner. Keep slow work in Queue; `call()` runs directly in the scheduler and is appropriate only for short operations.', 'The framework exports `runSchedulerConsole()` for an application-owned CLI entry point. It accepts an App resolver and bootstrap hook. After wiring that entry point, it supports `scheduler:work`, `scheduler:run`, `scheduler:list` and `scheduler:history --limit=25 --status=failed`.', 'Those are command names for your adapter, not globally installed executables. The runnable lab does not supply a production supervisor or CLI bootstrap. On shutdown, stop the SchedulerWorker before closing the App. Queue workers must use the same code/configuration and initialize the scheduler recorder.'] },
		{ id: 'history', title: 'Inspect history and failures', paragraphs: ['`ScheduledOccurrence` records the name, due minute, queue IDs, attempts, status, timestamps and errors. Queued work can move through queued, running, retrying/deferred, succeeded or failed states. Incomplete evaluations and failed checkpoint writes retry the same minute. Individual event failures remain recorded and do not stop other tasks or later minutes.', 'Use `queue.retryFailed()` for a terminal queued failure. It creates a replacement with a new identity and a `retryOf` link. The original failed queue record and ScheduledOccurrence remain failed for audit, even when that replacement succeeds. Observe the replacement’s queue lifecycle/result and application output; Queue does not retain a general success-history table. Persist recovery on an application-owned report when needed. A claim and queue dispatch are separate transitions: a crash between them can leave a claimed occurrence without a queued job. Monitor and reconcile those cases deliberately; elapsed-minute coverage does not guarantee exactly-once delivery or successful job completion.'], links: [{ label: 'Retries, failure history and replay', articleId: 'queue-overview', sectionId: 'retries-and-failures' }] },
		{ id: 'replay', title: 'Repair work without rewriting history', paragraphs: ['Run `npx tsx examples/runScheduledReplay.ts` after copying the Scheduler examples. It deliberately fails three immediate attempts because a local source is missing, supplies the source, then replays once. No historical application schedule is touched.', 'Expect `originalStatus: "failed"`, `replacementStatus: "succeeded"`, `linked: true`, `newIdentity: true`, one retained failure, zero active jobs and the recovered summary. Re-evaluating the original minute still skips its existing claim. Immediate backoff is for this deterministic lab, not production polling.'], codeSampleId: 'replay-source' },
		{ id: 'recovery-job', title: 'Read the source before replacing output', paragraphs: ['The repairable job reads its local source before writing the report. A missing source therefore cannot overwrite the last output. Replay performs the same normal job contract rather than changing the scheduled audit row.'], codeSampleId: 'replay-job-source' },
		serviceLabTesting('scheduler', 'runDailySummary'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Use a fixed Date in tests instead of sleeping. Try a non-due minute, repeat an already-claimed minute, or make the job fail and inspect the occurrence. The copied test proves the simple successful database-queue path and duplicate claim rejection.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and reference', paragraphs: ['Tested here: registration, daily matching, duplicate claim rejection, SQL queue dispatch/execution and successful history recording. The second copied test repairs a failed scheduled job, checks its replay link/output and confirms the terminal occurrence stays failed. The service-owned Scheduler suite separately covers validation, workers, console behaviour and more lifecycle transitions.', 'Still to write: a complete production CLI/supervisor walkthrough, DST/business-date examples, failed-dispatch reconciliation and an application-owned recovery dashboard. The linked service reference includes additional configuration details.'], links: [{ label: 'Scheduler API', articleId: 'scheduler-api' }, { label: 'Background worker guide', articleId: 'guide-background' }] },
	], codeSamples: [...serviceLabSamples('scheduler', 'runDailySummary'),
		{ id: 'job-source', title: 'examples/WriteDailySummaryJob.ts', language: 'typescript', code: serviceExampleSources.writeDailySummaryJob },
		{ id: 'register-source', title: 'examples/registerDailySummary.ts', language: 'typescript', code: serviceExampleSources.registerDailySummary },
		{ id: 'runner-source', title: 'examples/runDailySummary.ts', language: 'typescript', code: serviceExampleSources.runDailySummary },
		{ id: 'replay-job-source', title: 'examples/RecoverableSummaryJob.ts', language: 'typescript', code: serviceExampleSources.recoverableSummaryJob },
		{ id: 'replay-source', title: 'examples/runScheduledReplay.ts', language: 'typescript', code: serviceExampleSources.runScheduledReplay },
	], relatedIds: ['installation', 'queue-overview', 'storage', 'app'],
};
