import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('security', 'runSecretRoundTrip', 'Round-trips an ephemeral secret and rejects tampering, changed context, a different key and non-JSON input.', 'Node.js 24. Real authenticated encryption and App; no database, dotenv writes or persistent key changes.');

export const securityArticle: DocArticle = {
	id: 'security', area: 'services', group: 'Delivery', label: 'Security', title: 'Encrypt a secret you need to read later', summary: 'Keep reversible secrets encrypted with an application-owned key and explicit ownership context.', packageName: '@db3.ai/app/security', sourcePath: 'packages/app/src/security/README.md', examplePaths: ['packages/app/src/security/examples/runSecretRoundTrip.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Run an isolated encryption lab', paragraphs: ['Complete Installation and copy the example. It generates an ephemeral key only for a disposable App. It does not read/write `.env`, connect to SQL or modify an existing app key.', 'Passwords need one-way hashing through Auth, not reversible encryption. Use Security for values the server genuinely needs to recover, such as an integration credential.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation', articleId: 'installation' }, { label: 'Password authentication', articleId: 'auth' }] },
		{ id: 'run', title: 'Run and check integrity', paragraphs: ['Expect five true values: `roundTrip`, `randomized`, `contextRejected`, `tamperingRejected` and `nonJsonRejected`. No key, plaintext or ciphertext is printed.', 'The example encrypts twice, checks the recovered value, then deliberately changes owner context and one encrypted byte. Both decryption attempts fail safely. The App is closed in `finally`.'], codeSampleId: 'run-lab' },
		{ id: 'encrypt', title: 'Encrypt bytes, text or JSON', paragraphs: ['`encrypt()` returns a versioned text envelope; `decrypt()` returns a Buffer. `encryptJson()` and `decryptJson<T>()` wrap JSON serialization/parsing. The generic type does not validate the decrypted object schema.', 'New payloads use AES-256-GCM with random IVs and authentication tags. The same input gives different ciphertext, so encrypted values are not suitable for equality lookups.'], codeSampleId: 'security-source' },
		{ id: 'key', title: 'Provision one persistent application key', paragraphs: ['In a real app, load `APP_KEY` server-side and pass `config: { security: { key, cipher: "aes-256-gcm" } }` when creating App. `Security` resolves through the active App; it does not accept arbitrary constructor key options.', '`Security.generateKey()` creates a `base64:`-prefixed 32-byte key. Generate it once during provisioning, store it securely, and supply the same value to API and worker processes. Never copy the ephemeral-key-per-run lab pattern into an app that stores ciphertext.', '`ensureAppKey()` reads `APP_KEY` or the working directory’s `.env`, generates a missing key and writes it to `.env`. It preserves existing nonempty values for normal validation and fails if persistence fails. Use it only where that file write is intended; injected production secrets avoid the write.'], links: [{ label: 'Key options and provisioning helper', articleId: 'security-api', sectionId: 'key' }, { label: 'Environment configuration', articleId: 'config' }] },
		{ id: 'context', title: 'Bind ciphertext to its intended use', paragraphs: ['`additionalAuthenticatedData` authenticates a stable context such as owner/field identity. It is not stored in the envelope, so reconstruct exactly the same context when decrypting.', 'Different context fails authentication, but this is not a substitute for access control. Authorize the caller before loading/decrypting a secret. Plan migrations carefully if an identifier used in that context will change.'] },
		{ id: 'fields', title: 'Use an encrypted model field', paragraphs: ['`field.encryptedJson()` gives the model reusable storage conversion and hidden JSON output. Its field context binds payloads to table/column; it does not automatically add row-owner binding.', 'With `selectedByDefault: false`, opt in through `query().withField("integration")` only in server code that needs the value. Hidden output and request-fillable/guarded policy remain separate protections.'], links: [{ label: 'Fields and output policy', articleId: 'fields' }, { label: 'Persisting encrypted values', articleId: 'cookbook-secrets' }] },
		{ id: 'failures', title: 'Handle unreadable data without destroying it', paragraphs: ['Catch `SecurityError` at a safe application boundary. Wrong key, changed context, malformed data and failed integrity checks must not become a silent empty/default secret or an automatic overwrite.', 'Back up keys separately from the database and test restore. Losing the key loses access to encrypted data. Automatic key rotation/keyrings are not implemented; a deliberate re-encryption migration needs both old and new keys.', 'Key material is pinned for the service lifetime. Changing environment/config or constructing another App does not rotate an existing Security instance. Do not log keys, ciphertext, plaintext or raw provider errors containing decrypted credentials.'] },
		serviceLabTesting('security', 'runSecretRoundTrip'),
		{ id: 'run-tests', title: 'Test failures as well as round trips', paragraphs: ['The copied tests use real encryption, check all five lab outcomes, reject another App’s key and prove the original service still decrypts its ciphertext. They use only disposable keys.', 'Add application tests for authorization, field visibility and backup/restore. This isolated lab is not proof of a database migration or a production key recovery.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: JSON/text round trip, randomized ciphertext, tampering/context/wrong-key rejection, original-key recovery, non-JSON rejection and secret-safe output. Provisioning persistence, malformed payloads and key length validation also have service tests.', 'Key rotation, KMS integration, row-level authorization, searchable encryption and secure backup policy are not built-in features. All public Security and payload contracts are linked below.'], links: [{ label: 'Full Security API', articleId: 'security-api' }] },
	], codeSamples: [...serviceLabSamples('security', 'runSecretRoundTrip'), { id: 'security-source', title: 'examples/runSecretRoundTrip.ts', language: 'typescript', code: sources.runSecretRoundTrip ?? '' }], relatedIds: ['security-api', 'config', 'auth', 'cookbook-secrets'],
};

export const securityApiArticle = createApiReference({ id: 'security-api', label: 'Security API', packageName: '@db3.ai/app/security', sourcePath: 'packages/app/src/security/README.md', guideId: 'security', references: [['security', 'Encryption and JSON methods', 'dist/security/Security.d.ts'], ['options', 'App security options', 'dist/security/contracts/SecurityOptions.d.ts'], ['payload', 'Authenticated context', 'dist/security/contracts/SecurityPayload.d.ts'], ['key', 'Local key provisioning', 'dist/security/ensureAppKey.d.ts'], ['errors', 'SecurityError', 'dist/security/SecurityError.d.ts']] });
