import type { DocArticle } from '../docs';
import { frameworkAuthority } from '../generated/framework-authority';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';

const testPath = 'apps/starter/tests/app.test.ts';
const starterTests = (frameworkAuthority.behaviourTestSources as Readonly<Record<string, string>>)[testPath] ?? '';
const tests = { id: 'starter-tests', title: 'tests/app.test.ts', language: 'typescript' as const, code: starterTests };
const commands = { id: 'test-command', title: 'From the generated app root', language: 'bash' as const, code: 'npm test\nnpm run check\nnpm run build' };

export const authWorkflowArticle: DocArticle = {
	id: 'guide-auth', area: 'guides', group: 'Application guides', label: 'Authentication', title: 'Trace login from browser to database', summary: 'Use the starter’s existing login, then understand the session boundary before adding another provider.',
	packageName: '@db3.ai/create', sourcePath: 'apps/starter/README.md', testPath,
	examplePaths: ['apps/starter/server/app.ts', 'apps/starter/server/http/session.ts', 'apps/starter/server/http/createServer.ts'],
	sections: [
		{ id: 'setup', title: 'Start with the generated app', paragraphs: ['Follow Build your first app, including the unpublished tarball preview while the packages are not on npm. Use a new application database, apply migrations, then run `npm run dev`. Open `http://localhost:5173`.', 'Registration, login and notes do not require an OpenAI key. Keep `OPENAI_API_KEY` empty for this walkthrough. This is the starter’s application code, not automatically installed Auth routes.'], links: [{ label: 'Build your first app', articleId: 'starter-app' }] },
		{ id: 'run', title: 'Create an account and sign back in', paragraphs: ['Register a local test account with a name, email and a 12–128 character password. Save a note, reload and confirm it remains. Sign out; private data should no longer be available. Sign in with a wrong password, then the correct one.', 'Use the browser Network panel to inspect `/api/register`, `/api/me`, `/api/login` and `/api/logout`. Success responses do not contain a bearer token. Do not paste cookies or credentials into bug reports.'] },
		{ id: 'boot', title: 'Enable the provider at boot', paragraphs: ['The application enables password authentication in `config.auth.providers`. It can also accept a configured Google client ID. Auth owns account/provider/token records; the generated HTTP adapter chooses the session transport and public routes.'], codeSampleId: 'app-source' },
		{ id: 'session', title: 'Keep the session server-controlled', paragraphs: ['Registration/login issue a seven-day bearer session, then put its opaque value in a host-only `db3_session` cookie with HttpOnly and SameSite=Lax. Production adds Secure. `/api/me` selects only ID, name and email.', 'Every request enters the framework request context. Protected routes call the application helper `requireUser()`, which authenticates the cookie first. Logout revokes the current durable token and clears the cookie; clearing browser state alone would not revoke access.'], codeSampleId: 'session-source' },
		{ id: 'boundary', title: 'Validate the origin and input', paragraphs: ['All non-GET/HEAD/OPTIONS requests must carry an Origin exactly matching `APP_ORIGIN`; foreign or missing origins receive `403`. This includes registration/login, not only requests with an existing session.', 'Fastify rejects extra body properties and invalid lengths. The sign-in/registration endpoints have process-local limits of ten requests per fifteen minutes per rate-limit key. Duplicate registration returns `409`; bad credentials return a generic `401`.', 'Use one consistent browser hostname and port. `localhost` and `127.0.0.1` are different origins. Non-browser clients must explicitly send the configured Origin for this starter API; change the API design deliberately if adding other clients.'], codeSampleId: 'routes-source' },
		{ id: 'providers', title: 'Add social login as a separate feature', paragraphs: ['Setting `GOOGLE_AUTH_CLIENT_ID` prepares the framework provider and public client ID; it does not add a Google button or a credential-exchange route. Implement those together with the provider guide and the same cookie/validation policy.', 'Password recovery email, provider linking/removal UI, recent-authentication checks and session management screens are also follow-ups. Do not auto-link accounts just because their email addresses match.'], links: [{ label: 'Auth providers and account linking', articleId: 'auth', sectionId: 'providers' }, { label: 'Full Auth API', articleId: 'auth-api' }, { label: 'Mail previews', articleId: 'mail' }] },
		{ id: 'testing', title: 'Test the real boundary', paragraphs: ['The generated `tests/app.test.ts` is the source below. It creates a disposable database from committed migrations, exercises HTTP routes with real Auth/ActiveRecord and removes it afterwards. Configure its separate `TEST_DB_*` credentials as shown in the generated README.', 'The suite keeps the real server; only external AI HTTP responses use a synthetic test key and controlled fetch. No live OpenAI request is needed to run these tests.'], codeSampleId: 'starter-tests' },
		{ id: 'run-tests', title: 'Run and extend the tests', paragraphs: ['Add a second account and keep unauthorized/cross-account checks when changing the UI. Test cookie Secure behavior behind your actual HTTPS deployment and configure a shared rate-limit store before running multiple API processes.'], codeSampleId: 'test-command' },
		{ id: 'coverage', title: 'Coverage and production boundaries', paragraphs: ['The supplied tests cover registration, wrong-password recovery, cookie transport, logout revocation, rejected origins, invalid input and owner isolation. Browser/proxy HTTPS, distributed rate limiting, email recovery and live social login require separate deployment/provider trials.'], links: [{ label: 'Build an owned-note API', articleId: 'guide-api' }, { label: 'Auth service lab', articleId: 'auth' }] },
	], codeSamples: [{ id: 'app-source', title: 'server/app.ts', language: 'typescript', code: serviceExampleSources.starterApplication }, { id: 'session-source', title: 'server/http/session.ts', language: 'typescript', code: serviceExampleSources.starterSession }, { id: 'routes-source', title: 'server/http/createServer.ts', language: 'typescript', code: serviceExampleSources.starterServer }, tests, commands], relatedIds: ['starter-app', 'auth', 'guide-api', 'guide-testing'],
};

export const apiWorkflowArticle: DocArticle = {
	id: 'guide-api', area: 'guides', group: 'Application guides', label: 'Build an API', title: 'Build an owned-note JSON API', summary: 'Keep HTTP validation, field conversion and authorization at their own boundaries. Use the starter’s real note routes as the example.',
	packageName: '@db3.ai/create', sourcePath: 'apps/starter/README.md', testPath,
	examplePaths: ['apps/starter/server/models/Note.ts', 'apps/starter/server/http/createServer.ts'],
	sections: [
		{ id: 'setup', title: 'Run the starter first', paragraphs: ['Create the Notes starter, configure its new database, apply migrations and run development. Sign in through the generated UI before trying the browser examples below. AI is optional and not needed for note CRUD.', 'This guide modifies application code generated by `@db3.ai/create`. The backend framework does not silently register these endpoints for every model.'], links: [{ label: 'Create and run the app', articleId: 'starter-app' }, { label: 'Cookie authentication walkthrough', articleId: 'guide-auth' }] },
		{ id: 'model', title: 'Let the fields own conversion', paragraphs: ['The model has logical `owner`, `title` and `body` fields. `owner` maps to `owner_id`; timestamps map to their SQL columns. Normal route code uses logical names and `toJSON()`.', '`requestFillable` allows only title/body. The server assigns the authenticated owner independently. HTTP validation rejects extra submitted properties instead of silently accepting a requested owner. A later model/schema change must go through committed migrations.'], codeSampleId: 'model-source' },
		{ id: 'routes', title: 'Keep the route contract explicit', paragraphs: ['`GET /api/notes` returns at most 100 owned notes, newest first with ID as a tie-breaker. It is a bounded list, not a complete pagination API. `POST /api/notes` creates one and returns `201` with `{ note }`.', '`GET /api/notes/:id` loads one owned note. `PATCH /api/notes/:id` changes supplied title/body fields and preserves omitted fields. An empty patch is rejected. `DELETE /api/notes/:id` deletes the owned record and returns `{ ok: true }`.', 'Every individual lookup includes both ID and owner. A foreign or missing record returns the same `404`. Authentication alone does not authorize access to an arbitrary ULID.'], codeSampleId: 'routes-source' },
		{ id: 'run', title: 'Try it from the signed-in browser', paragraphs: ['Open the browser console on your local starter app and run this snippet. It creates and edits only a new local example note. Same-origin browser fetch includes the session cookie and supplies Origin for writes. The expected responses are `201` then `200`; the title changes while body and owner remain the same.', 'Do not use this snippet on a live application with real customer data. Delete the example note through the same owned API when finished.'], codeSampleId: 'browser-example' },
		{ id: 'errors', title: 'Return useful, safe errors', paragraphs: ['Malformed IDs, extra fields, blank content and excessive lengths return `400`. Missing authentication is `401`; rejected Origin is `403`; absent/foreign notes are `404`. Model values are serialized through the fields, not hand-remapped.', 'The route’s error handler hides SQL errors, stack traces, credentials and provider payloads. The HTTP schema enforces the current note constraints before saving; when adding model rules, decide how those validation errors map into your public response contract rather than letting them become a generic `500`.'] },
		{ id: 'extend', title: 'Add a feature in the right places', paragraphs: ['For an extra persisted field: update the model, request allowlist where appropriate, request/response contract and UI. Generate and inspect its migration, apply it to a disposable app, then test valid and invalid input.', 'For a different access policy, change scoped model queries and tests together. Do not thread optional database parameters through route helpers or bypass field conversion with raw SQL just to add a normal filter.'], links: [{ label: 'Model a feature', articleId: 'guide-model-data' }, { label: 'Migration workflow', articleId: 'migrations' }, { label: 'Query scope and escape hatches', articleId: 'queries' }] },
		{ id: 'testing', title: 'Test persistence and denial', paragraphs: ['The exact generated test below verifies the owned edit, preservation of omitted fields, foreign reads/edits, invalid patches without changed data, deletion and missing-row response. It also covers login and the optional simulated AI boundary.', 'Set `TEST_DB_*` for a disposable SQL account. The test must not point at the application database. A workspace source import is not a substitute for exercising this generated consumer.'], codeSampleId: 'starter-tests' },
		{ id: 'run-tests', title: 'Run the generated checks', paragraphs: ['Run from the generated app root. The test suite uses real framework services, then `check` and `build` validate the client/server application types and browser bundle.'], codeSampleId: 'test-command' },
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Current source/tests cover owned note CRUD, logical fields, strict input, bounded listing, private errors and session/origin policy. Still to add as separate features: pagination cursors, optimistic edit conflicts, shared project membership and an OpenAPI endpoint specification.'], links: [{ label: 'Complete model API', articleId: 'active-record-api' }, { label: 'Private file endpoints', articleId: 'guide-files' }, { label: 'Move expensive work into a queue', articleId: 'guide-background' }] },
	], codeSamples: [{ id: 'model-source', title: 'server/models/Note.ts', language: 'typescript', code: serviceExampleSources.starterNote }, { id: 'routes-source', title: 'server/http/createServer.ts', language: 'typescript', code: serviceExampleSources.starterServer }, { id: 'browser-example', title: 'Local starter browser console', language: 'javascript', code: "const created = await fetch('/api/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'API example', body: 'A private note created through the API.' }) });\nconsole.log(created.status);\nconst { note } = await created.json();\nconst edited = await fetch(`/api/notes/${note.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'Updated API example' }) });\nconsole.log(edited.status, await edited.json());\n// When finished with this local example:\nawait fetch(`/api/notes/${note.id}`, { method: 'DELETE' });" }, tests, commands], relatedIds: ['starter-app', 'guide-auth', 'fields', 'guide-testing'],
};

export const authApiArticle = createApiReference({ id: 'auth-api', label: 'Auth API', packageName: '@db3.ai/app/auth', sourcePath: 'packages/app/src/auth/README.md', guideId: 'auth', references: [['auth', 'Account, provider and session operations', 'dist/auth/Auth.d.ts'], ['identity', 'Account model', 'dist/auth/UserIdentity.d.ts'], ['provider', 'Provider model and safe summary', 'dist/auth/AuthProvider.d.ts'], ['token', 'Token model and safe session', 'dist/auth/AuthToken.d.ts'], ['reset', 'Reset tokens', 'dist/auth/PasswordResetToken.d.ts'], ['driver', 'Provider verification contract', 'dist/auth/contracts/AuthProviderDriver.d.ts'], ['password', 'Password hashing helpers', 'dist/auth/passwordHash.d.ts'], ['google', 'Google provider', 'dist/auth/providers/GoogleAuthProvider.d.ts'], ['password-provider', 'Password provider', 'dist/auth/providers/PasswordAuthProvider.d.ts']] });
