/**
 * Copyable Hello guide fragments shared by documentation and packed-consumer tests.
 *
 * These fragments run in a generated application's directory and service types.
 */
export const helloGuideSamples = {
	"helloTestExplicit": "import { helloDefinition } from '../apps/helloDefinition';\n\n// Replace the existing host construction inside the test:\nconst host = new App({ directory: new URL('../', import.meta.url), db: database.db, apps: { hello: helloDefinition } });",
	"helloTest": "import 'dotenv/config';\nimport { expect, it } from 'vitest';\nimport Fastify from 'fastify';\nimport HelloApp from '../apps/hello/App';\nimport { App } from '@db3.ai/app/server';\nimport { AppRouteError } from '@db3.ai/app/apps';\nimport { registerAppRoutes } from '@db3.ai/app/apps/fastify';\nimport { createGeneratedTestDatabase } from '@db3.ai/app/db/test/db';\n\ndelete process.env.DATABASE_URL;\nprocess.env.DB_CONNECTION = 'mariadb';\nprocess.env.DB_HOST = process.env.TEST_DB_HOST || '127.0.0.1';\nprocess.env.DB_PORT = process.env.TEST_DB_PORT || '3306';\nprocess.env.DB_USER = process.env.TEST_DB_USER || 'root';\nprocess.env.DB_PASSWORD = process.env.TEST_DB_PASSWORD || '';\nprocess.env.DB_DATABASE = 'db3_app_test';\nprocess.env.DB_TEST_DATABASE_PREFIX = 'db3_app_test';\n\n/** Tests the actual local feature with disposable storage and real HTTP routing. */\nit('serves Hello only when authenticated and enabled', async () => {\n\tconst database = await createGeneratedTestDatabase('hello');\n\tconst host = new App({ directory: new URL('../', import.meta.url), db: database.db });\n\tconst server = Fastify();\n\tregisterAppRoutes(server, host.apps, async request => {\n\t\tif (request.headers.authorization !== 'test-user') throw new AppRouteError(401, 'Please sign in.');\n\t\treturn { id: 'reader' };\n\t});\n\ttry {\n\t\tawait host.apps.install('hello');\n\t\tawait host.apps.boot();\n\t\texpect((await server.inject('/api/apps/hello')).statusCode).toBe(401);\n\t\tconst response = await server.inject({ url: '/api/apps/hello', headers: { authorization: 'test-user' } });\n\t\texpect(response.statusCode).toBe(200);\n\t\texpect(response.json()).toEqual({ message: 'Hello, reader!' });\n\t\tconst original = host.apps.get('hello') as HelloApp;\n\t\tawait host.apps.manage('disable', 'hello');\n\t\texpect((await server.inject('/api/apps/hello')).statusCode).toBe(404);\n\t\texpect(() => original.greet('reader')).toThrow('Hello is not running.');\n\t\tawait host.apps.manage('enable', 'hello');\n\t\tconst restarted = host.apps.get('hello') as HelloApp;\n\t\texpect(restarted).not.toBe(original);\n\t\texpect(restarted.greet('reader')).toEqual({ message: 'Hello, reader!' });\n\t} finally {\n\t\ttry { await server.close(); } finally {\n\t\t\ttry { await host.close(); } finally { await database.destroy(); }\n\t\t}\n\t}\n});\n",
	"helloUse": "import { app } from '@db3.ai/app/server';\nimport { AppRouteError } from '@db3.ai/app/apps';\n\n/** Greets an identity already authenticated by the caller. */\nexport async function greetWithHello(userId: string) {\n\tconst host = app();\n\treturn host.apps.run(async () => {\n\t\tconst hello = host.hello;\n\t\tif (!hello) throw new AppRouteError(404, 'Hello is unavailable.');\n\t\treturn hello.greet(userId);\n\t});\n}"
} as const;
