import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { discoverApps } from './discoverApps';

/** Regenerates optional app().social types from discovery during development and builds, without loading server code. */
export async function writeAppTypes(directory: string): Promise<void> {
	const target = join(directory, '.db3/apps.d.ts');
	const properties = discoverApps(directory).map(app => {
		const specifier = app.packageName ?? `./${relative(dirname(target), app.entry).replaceAll('\\', '/').replace(/\.ts$/, '.js')}`;
		return `\t\treadonly ${app.manifest.id}?: InstanceType<typeof import(${JSON.stringify(specifier)}).default>;`;
	});
	await mkdir(dirname(target), { recursive: true });
	await writeFile(target, `// Generated by DB3 app discovery. Do not edit.\nimport '@db3.ai/app/apps/contracts';\ndeclare module '@db3.ai/app/apps/contracts' {\n\tinterface InstalledApps {\n${properties.join('\n')}\n\t}\n}\n`);
}
