import { agentCitationOccurrenceKey, normalizedAgentCitations, type AgentCitation } from '@db3.ai/pure';

/**
 * Extracts a normalized URL citation from a Responses streaming annotation.
 *
 * @param record - Raw `response.output_text.annotation.added` event.
 * @returns Valid URL citation, or null for unsupported annotations.
 */
export function agentCitationFromStreamRecord(record: Record<string, unknown>): AgentCitation | null {
	if (record.type !== 'response.output_text.annotation.added') return null;

	const annotation = recordValue(record.annotation);
	const itemId = stringValue(record.item_id) || stringValue(record.itemId);
	const annotationIndex = integerValue(record.annotation_index) ?? integerValue(record.annotationIndex);
	const contentIndex = integerValue(record.content_index) ?? integerValue(record.contentIndex) ?? 0;

	return providerUrlCitation(annotation, {
		id: citationId(itemId, contentIndex, annotationIndex),
		offset: contentIndex === 0 ? 0 : null,
	});
}

/**
 * Extracts URL citations from the final Agents SDK model response.
 *
 * A null result means the provider did not expose an authoritative annotation
 * collection, so callers may fall back to citations observed in stream events.
 * An empty array is authoritative and means the final response had no citations.
 *
 * @param rawResponses - Agents SDK model responses generated by the run.
 * @returns Final normalized citations, or null when annotations are unavailable.
 */
export function agentCitationsFromFinalModelResponse(rawResponses: unknown): AgentCitation[] | null {
	if (!Array.isArray(rawResponses) || rawResponses.length === 0) return null;

	const response = recordValue(rawResponses.at(-1));
	const output = Array.isArray(response?.output) ? response.output : null;

	if (!output || output.length === 0) return null;

	const message = recordValue(output.at(-1));

	if (!message) return null;

	const content = message.type === 'message' && Array.isArray(message.content)
		? message.content
		: null;

	if (!content) return null;

	const messageId = stringValue(message.id);
	const citations: AgentCitation[] = [];
	let textOffset = 0;
	let hasAnnotationCollection = false;

	for (let contentIndex = 0; contentIndex < content.length; contentIndex += 1) {
		const part = recordValue(content[contentIndex]);

		if (part?.type !== 'output_text') continue;

		const providerData = recordValue(part.providerData);
		const annotations = Array.isArray(providerData?.annotations)
			? providerData.annotations
			: Array.isArray(part.annotations)
				? part.annotations
				: null;

		if (annotations) {
			hasAnnotationCollection = true;

			for (let annotationIndex = 0; annotationIndex < annotations.length; annotationIndex += 1) {
				const citation = providerUrlCitation(recordValue(annotations[annotationIndex]), {
					id: citationId(messageId, contentIndex, annotationIndex),
					offset: textOffset,
				});

				if (citation) citations.push(citation);
			}
		}

		textOffset += stringValue(part.text)?.length ?? 0;
	}

	return hasAnnotationCollection ? normalizedAgentCitations(citations) : null;
}

/**
 * Adds a citation to an in-memory collection when its occurrence is new.
 *
 * @param citations - Mutable citations collected for the current attempt.
 * @param citation - Citation occurrence to remember.
 * @returns True when the citation was added.
 */
export function rememberAgentCitation(citations: AgentCitation[], citation: AgentCitation): boolean {
	const key = agentCitationOccurrenceKey(citation);

	if (citations.some(existing => agentCitationOccurrenceKey(existing) === key)) return false;

	citations.push(citation);

	return true;
}

/**
 * Context needed to normalize a provider URL annotation.
 */
interface ProviderCitationContext {
	/** Stable id assigned to this annotation occurrence. */
	id: string;

	/** Character offset of the containing output-text part. */
	offset: number | null;
}

/**
 * Converts a provider URL annotation into application's public citation contract.
 *
 * @param annotation - Raw provider annotation object.
 * @param context - Stable id and complete-message character offset.
 * @returns Valid normalized citation, or null when required data is absent.
 */
function providerUrlCitation(annotation: Record<string, unknown> | null, context: ProviderCitationContext): AgentCitation | null {
	if (!annotation || annotation.type !== 'url_citation' || context.offset === null) return null;

	const startIndex = integerValue(annotation.start_index) ?? integerValue(annotation.startIndex);
	const endIndex = integerValue(annotation.end_index) ?? integerValue(annotation.endIndex);
	const title = stringValue(annotation.title)?.trim();
	const url = stringValue(annotation.url)?.trim();

	if (startIndex === null || endIndex === null || !title || !url) return null;

	const citations = normalizedAgentCitations([{
		id: context.id,
		type: 'url',
		title,
		url,
		startIndex: context.offset + startIndex,
		endIndex: context.offset + endIndex,
	}]);

	return citations[0] ?? null;
}

/**
 * Builds a stable id for one provider citation occurrence.
 *
 * @param itemId - Provider output message id when available.
 * @param contentIndex - Output-text part index within the message.
 * @param annotationIndex - Annotation index within the output-text part.
 * @returns Stable citation id for streaming and restored UI state.
 */
function citationId(itemId: string | null, contentIndex: number, annotationIndex: number | null): string {
	return `${itemId || 'output'}:${contentIndex}:${annotationIndex ?? 0}`;
}

/**
 * Narrows an unknown JSON value to a non-array record.
 *
 * @param value - Unknown provider value.
 * @returns Object record, or null for primitives and arrays.
 */
function recordValue(value: unknown): Record<string, unknown> | null {
	return value && typeof value === 'object' && !Array.isArray(value)
		? value as Record<string, unknown>
		: null;
}

/**
 * Reads a non-empty string from an unknown provider value.
 *
 * @param value - Unknown provider value.
 * @returns String value, or null when absent.
 */
function stringValue(value: unknown): string | null {
	return typeof value === 'string' && value ? value : null;
}

/**
 * Reads a non-negative integer from an unknown provider value.
 *
 * @param value - Unknown provider index value.
 * @returns Non-negative integer, or null when invalid.
 */
function integerValue(value: unknown): number | null {
	return typeof value === 'number' && Number.isInteger(value) && value >= 0 ? value : null;
}
