import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';

const testPath = 'packages/app/src/ai/tests/Ai.integration.test.ts';
const sourcePath = 'packages/app/src/ai/README.md';
const examples = serviceExampleSources as Readonly<Record<string, string>>;

/** Gives each AI guide the same public import and verified service provenance. */
function guide(article: Omit<DocArticle, 'area' | 'group' | 'packageName' | 'sourcePath' | 'testPath'>): DocArticle {
	return { area: 'ai', group: 'Build with AI', packageName: '@db3.ai/app/ai', sourcePath, testPath, ...article };
}

export const aiArticle = guide({
	id: 'ai', label: 'Introduction', title: 'Build AI features in your app',
	summary: 'Give your app agents that call functions, remember conversations, generate images and track their work.',
	examplePaths: ['apps/starter/server/ai/summariseNote.ts'],
	sections: [
		{ id: 'start', title: 'Start in your app', paragraphs: ['These guides assume you have created a db3 app and are working in its directory. Your app already has a server, authentication, database migrations and an `Ai` service. Add an agent class when a feature needs to use your application’s functions or remember a conversation.', 'Use `app().ai` for text, structured data, image generation and embeddings. Use `Agent` for tool calls, live events and background runs. Both save requests and usage through the framework’s ActiveRecord models.'], links: [{ label: 'Create your app', articleId: 'starter-app' }, { label: 'Write your first agent', articleId: 'ai-agents' }] },
		{ id: 'setup', title: 'Configure AI', paragraphs: ['Set `OPENAI_API_KEY` and `OPENAI_MODEL` in your server `.env`, run the app’s migrations and restart the server. Keep provider credentials on the server. The generated Notes app works without a key; only its AI feature is disabled.', 'The generated app passes this configuration to `new App({ ai: config.ai })`. The public service is named `Ai`; provider selection and connection details belong in configuration.'], codeSampleId: 'setup', links: [{ label: 'OpenAI authentication guidance', href: 'https://developers.openai.com/api/reference/overview#authentication' }, { label: 'OpenAI data controls', href: 'https://developers.openai.com/api/docs/guides/your-data' }] },
		{ id: 'text', title: 'Generate text', paragraphs: ['Inside your route or job, call `app().ai.generateText(...)` for a string. Use `generateTextWithResponse(...)` when you also need the saved request and conversation IDs. Authorize the source record before sending it to a provider.', 'The starter’s summary function loads a note by both ID and owner, then generates a summary without replacing the original.'], codeSampleId: 'summary' },
		{ id: 'next', title: 'Build the next feature', paragraphs: ['An agent combines your instructions with explicit functions. Its conversation, messages, tool progress, provider attempts and usage remain in your app’s database. You can render that history, inspect a failure or extend the records with your own fields.'], links: [{ label: 'Agents and function calls', articleId: 'ai-agents' }, { label: 'Conversations and models', articleId: 'ai-conversations' }, { label: 'Generate and save images', articleId: 'ai-images' }, { label: 'Embeddings and structured data', articleId: 'ai-embeddings' }, { label: 'Usage and tracking', articleId: 'ai-usage' }, { label: 'Providers and failover', articleId: 'ai-providers' }] },
	],
	codeSamples: [
		{ id: 'setup', title: 'From your app directory', language: 'bash', code: '# Set OPENAI_API_KEY and OPENAI_MODEL in .env\nnpm run db:migrate\nnpm run dev' },
		{ id: 'summary', title: 'server/ai/summariseNote.ts', language: 'typescript', code: serviceExampleSources.starterSummariseNote },
	], relatedIds: ['ai-agents', 'starter-app', 'ai-api'],
});

const agents = guide({
	id: 'ai-agents', label: 'Agents and tools', title: 'Agents and function calls',
	summary: 'Create an agent class, give it application functions and run it from a route or job.',
	examplePaths: ['packages/app/src/ai/examples/HelpAgent.ts'],
	sections: [
		{ id: 'create', title: 'Create an agent', paragraphs: ['Create `server/agents/HelpAgent.ts`. An agent describes its task in `instructions()` and exposes functions from `tools()`. This example reads a help guide through your app’s Storage service.', 'Install `zod` in your app for tool argument schemas. The framework validates the model’s arguments before invoking your function. The route selects the guide path, user and scope; the model cannot choose another user’s file.'], codeSampleId: 'agent' },
		{ id: 'run', title: 'Run your agent', paragraphs: ['Write a guide to your configured disk, then call the agent from trusted server code. `run()` resolves with the final output and saved IDs, or throws when the run fails. `user` and `scope` are application identifiers; choose them from your authenticated request and permission checks.'], codeSampleId: 'run' },
		{ id: 'stream', title: 'Stream events to your UI', paragraphs: ['Use `stream(message, emit)` to forward typed events to your HTTP transport. Events include `text.delta`, `tool.calling`, `tool.progress`, `tool.success`, `tool.error`, `run.completed` and `run.error`.', '`stream()` reports a failure through `run.error` and returns null. Your renderer can display tool progress alongside text and later restore the same timeline from saved messages. Keep prompt/debug events behind an authorized diagnostic view.'], codeSampleId: 'stream', links: [{ label: 'Restore a conversation', articleId: 'ai-conversations' }] },
		{ id: 'queue', title: 'Run an agent in the background', paragraphs: ['Register `AgentRunJob` and each concrete agent during app boot, in both your web and worker processes. Add `QueuedJob` and `FailedJob` to your migration registry if you have not already configured the database queue.', '`queue()` saves the conversation and prepared run before dispatching. The worker reconstructs your agent from its serialized constructor context. Keep context serializable; registered ActiveRecord references can be restored by the framework serializer. Use stable class names for persisted jobs.'], codeSampleId: 'queue', links: [{ label: 'Start a queue worker', articleId: 'queue-overview' }] },
		{ id: 'tools', title: 'Use other AI features in a tool', paragraphs: ['Call `this.generateImage(...)`, `this.generateEmbedding(...)` or `this.generateStructured(...)` from an agent tool. Calls made during the run inherit its conversation and parent request, so the full operation appears in one request tree. Direct `app().ai` calls inside a tool inherit the same context.', 'Use the exported SDK tool helpers for supported provider tools such as web search. Tool availability depends on the selected provider and model. Your functions still own authorization, input limits and any application side effects.'] },
	], codeSamples: [
		{ id: 'agent', title: 'server/agents/HelpAgent.ts', language: 'typescript', code: examples.helpAgent ?? '' },
		{ id: 'run', title: 'Inside your route or job', language: 'typescript', code: "import { app } from '@db3.ai/app/server';\nimport { HelpAgent } from './agents/HelpAgent';\n\nawait app().storage.put('help.md', 'Change your password on the settings page.');\nconst result = await new HelpAgent({ user: userId, scope: teamId, guidePath: 'help.md' }).run('How do I change my password?');\nconsole.log(result.finalOutput, result.conversationId);" },
		{ id: 'stream', title: 'Forward events through your transport', language: 'typescript', code: "await new HelpAgent({ user: userId, scope: teamId, guidePath: 'help.md' }).stream(message, async event => {\n\tawait sendEvent(event);\n});" },
		{ id: 'queue', title: 'Register at boot, dispatch from your feature', language: 'typescript', code: "import { AgentRunJob, registerQueuedAgent } from '@db3.ai/app/ai';\n\napplication.queue.registerJob(AgentRunJob);\nregisterQueuedAgent('HelpAgent', HelpAgent);\n\nconst run = await new HelpAgent({ user: userId, scope: teamId, guidePath: 'help.md' }).queue('Explain password settings.', { queue: 'help' });\nconsole.log(run.jobId, run.conversationId);" },
	], relatedIds: ['ai-conversations', 'ai-usage', 'queue-overview', 'ai-api'],
});

const conversations = guide({
	id: 'ai-conversations', label: 'Conversations and models', title: 'Remember conversations in your app',
	summary: 'Resume a conversation, render its history and extend the framework’s ActiveRecord models.',
	examplePaths: ['packages/app/src/ai/examples/Conversation.ts'],
	sections: [
		{ id: 'resume', title: 'Continue a conversation', paragraphs: ['Pass the previous `conversationId` to the same agent with the same authenticated user and scope. The agent loads saved history before the next model turn and rejects a conversation belonging to a different user, scope or agent.', 'Treat conversation IDs as references, not permission. Apply the same ownership checks to your history and request-inspection routes. Direct text generation can append tracking rows to a conversation, but does not automatically replay its history; use an agent for that.'], codeSampleId: 'resume' },
		{ id: 'records', title: 'Work with the saved models', paragraphs: ['`AiConversation` groups a conversation. `AiMessage` stores text, tool lifecycle events and provider reasoning summaries when enabled. `AiRequest` stores inputs, responses, status, timestamps, provider metadata, token counts and costs. Root and child requests preserve the relationship between an agent run and its provider work.', 'The generated app registers these models, plus `AiRateLimitBucket` and `AiRateLimitReservation`, in its migrations. Use ordinary ActiveRecord queries from your app. Raw prompts and tool results can contain private data: authorize access and choose a retention policy for your application.'] },
		{ id: 'render', title: 'Render saved history', paragraphs: ['After authorizing the conversation, load its messages in sequence order and its requests. `agentConversationTimeline()` returns the message, tool and reasoning-summary items used by the streaming UI contract. Pass your agent’s tool definitions to attach app-specific tool labels.', 'The formatter can include prompt-context items for debugging. Filter those out of ordinary user views. It formats records; it does not authorize access or provide a UI component.'], codeSampleId: 'history' },
		{ id: 'extend', title: 'Add your own fields', paragraphs: ['Create a model in your app that extends the framework model. This example adds a support topic while retaining the existing table and fields.', 'Replace `AiConversation` with your subclass in the app’s model registry, configure `ai.models.conversation`, generate a migration, review it and apply it. The service uses your configured constructor for its reads and writes. Register one class per table. If you change table names, also override the related link fields.'], codeSampleId: 'model' },
		{ id: 'configure', title: 'Use your model throughout AI', paragraphs: ['The same `models` option accepts request and message subclasses. The default `user` and `scope` fields store app identifiers; subclasses may replace them with typed links to your app’s models.'], codeSampleId: 'configure' },
	], codeSamples: [
		{ id: 'resume', title: 'Resume from trusted route context', language: 'typescript', code: "const result = await new HelpAgent({\n\tuser: userId, scope: teamId, conversationId, guidePath: 'help.md',\n}).run('Which page should I open?');" },
		{ id: 'history', title: 'After authorizing the conversation', language: 'typescript', code: "import { AiMessage, AiRequest, agentConversationTimeline } from '@db3.ai/app/ai';\n\nconst messages = await AiMessage.where({ conversation: conversationId }).orderBy('sequence').all();\nconst requests = await AiRequest.where({ conversation: conversationId }).all();\nconst timeline = agentConversationTimeline(messages, [], requests);" },
		{ id: 'model', title: 'server/models/Conversation.ts', language: 'typescript', code: examples.aiConversation ?? '' },
		{ id: 'configure', title: 'In your existing App options', language: 'typescript', code: 'ai: {\n\t...config.ai,\n\tmodels: { conversation: Conversation },\n},' },
	], relatedIds: ['ai-agents', 'active-record', 'ai-usage'],
});

const images = guide({
	id: 'ai-images', label: 'Images', title: 'Generate and save images',
	summary: 'Create an image, save its bytes through Storage and keep the result attached to its AI request.',
	examplePaths: ['packages/app/src/ai/examples/createHelpImage.ts'],
	sections: [
		{ id: 'generate', title: 'Generate an image for your app', paragraphs: ['Use `app().ai.generateImage()` for an image operation, or `this.generateImage()` inside an agent tool. Supply a prompt and optional model, size, quality and output format. The current image adapter uses the OpenAI Images API.', 'Provide a `store` callback to save the returned bytes through your configured Storage disk or Media workflow. Its return value becomes `result.stored` and the saved request’s response reference.'], codeSampleId: 'image' },
		{ id: 'tracking', title: 'Keep files and tracking together', paragraphs: ['The result includes `b64Json`, `model`, `aiRequestId` and your storage reference. Raw image bytes are omitted from the persisted provider summary. Choose the output path in trusted app code and authorize any later download.', 'A storage failure fails the operation even if the provider already generated the image. Inspect the saved request before repeating a costly generation. Image and embedding calls currently use one provider; automatic provider failover is available for text and agent runs.'], links: [{ label: 'Storage disks', articleId: 'storage' }, { label: 'Media ownership and serving', articleId: 'media' }, { label: 'Usage records', articleId: 'ai-usage' }] },
	], codeSamples: [{ id: 'image', title: 'server/ai/createHelpImage.ts', language: 'typescript', code: examples.createHelpImage ?? '' }], relatedIds: ['ai-agents', 'storage', 'media'],
});

const embeddings = guide({
	id: 'ai-embeddings', label: 'Embeddings and structured data', title: 'Turn application content into data',
	summary: 'Generate embedding vectors and validate structured output against your app’s schema.',
	sections: [
		{ id: 'embed', title: 'Generate an embedding', paragraphs: ['Load and authorize the source content in your app, then call `generateEmbedding(text)`. The result contains a vector, its model and the tracked request ID. The default model is `text-embedding-3-small`.', 'Store the vector with its model and source revision in your application’s search index. Embed queries with the same model and keep tenant filters on retrieval. This API generates vectors; your app chooses the index, similarity search and retrieval policy.'], codeSampleId: 'embedding' },
		{ id: 'structured', title: 'Generate schema-validated output', paragraphs: ['Use `generateStructured()` when your feature needs data instead of prose. Supply a Zod schema and a stable schema name. The service sends the JSON schema to the provider, parses its output and validates it before returning `data`.', 'The result also includes text and tracking IDs. A schema validates structure, not factual accuracy; check domain constraints before saving or acting on generated values. Agent subclasses can also override `outputType()` for structured final output.'], codeSampleId: 'structured' },
	], codeSamples: [
		{ id: 'embedding', title: 'Inside your server feature', language: 'typescript', code: "const result = await app().ai.generateEmbedding(note.body);\nconsole.log(result.vector, result.model, result.aiRequestId);" },
		{ id: 'structured', title: 'Extract a typed title', language: 'typescript', code: "import { z } from 'zod';\n\nconst result = await app().ai.generateStructured({\n\tinstructions: 'Extract a short title from the supplied note.',\n\tinput: note.body,\n\tschemaName: 'note',\n\tschema: z.object({ title: z.string() }),\n});\nconsole.log(result.data.title);" },
	], relatedIds: ['ai-agents', 'ai-usage', 'ai-api'],
});

const usage = guide({
	id: 'ai-usage', label: 'Usage and tracking', title: 'Inspect AI requests and usage',
	summary: 'Track provider work, inspect failures and account for every request in an agent run.',
	sections: [
		{ id: 'requests', title: 'Inspect a saved request', paragraphs: ['AI calls save requests by default. Use the returned `aiRequestId` to query `AiRequest` through ActiveRecord. Request records include status, input, response, error information, duration and provider-reported token usage.', 'Agent runs save a root request and a child for each provider attempt. Provider calls made by tools are linked below the active attempt. This lets you inspect what happened without losing failed attempts or counting aggregate usage twice.'], codeSampleId: 'request' },
		{ id: 'cost', title: 'Account for the complete run', paragraphs: ['`AiRequest.runCostSummary(id)` walks the request tree and returns token totals, provider request count, known cost and the number of unpriced requests. Provider-reported costs take precedence where supported; otherwise the framework uses its model pricing table.', 'Missing usage or unknown pricing must not be treated as free work. `totalCostUSD` is a known subtotal when `unpricedRequestCount` is nonzero. Keep price tables current and reconcile commercial billing with your provider’s records.'], codeSampleId: 'cost' },
		{ id: 'allowance', title: 'Apply your application’s allowance policy', paragraphs: ['Configure `ai.allowance` to check user or workspace budget before provider work. The callback receives the provider, operation, model, scope and pending request where available. Throw `AIAllowanceExceededError` to reject the operation.', 'Provider rate limits and customer credits answer different questions. The framework tracks work and exposes policy hooks; your app defines subscriptions, prices, credit buckets and an idempotent ledger. Agent subclasses can override `usageCharge()` and `settleUsage()` for that policy. Nested operations should be attributed to their parent run instead of creating another root charge.'] },
		{ id: 'testing', title: 'Test without live provider calls', paragraphs: ['Inject `fetch` through your App’s AI options with a synthetic key. Keep the real Agent runtime, SDK, database and Storage in the test; replace only the external provider response. Use a disposable database and run the same app migrations used at boot.', 'The framework integration tests exercise function calls, history reload, ownership rejection, queued reconstruction, nested request parentage, text failover, structured output, image storage and embeddings. The generated app tests its Notes route with simulated AI responses. These tests establish the app contract, not the quality or availability of a live model.'], links: [{ label: 'Test your generated app', articleId: 'starter-app', sectionId: 'testing' }] },
	], codeSamples: [
		{ id: 'request', title: 'Inside an authorized diagnostic route', language: 'typescript', code: "import { AiRequest } from '@db3.ai/app/ai';\n\nconst request = await AiRequest.findByPk(aiRequestId);\nconsole.log(request?.status, request?.inputTokens, request?.outputTokens);" },
		{ id: 'cost', title: 'Inspect a complete agent run', language: 'typescript', code: 'const usage = await AiRequest.runCostSummary(aiRequestId);\nconsole.log(usage?.providerRequestCount, usage?.totalTokens);\nconsole.log(usage?.totalCostUSD, usage?.unpricedRequestCount);' },
	], relatedIds: ['ai-conversations', 'ai-providers', 'ai-api'],
});

const providers = guide({
	id: 'ai-providers', label: 'Providers and failover', title: 'Configure providers and failover',
	summary: 'Keep provider selection outside your feature code and recover from temporary provider failures.',
	sections: [
		{ id: 'config', title: 'Select providers in app configuration', paragraphs: ['The default provider is OpenAI. The current adapter supports OpenAI-compatible connections, with registered settings for OpenAI, OpenRouter, Groq, xAI and DeepSeek. Set the corresponding server environment variables for the providers you select.', 'Use `ai.provider` for an ordered failover chain. A record pins a model per provider; an array uses their configured defaults. Text and structured generation require a Responses-compatible provider. Agent runs can also use supported Chat Completions providers.'], codeSampleId: 'providers' },
		{ id: 'failover', title: 'Understand when failover runs', paragraphs: ['Text calls move to the next configured provider for transient network failures, timeouts, overload, rate limits, quota exhaustion and server errors. Authentication and invalid-request errors remain terminal. Unconfigured or disabled providers are skipped.', 'Agents fail over only before the SDK has emitted an event for the attempt. Once streaming has started, the framework does not replay the run on another provider because a tool may already have changed your app. Persisted attempts show which provider failed and which one completed the work.'] },
		{ id: 'limits', title: 'Share provider capacity across workers', paragraphs: ['`AIRateLimiter` stores rate-limit buckets and reservations in your database. It learns capacity from provider headers and defers calls when capacity is unavailable. Register its two models in your migrations; the generated app includes them.', 'Queue retries and quota deferrals use the framework queue contracts. Run workers for the queue you dispatch to, and monitor failed jobs alongside AI requests. The default per-request timeout is 60 seconds and SDK automatic retries are disabled; failover and queue policy remain explicit.'], links: [{ label: 'Queue workers and retries', articleId: 'queue-overview' }] },
		{ id: 'adapters', title: 'Keep application code provider independent', paragraphs: ['Your app calls `Ai` and extends `Agent`. Provider configuration, transport and cost handling live below those APIs. An OpenAI-compatible endpoint can use the existing connection options; a protocol that differs from these adapters needs a framework driver implementation.', 'Images and embeddings currently use the OpenAI adapter without cross-provider failover. Studio and Cloud are separate product work; these APIs do not require a hosted db3 account.'] },
	], codeSamples: [{ id: 'providers', title: 'Inside your App AI configuration', language: 'typescript', code: "ai: {\n\t...config.ai,\n\tprovider: {\n\t\topenai: process.env.OPENAI_MODEL!,\n\t\topenrouter: process.env.OPENROUTER_MODEL!,\n\t},\n},\n// Set OPENAI_API_KEY and OPENROUTER_API_KEY on the server." }], relatedIds: ['ai-usage', 'ai-agents', 'ai-api'],
});

export const aiArticles = [aiArticle, agents, conversations, images, embeddings, usage, providers];
export const aiApiArticle = createApiReference({ id: 'ai-api', label: 'AI API', packageName: '@db3.ai/app/ai', sourcePath, guideId: 'ai', references: [['service', 'AI service', 'dist/ai/Ai.d.ts'], ['agent', 'Agent runtime', 'dist/ai/Agent.d.ts'], ['options', 'Requests, results and configuration', 'dist/ai/contracts/AI.d.ts'], ['events', 'Agent events and tools', 'dist/ai/contracts/Agent.d.ts'], ['conversation', 'Conversation model', 'dist/ai/AiConversation.d.ts'], ['message', 'Message model', 'dist/ai/AiMessage.d.ts'], ['request', 'Request model', 'dist/ai/AiRequest.d.ts']] });
