import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';
import { createApiReference } from './apiReference';

const backgroundEvidence = serviceLabEvidence('queue', 'runQueueReports', 'Persists a report job, closes the producer, restores it in a fresh worker, repairs failure and repeats without duplicate output.', 'Disposable SQL and local files; no Redis, external provider or HTTP server.');
export const backgroundArticle: DocArticle = {
	id: 'guide-background', area: 'guides', group: 'Application guides', label: 'Background work', title: 'Move a report out of the request', summary: 'Accept the work quickly, persist its identity and let a registered worker produce the result. Keep access and progress in the application.',
	packageName: '@db3.ai/app/queue', sourcePath: 'packages/app/src/queue/README.md', examplePaths: ['packages/app/src/queue/examples/WriteReportJob.ts', 'packages/app/src/queue/examples/runQueueReports.ts'], testPath: backgroundEvidence.testPath, verifiedExample: backgroundEvidence,
	sections: [
		{ id: 'setup', title: 'Set up the queue and storage', paragraphs: ['Use Installation’s independent app, tools and dedicated test SQL credentials. The lab creates `QueuedJob` and `FailedJob` tables plus a temporary storage root, then removes them. Production apps apply committed migrations and use storage shared by producer/worker processes.'], links: [{ label: 'Installation and SQL test account', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Full Queue setup', articleId: 'queue-overview' }] },
		{ id: 'copy', title: 'Copy the complete example', paragraphs: ['This recipe reuses the maintained SQL report lab rather than a second version of the same job. All Queue examples are shipped with the package.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect the wrong queue to be idle, the first missing-source attempt released, the last attempt failed, a linked replay and one report file containing `Report: Three notes ready`. The final queue is empty and the failed audit record remains.'], codeSampleId: 'run-lab' },
		{ id: 'job', title: 'Give the work a stable identity', paragraphs: ['The job constructor validates its durable data when dispatching and when restoring. Use a report revision identity, not a request object, database connection, access token or submitted filesystem path.', 'The handler reads source bytes and replaces a stable result. Running it twice produces one output. That is a property of this operation, not a claim that queues execute exactly once. Email, billing and remote API calls need their own idempotency keys and recovery design.'], codeSampleId: 'job-source' },
		{ id: 'request', title: 'Keep the request boundary small', paragraphs: ['A real request first authenticates, authorizes the report and validates its inputs. Save application-owned report status/ownership, then dispatch the job to the same named queue the worker consumes. Return an accepted response with the application report ID; a queue ID is operational metadata, not read permission.', 'If saving the report and dispatching must be atomic, use an application outbox or another explicit transactional handoff. A normal model transaction does not include file storage or every queue driver. This framework does not supply a general outbox API today.', 'The lab exercises producer-to-worker durability without an HTTP endpoint. The API guide supplies the request-validation and owner-scope pattern; an HTTP report-progress UI remains a follow-up.'], links: [{ label: 'Authenticated JSON API', articleId: 'guide-api' }, { label: 'Transactions and external effects', articleId: 'cookbook-transactions' }] },
		{ id: 'worker', title: 'Boot the worker with the same registrations', paragraphs: ['Register `WriteReportJob` in every worker boot and consume `reports`, not `default`. The producer is closed before a new worker App restores the saved job, so in-memory registration in the request is not mistaken for durability.', 'For a long-running worker, use `startWorker()` with process supervision and stop/drain before shutdown. A one-step call returning no job means none is ready on that queue now; it does not mean delayed work is complete.'], codeSampleId: 'runner-source' },
		{ id: 'recover', title: 'Repair the cause, then replay', paragraphs: ['The first run has missing source bytes. Queue records ordinary failure and retries according to its policy. The lab writes the missing source, calls `retryFailed()` and checks linkage to the retained failure record.', 'Keep result reads scoped to the application owner. Queue history, raw payloads and errors are privileged operations; do not expose them as an unauthenticated progress endpoint.'], links: [{ label: 'Provider backpressure and deadlines', articleId: 'cookbook-retries' }] },
		serviceLabTesting('queue', 'runQueueReports'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the immutable report ID and source contents. Keep wrong-queue, failure, linked replay, one-output and empty-queue assertions. Repeat with your production driver in release verification.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['Tested: real SQL handoff across App instances, registration, queue selection, failure/repair/replay, worker drain and repeatable file output. Explained: HTTP ownership, report status, outbox, shared storage and production worker supervision.'], links: [{ label: 'Queue API', articleId: 'queue-api' }, { label: 'Recurring reports', articleId: 'scheduler' }, { label: 'Multi-step graphs', articleId: 'flows' }] },
	], codeSamples: [...serviceLabSamples('queue', 'runQueueReports'), { id: 'job-source', title: 'examples/WriteReportJob.ts', language: 'typescript', code: serviceExampleSources.writeReportJob }, { id: 'runner-source', title: 'examples/runQueueReports.ts', language: 'typescript', code: serviceExampleSources.runQueueReports }], relatedIds: ['queue-overview', 'scheduler', 'flows', 'guide-api'],
};

const retryEvidence = serviceLabEvidence('queue', 'runBackpressure', 'Defers twice without consuming an attempt, completes after simulated readiness and terminates at an application deadline.', 'Real SQL queue; controlled readiness flag, no network or paid API.');
export const retriesArticle: DocArticle = {
	id: 'cookbook-retries', area: 'cookbook', group: 'Common problems', label: 'Provider backpressure', title: 'Retry later without using an attempt', summary: 'A busy provider is not always a broken job. Defer deliberately, but give the work a deadline so it cannot wait forever.',
	packageName: '@db3.ai/app/queue', sourcePath: 'packages/app/src/queue/README.md', examplePaths: ['packages/app/src/queue/examples/DeferredReportJob.ts', 'packages/app/src/queue/examples/runBackpressure.ts'], testPath: retryEvidence.testPath, verifiedExample: retryEvidence,
	sections: [
		{ id: 'setup', title: 'Set up', paragraphs: ['Use the framework/tools and disposable SQL configuration from Installation. The provider in this lab is a controlled readiness flag. The queue, claims, attempts and failure records are real. No HTTP request or provider key is needed.'], links: [{ label: 'SQL lab prerequisites', articleId: 'installation', sectionId: 'database-labs' }] },
		{ id: 'copy', title: 'Copy the job and runner', paragraphs: ['Keep the durable deadline in the job data so it survives process restart. The example has no irreversible provider side effect.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect two `deferred` outcomes, `attemptsAfterDeferral: 0`, then `succeeded`. An expired application deadline produces `failed`, with no queued work left and one retained failure.'], codeSampleId: 'run-lab' },
		{ id: 'policy', title: 'Distinguish deferral from failure', paragraphs: ['Throw `QueueRetryLaterError(delaySeconds)` only for deliberate backpressure. Queue releases the claim and restores the consumed attempt. An ordinary exception follows `maxTries`, backoff and `retryUntilSeconds` instead.', 'Intentional deferral bypasses ordinary retry exhaustion. Check an application deadline before deferring or the job can remain queued indefinitely. The example uses zero seconds only to prove the lifecycle without sleeps; a real provider needs a validated, bounded non-zero delay and usually jitter.'], codeSampleId: 'job-source' },
		{ id: 'provider', title: 'Translate provider responses carefully', paragraphs: ['Classify the actual response. Rate limits and a documented Retry-After can justify deferral; invalid credentials or malformed input generally need repair, not endless retries. Validate delay units and upper bounds before throwing.', 'A timeout may happen after the provider accepted work. Do not blindly repeat a charge, email or generation without an idempotency/reconciliation policy. This recipe does not parse Retry-After or certify a provider’s behavior.'] },
		{ id: 'recover', title: 'Prove recovery and expiry', paragraphs: ['The runner changes only the simulated external readiness, not a queued payload or attempt counter. The next real claim succeeds. A separately expired job proves the hard stop independently of readiness.'], codeSampleId: 'runner-source' },
		serviceLabTesting('queue', 'runBackpressure'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Add another deferral and keep the attempt count at zero. Keep a deterministic expired deadline rather than waiting for a timer. Test real delay scheduling separately with the production driver.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage', paragraphs: ['Tested: SQL claims/deferrals, preserved attempts, readiness recovery and an application deadline. Explained: ordinary retries, non-zero delay, idempotency and response classification. Follow-up: a provider-specific adapter recipe with Retry-After parsing.'], links: [{ label: 'Queue policy and lifecycle reference', articleId: 'queue-api' }, { label: 'Background report workflow', articleId: 'guide-background' }] },
	], codeSamples: [...serviceLabSamples('queue', 'runBackpressure'), { id: 'job-source', title: 'examples/DeferredReportJob.ts', language: 'typescript', code: serviceExampleSources.deferredReportJob }, { id: 'runner-source', title: 'examples/runBackpressure.ts', language: 'typescript', code: serviceExampleSources.runBackpressure }], relatedIds: ['queue-overview', 'guide-background', 'scheduler'],
};

export const schedulerApiArticle = createApiReference({ id: 'scheduler-api', label: 'Scheduler API', packageName: '@db3.ai/app/scheduler', sourcePath: 'packages/app/src/scheduler/README.md', guideId: 'scheduler', references: [['scheduler', 'Registration and due evaluation', 'dist/scheduler/Scheduler.d.ts'], ['event', 'Daily event configuration', 'dist/scheduler/ScheduledEvent.d.ts'], ['job', 'Scheduled job', 'dist/scheduler/ScheduledJob.d.ts'], ['call', 'Inline call', 'dist/scheduler/ScheduledCall.d.ts'], ['occurrence', 'Durable occurrence', 'dist/scheduler/ScheduledOccurrence.d.ts'], ['recorder', 'Queue lifecycle recorder', 'dist/scheduler/ScheduledOccurrenceRecorder.d.ts'], ['worker', 'Worker lifecycle', 'dist/scheduler/SchedulerWorker.d.ts'], ['contracts', 'Inputs and results', 'dist/scheduler/contracts/Scheduler.d.ts'], ['worker-options', 'Worker options', 'dist/scheduler/contracts/SchedulerWorker.d.ts'], ['checkpoint', 'Durable worker progress', 'dist/scheduler/contracts/SchedulerCheckpoint.d.ts'], ['console', 'Console adapter', 'dist/scheduler/console.d.ts'], ['console-options', 'Console options', 'dist/scheduler/contracts/SchedulerConsole.d.ts']] });
