import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('events', 'runNoteEvents', 'Runs exact-class event listeners in order, unsubscribes, rejects a failing listener and resumes after explicit removal.', 'Node.js 24. In-process Events; no database or queued/durable delivery claim.');

export const eventsArticle: DocArticle = {
	id: 'events', area: 'services', group: 'Application', label: 'Events', title: 'React to a saved note', summary: 'Use typed, in-process events for small reactions while keeping delivery and failure behavior visible.', packageName: '@db3.ai/app/events', sourcePath: 'packages/app/src/events/README.md', examplePaths: ['packages/app/src/events/examples/NoteSaved.ts', 'packages/app/src/events/examples/runNoteEvents.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Start with one event', paragraphs: ['Complete Installation and copy the example. It needs no database or worker. The trace represents reactions; it does not actually save or index a note.', 'In an app, register listeners during boot on `app().events`. Dispatch only once the operation the event describes has succeeded.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'run', title: 'Run, fail and repair a dispatch', paragraphs: ['Expect the trace `index:one`, `first:one`, `index:two`, `after:four`, with `rejected: true` and `hasListeners: false`.', 'The failed third dispatch never reaches the later listener. Removing the failing registration allows the fourth dispatch to complete. All remaining listeners are cleared in `finally`.'], codeSampleId: 'run-lab' },
		{ id: 'event', title: 'Use a class as the event identity', paragraphs: ['Name the event after something that happened and carry stable IDs. Event instances are not cloned. Readonly fields help communicate intent, but do not deeply freeze nested values.', 'The exact class constructor is the subscription key. A subclass is a different event type. Plain objects are rejected rather than sharing one ambiguous Object key.'], codeSampleId: 'event-source' },
		{ id: 'listeners', title: 'Subscribe and await delivery', paragraphs: ['`listen(EventClass, listener)` returns an idempotent unsubscribe function. `once()` removes its registration before invocation so overlapping dispatches cannot run that listener twice.', '`dispatch(new Event(...))` snapshots current listeners and awaits them sequentially in registration order. Removing a registration does not cancel a callback already captured by an in-progress dispatch.'], codeSampleId: 'events-source' },
		{ id: 'errors', title: 'Decide whether a reaction must succeed', paragraphs: ['The first thrown/rejected listener stops dispatch and propagates to the caller. Earlier listeners may already have changed state; there is no rollback of their effects.', 'Catch only when you intentionally make a reaction non-fatal. Do not replay a whole event blindly: earlier successful side effects might run twice. This lab repairs registration and dispatches a new event; it does not claim automatic retry or duplicate protection.'] },
		{ id: 'durability', title: 'Use Queue for durable work', paragraphs: ['Events are in memory, process-local and not persisted. They do not cross API, worker or scheduler processes, survive a crash or retry failed listeners.', 'A listener can enqueue a job, but a database commit followed by dispatch is not an atomic outbox. If losing the handoff matters, design that transaction/reconciliation explicitly.', 'Queue lifecycle observers are a different stream: their errors are isolated from already-completed queue transitions. Application Events intentionally propagates listener failures. Logs are observability, not a way to trigger product behavior.'], links: [{ label: 'Durable queued reports', articleId: 'queue-overview' }, { label: 'Structured logging', articleId: 'logging' }] },
		{ id: 'cleanup', title: 'Remove listeners at their owner boundary', paragraphs: ['Use the returned unsubscribe function for one registration, `forget(EventClass)` for one event type, and `clear()` for the whole dispatcher. Do not clear a shared app dispatcher after each request.', '`App.close()` clears its dispatcher. A standalone dispatcher owns no network resources, but you should still remove listeners when its owner finishes.'] },
		serviceLabTesting('events', 'runNoteEvents'),
		{ id: 'run-tests', title: 'Test ordering and failure', paragraphs: ['The copied tests use the real dispatcher and assert the complete trace, failure propagation, one-shot observation, exact-class matching, plain-object rejection and idempotent unsubscribe.', 'Add a second application listener and prove its position in the trace. If it creates durable work, test the Queue handoff separately.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught/tested: every Events method, async order, listener failure/recovery, exact-class identity and cleanup. App shutdown and overlapping one-shot dispatch also have existing service tests.', 'Cross-process delivery, replay, retries, cancellation and transaction coupling are not Events features. The reference contains the service and every public event contract.'], links: [{ label: 'Full Events API', articleId: 'events-api' }] },
	], codeSamples: [...serviceLabSamples('events', 'runNoteEvents'), { id: 'event-source', title: 'examples/NoteSaved.ts', language: 'typescript', code: sources.noteSavedEvent ?? '' }, { id: 'events-source', title: 'examples/runNoteEvents.ts', language: 'typescript', code: sources.runNoteEvents ?? '' }], relatedIds: ['events-api', 'app', 'queue-overview', 'logging'],
};

export const eventsApiArticle = createApiReference({ id: 'events-api', label: 'Events API', packageName: '@db3.ai/app/events', sourcePath: 'packages/app/src/events/README.md', guideId: 'events', references: [['events', 'Dispatcher', 'dist/events/Events.d.ts'], ['identity', 'Event identity', 'dist/events/contracts/EventConstructor.d.ts'], ['listener', 'Listener callback', 'dist/events/contracts/EventListener.d.ts'], ['unsubscribe', 'Unsubscribe function', 'dist/events/contracts/EventUnsubscribe.d.ts']] });
