import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';

const sources: Readonly<Record<string, string>> = serviceExampleSources;

/** Application-first guide to the implemented persistent inbox service. */
export const inAppArticle: DocArticle = {
	id: 'in-app', area: 'services', group: 'Delivery', label: 'In-app messages', title: 'In-app messages',
	summary: 'Send a persistent message to a user, read their inbox and manage read, dismissal and archive state.',
	packageName: '@db3.ai/app/in-app', sourcePath: 'packages/app/src/in-app/README.md',
	examplePaths: ['packages/app/src/in-app/examples/sendReportReady.ts'],
	testPath: 'packages/app/src/in-app/tests/InApp.test.ts',
	sections: [
		{ id: 'setup', title: 'Add inbox storage', paragraphs: ['Start with a locally running application and its existing Auth and database setup. Add `InAppRecord` to the model registry in `server/database/models.ts`, keeping the existing models. Generate, review and apply a migration through your application CLI.', '`app().inApp` is supplied by App and uses the configured Auth identity model. Accessing the service never creates production tables.'], codeSampleId: 'storage', links: [{ label: 'Create an application', articleId: 'starter-app' }, { label: 'Installation', articleId: 'installation' }] },
		{ id: 'send', title: 'Send a report-ready message', paragraphs: ['Create `server/messages/sendReportReady.ts` with this function. Call it from authorized application code with a real user ID and report ID. The function returns the durable item ID; it does not send email or contact a push provider.', 'Pass a user ID or an array of IDs to `send()`. `body` is the required plain-text fallback. `bodyHtml` can carry rich application-authored content, but every HTML renderer must sanitize it. A batch accepts at most 100 input IDs and creates independent state per distinct recipient. An invalid recipient rolls back the whole batch. An empty array creates nothing.'], codeSampleId: 'send-source' },
		{ id: 'run', title: 'Try it in your application REPL', paragraphs: ['Run `npm run repl` from the generated application after applying the migration. Replace the example user ID with a real user in your local database, then execute these expressions. No HTTP server or browser UI is needed.', '`runWithUser()` is appropriate for this trusted local REPL exercise and tests. HTTP routes must authenticate the actual session instead of accepting a user ID as proof of identity.'], codeSampleId: 'repl' },
		{ id: 'inbox', title: 'Read the authenticated inbox', paragraphs: ['In an authenticated request context, `inbox()` derives the reader from framework Auth. Do not pass a reader ID from the browser. The result contains `items`, `unreadCount` for the unarchived scoped inbox, and `nextBefore` for pagination.', 'Opening or fetching the inbox marks nothing read. Supply `before` only when `nextBefore` is non-null. Page size defaults to 25 and is capped at 100. Refresh the first page to find new arrivals; this pagination cursor is not a live-event replay cursor.'], codeSampleId: 'inbox' },
		{ id: 'presentation', title: 'Choose a toast, banner or quiet inbox item', paragraphs: ['`presentation: "toast"` records an intent to show a transient alert for a new live arrival. `"banner"` records an intent to keep a prominent message until dismissed. `"inbox"` is a quiet item. Every mode remains stored in the inbox.', 'Query with `view: "banners"` for undismissed, unarchived banners. Presentation metadata does not render UI by itself. Render title and fallback body with text-safe bindings. Sanitize `bodyHtml` against an application-owned allowlist before using an HTML rendering path, and avoid replaying stored items as new toasts on page load.'] },
		{ id: 'state', title: 'Keep read and dismissal separate', paragraphs: ['Use `update(id, transition, scope)` with `read`, `unread`, `dismiss` or `archive`. Dismissing removes a banner from active banner queries but keeps it in the inbox. Reading does not dismiss it. Archiving removes it from active inbox and banner queries.', 'Each recipient owns independent state. A foreign item ID produces the same not-found error as an unknown item.'], codeSampleId: 'state' },
		{ id: 'scope', title: 'Authorize organization inboxes', paragraphs: ['Account scopes use the authenticated user’s ownership. Other scopes require an `inApp.authorizeScope` policy on App and fail closed when one is absent. The policy receives the user ID, explicit scope and `receive`, `read` or `update` operation.', 'Check current membership and write restrictions in that policy. When configured, it also governs account scopes. Background producers check recipient eligibility without assuming an active login. Sender authorization remains application-owned; do not expose an unrestricted send endpoint.'], links: [{ label: 'Scope policy contract', articleId: 'in-app-api', sectionId: 'scope' }] },
		{ id: 'failures', title: 'Retry safely and handle failures', paragraphs: ['A `key` identifies one occurrence within recipient, scope and notification type. Sending the same normalized content again returns the existing ID. Different content with the same key raises `InAppError` with code `conflict`; it does not overwrite history. Omit the key to create a new occurrence.', 'The service participates in outer ActiveRecord transactions. An outer rollback removes its inbox writes. Retry the entire owning transaction on database deadlocks or stale-snapshot errors. Never treat an uncommitted acceptance as durable success.', 'Map `invalid`, `unauthenticated`, `forbidden`, `not_found` and `conflict` to suitable HTTP responses. Do not expose raw storage errors. Message actions allow root-relative or HTTP(S) URLs; destination routes still enforce their own permissions.'] },
		{ id: 'testing', title: 'Test your application', paragraphs: ['Use a disposable test database and the application’s real App/Auth configuration. Install or migrate the registered models, create two users, send to both, and use `auth.runWithUser()` to inspect each inbox. Assert read/dismissal independence, unauthorized access, duplicate keys and rollback. Run those tests with your application’s `npm test`.', 'Framework contributors can run the focused service suite from the repository root after configuring the ignored `packages/app/.env.test`. It executes the example above and tests real SQL; unavailable SQL fails the suite.'], codeSampleId: 'tests' },
		{ id: 'cleanup', title: 'Own retention and account deletion', paragraphs: ['The framework stores opaque recipient IDs so it can use your configured identity model. Add inbox cleanup to account-deletion and retention workflows. There is no automatic retention job or hard-coded foreign key to a specific user table.', 'The service owns no socket, timer or worker to close. Your application owns its normal App and database lifecycle; disposable test databases must be removed in test cleanup.'] },
		{ id: 'coverage', title: 'Current capability', paragraphs: ['This is the persistent server-side inbox service. It includes typed content, recipient state, scope authorization, deduplication and pagination.', 'The starter app includes an unread badge, paginated inbox and demo buttons for quiet messages, toasts and persistent banners. Apply its migrations, sign in and use the notification controls above the notebook. A private WebSocket channel invalidates the inbox after the demo HTTP send/update routes commit, and on reconnect. Each tab reloads authorized state over HTTP; historical toast messages are not replayed. This is application-owned channel wiring, not automatic InApp dispatch. Push, email coordination and notification-class dispatch are not connected to this demo.'], links: [{ label: 'In-app API reference', articleId: 'in-app-api' }, { label: 'Private WebSocket channels', articleId: 'websocket', sectionId: 'resource-channels' }, { label: 'Send email with Mail', articleId: 'mail' }] },
	],
	codeSamples: [
		{ id: 'storage', title: 'Register and migrate the model', language: 'typescript', code: "import { InAppRecord } from '@db3.ai/app/in-app';\n\n// Add InAppRecord to your existing models array in server/database/models.ts.\n// Then run from your application directory:\n// npm run db:make:migration -- add_in_app_messages\n// npm run db:migrate" },
		{ id: 'send-source', title: 'server/messages/sendReportReady.ts', language: 'typescript', code: sources.sendReportReady ?? '' },
		{ id: 'repl', title: 'Inside npm run repl', language: 'typescript', code: "const { app } = await import('@db3.ai/app/server');\nconst { UserIdentity } = await import('@db3.ai/app/auth');\nconst { sendReportReady } = await import('./server/messages/sendReportReady.ts');\nconst user = await UserIdentity.findOrFail('YOUR_LOCAL_USER_ID');\nconst scope = { type: 'account' };\nconst [receipt] = await sendReportReady(String(user.id), 'demo-report');\nawait app().auth.runWithUser(user, () => app().inApp.inbox({ scope }));\n// Repeat the same send: status is existing and the item ID is unchanged.\nawait sendReportReady(String(user.id), 'demo-report');\nawait app().auth.runWithUser(user, () => app().inApp.update(receipt.id, 'dismiss', scope));" },
		{ id: 'inbox', title: 'Inside an authenticated route', language: 'typescript', code: "const page = await app().inApp.inbox({ scope: { type: 'account' }, limit: 25 });\nconst banners = await app().inApp.inbox({ scope: { type: 'account' }, view: 'banners' });" },
		{ id: 'state', title: 'Explicit recipient actions', language: 'typescript', code: "const scope = { type: 'account' };\nawait app().inApp.update(itemId, 'read', scope);\nawait app().inApp.update(itemId, 'unread', scope);\nawait app().inApp.update(itemId, 'dismiss', scope);\nawait app().inApp.update(itemId, 'archive', scope);" },
		{ id: 'tests', title: 'From the framework repository root', language: 'sh', code: 'cp packages/app/.env.test.example packages/app/.env.test\n# Set local MariaDB/MySQL connection credentials in that ignored file.\nnpm run test:service --workspace @db3.ai/app -- in-app' },
	],
	relatedIds: ['in-app-api', 'auth', 'mail', 'starter-app'],
};

/** Public signatures generated from the staged package declarations. */
export const inAppApiArticle = createApiReference({
	id: 'in-app-api', label: 'In-app messages', packageName: '@db3.ai/app/in-app', sourcePath: 'packages/app/src/in-app/README.md', guideId: 'in-app',
	references: [
		['service', 'Service operations', 'dist/in-app/InApp.d.ts'],
		['message', 'Message content', 'dist/in-app/contracts/InAppMessage.d.ts'],
		['inbox', 'Inbox and acceptance results', 'dist/in-app/contracts/InAppInbox.d.ts'],
		['scope', 'Scope and authorization', 'dist/in-app/contracts/InAppScope.d.ts'],
		['errors', 'Errors', 'dist/in-app/InAppError.d.ts'],
	],
});
