import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const evidence = serviceLabEvidence('media', 'runProjectMedia', 'Streams a project file, places it in a folder, resolves duplicate names, scopes reads and verifies file/placement cleanup.', 'A dedicated MariaDB/MySQL test account and temporary local disk. No real uploads or provider requests.');

export const mediaArticle: DocArticle = {
	id: 'media', area: 'services', group: 'Files', label: 'Media', title: 'Media',
	summary: 'Give files durable IDs and project-scoped libraries. Keep storage paths, browser folders and permission checks separate.',
	packageName: '@db3.ai/app/media', sourcePath: 'packages/app/src/media/README.md', examplePaths: ['packages/app/src/media/examples/runProjectMedia.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Set up storage and media tables', paragraphs: ['Storage owns the bytes. Media owns `MediaLibrary`, `MediaFile` and `MediaItem` records. The application supplies a storage disk and a database containing those tables.', 'The lab uses temporary storage and installs the three models into a generated test database. An application must use committed migrations and a durable disk. A browser placement is a data record; the framework does not automatically install a Vue media browser.'], links: [{ label: 'Installation and test SQL configuration', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Configure Storage', articleId: 'storage' }] },
		{ id: 'copy', title: 'Copy the project-files example', paragraphs: ['Use the independent app directory and test configuration from Installation. The example uses two trusted project identities to demonstrate scoped reads.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['The result contains `/Briefs/brief.txt`, a numbered duplicate `/Briefs/brief-2.txt`, and true values for private visibility, cross-project rejection and deletion cleanup. The generated database and temporary files are removed afterwards.'], codeSampleId: 'run-lab' },
		{ id: 'libraries', title: 'Give a project its own library', paragraphs: ['`libraryFor()` finds or creates a library identified by `scopeType`, `scopeId` and `key`. Your app decides what a project is and verifies access before resolving that library.', 'A library can supply a default disk and path prefix. Treat scope values as trusted application inputs, not arbitrary values copied from a request body. Library identity is not an access-control check.'], codeSampleId: 'media-source' },
		{ id: 'store', title: 'Store a file or place it in a folder', paragraphs: ['`storeFile()` creates a managed file without a browser item. `storeVisibleFile()` also creates a placement and any missing folders. Use `storeFileStream()` or `storeVisibleFileStream()` for an assembled upload stream.', 'Browser paths can change while the file ULID remains stable. Duplicate placement names are numbered rather than replacing an existing file. `ensureFolder()` and `attachFile()` work with existing library/file records.', 'Do not supply a path or byte count from untrusted input without validating it. Ordinary stream storage does not inspect the file contents or implement a resumable upload protocol.'] },
		{ id: 'read', title: 'Read a file within its authorized library', paragraphs: ['Load the file with both its ID and authorized library, as the example does with `MediaFile.where({ id, library })`. Only then call `readFile()` or `readFileStream()`.', '`media.file(id)` is an unscoped lookup, not an authorization check. A guessed ULID must not let one project read another project’s files. Your route also owns MIME policy, response headers and download disposition.'] },
		{ id: 'images', title: 'Validate image uploads and render variants', paragraphs: ['For untrusted images, perform a cheap signature/type allowlist at the upload boundary, then use `storeReconstructedVisibleImageStream()`. The processor decodes and reconstructs the file, stripping metadata and trailing bytes before saving media records.', '`renderImage()` generates responsive variants through the image processor and disposable cache. `imageVariantOptionsFromSearchParams()` limits the request options; supported widths are 1–4096. Decoding is bounded by a 40-megapixel input limit and 20-second processing timeout.', 'Configure cache disk/prefix under `config.media.images`. Authorize the original file before rendering a variant. The project-text-file lab does not exercise reconstruction or image caching; the framework has separate processor and renderer tests.'] },
		{ id: 'visibility', title: 'Choose private or public delivery deliberately', paragraphs: ['Files default to private storage visibility. A browser-visible item is not a public file, and setting metadata to public does not install a public HTTP route.', 'Private delivery needs an authenticated, scoped route. Public delivery needs an explicit policy for what may be published. Media does not check whether a file is safe to display as HTML, whether an SVG contains active content, or whether your app is permitted to share its contents.'] },
		{ id: 'delete', title: 'Delete and recover', paragraphs: ['Before `deleteFile()`, check app-owned references and whether deletion is allowed. The manager removes generated variants and source bytes, then the managed row; foreign keys remove browser placements.', 'Database and object storage are not one transaction. Plan for partial failures and orphan reconciliation in an application that needs stronger guarantees. Reconstructed-image failures have their own partial-object cleanup, but that is not a claim of atomicity for every file operation.'] },
		serviceLabTesting('media', 'runProjectMedia'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Run with dedicated SQL credentials and local temporary storage. Try a different folder or a duplicate filename. Keep the cross-project read test: it proves the scoped lookup used by this example, not the application’s membership policy.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and reference', paragraphs: ['Tested here: scoped libraries, streamed storage, browser placement, duplicate names, scoped reads, private defaults and deletion cleanup. The private-file guide adds real HTTP authentication, input limits, headers and foreign-user rejection.', 'Still to build: browser integration, source-backed image-processing walkthroughs and orphan reconciliation. Image APIs also have the `@db3.ai/app/media/image` public subpath.'], links: [{ label: 'Full Media API', articleId: 'media-api' }, { label: 'Private upload and download', articleId: 'guide-files' }] },
	], codeSamples: [...serviceLabSamples('media', 'runProjectMedia'), { id: 'media-source', title: 'examples/runProjectMedia.ts', language: 'typescript', code: serviceExampleSources.runProjectMedia }], relatedIds: ['installation', 'storage', 'auth', 'queue-overview'],
};
