import type { DocArticle } from '../docs';
import { frameworkAuthority } from '../generated/framework-authority';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const serviceReferences = [
	['App', 'app', 'app-api'], ['Config', 'config', 'config-api'], ['Auth', 'auth', 'auth-api'], ['ActiveRecord', 'active-record', 'active-record-api'], ['Fields', 'fields', 'fields-api'], ['Migrations', 'migrations', 'migrations-api'], ['Validation', 'validation', 'validation-api'], ['Cache', 'cache', 'cache-api'], ['Events', 'events', 'events-api'], ['Logging', 'logging', 'logging-api'], ['Security', 'security', 'security-api'], ['Mail', 'mail', 'mail-api'], ['Storage', 'storage', 'storage-api'], ['Media', 'media', 'media-api'], ['Queue', 'queue-overview', 'queue-api'], ['Scheduler', 'scheduler', 'scheduler-api'], ['Flows', 'flows', 'flows-api'], ['Serialization', 'serialization', 'serialization-api'], ['URLs', 'url', 'url-api'], ['SSR', 'ssr', 'ssr-api'], ['AI text', 'ai', 'ai-api'],
] as const;

export const apiIndexArticle: DocArticle = {
	id: 'api-reference', area: 'services', group: 'Quality', label: 'API reference', title: 'Find a public contract', summary: 'Start with a working guide. Use the emitted TypeScript reference when you need an option, method or return type.',
	packageName: '@db3.ai/app', sourcePath: 'packages/app/README.md', includeSourceDocument: false,
	sections: [
		{ id: 'use', title: 'Guide first, signature when needed', paragraphs: ['Each service below links to its task-oriented guide and a focused declaration reference. The references are generated from the same compiled package shape consumers install, not manually transcribed interfaces.', 'A public import path is supported by the package export map. Relative imports inside a declaration describe its type dependencies; they do not grant arbitrary deep imports into private implementation files.'], links: [{ label: 'Install or create an app', articleId: 'installation' }, { label: 'Solve a concrete problem', articleId: 'solve-a-problem' }] },
		...serviceReferences.map(([label, guide, reference]) => ({ id: guide, title: label, paragraphs: [], links: [{ label: `${label} guide and examples`, articleId: guide }, { label: `${label} signatures and options`, articleId: reference }] })),
		{ id: 'packages', title: 'Package inventories', paragraphs: ['The package pages list the supported import entry points. Pure includes its complete emitted utility declarations. The source-backed Markdown pages expose the same content to AI tools, with linked examples and behavior tests.'], links: [{ label: '@db3.ai/app package', articleId: 'package-app' }, { label: '@db3.ai/pure package', articleId: 'package-pure' }] },
		{ id: 'coverage', title: 'What reference coverage means', paragraphs: ['Use the reference to look up methods, options and return types. Each service guide includes runnable examples and explains its limits. Match the documentation version to the package version installed in your app.'] },
	], relatedIds: ['package-app', 'package-pure', 'testing'],
};

export const packageAppArticle: DocArticle = {
	id: 'package-app', area: 'api', group: 'Packages', label: '@db3.ai/app', title: '@db3.ai/app', summary: 'The backend runtime: application services, field-aware records, durable work and optional web delivery.', packageName: '@db3.ai/app', sourcePath: 'packages/app/README.md', includeSourceDocument: false,
	sections: [
		{ id: 'install', title: 'Install the matching packages', paragraphs: ['App depends on the matching Pure version. Use the published package once available, or both maintainer-supplied tarballs for the current preview. Import the runtime from `@db3.ai/app` or its service subpaths.', 'The runtime manifest supports Node.js 20+, while these walkthroughs and the starter use Node.js 24+. The package is MIT licensed.'], links: [{ label: 'Installation commands and publication status', articleId: 'installation' }, { label: 'Create the app shell', articleId: 'starter-app' }] },
		{ id: 'imports', title: 'Supported imports', paragraphs: ['This exact inventory comes from the staged export map. Choose the service subpath for normal imports; do not depend on workspace-only source aliases.'], codeSampleId: 'imports' },
		{ id: 'ownership', title: 'What belongs in your app', paragraphs: ['The framework owns reusable service mechanics. Your app owns routes, models, organization membership, billing policy, provider permissions and business workflows. Configure one App at process boot and resolve services through it.', 'SSR is optional; install its HTTP/build peers only when using those adapters. Flows needs an explicit App extension and registered blocks. AI includes agents, tools, saved conversations, images, embeddings and provider failover. Applications supply credentials, authorization and commercial billing policy.'], links: [{ label: 'App and request lifecycle', articleId: 'app' }, { label: 'Every service reference', articleId: 'api-reference' }, { label: 'Current AI boundary', articleId: 'ai' }] },
		{ id: 'examples', title: 'Use the shipped examples', paragraphs: ['The tarball includes service-owned example source. Each guide supplies exact copy, run and test commands, plus an isolated cleanup path. Copy examples into your app before changing them; keep application code outside `node_modules`.'], links: [{ label: 'First HTTP app', articleId: 'create-app' }, { label: 'Private files', articleId: 'guide-files' }, { label: 'Durable report worker', articleId: 'guide-background' }] },
		{ id: 'testing', title: 'Verify the consumer boundary', paragraphs: ['Use your generated app’s `npm test`, type check and build, or the guide’s copied test. Framework maintainers additionally pack the package, install it into a fresh consumer and check runtime imports and TypeScript. Passing through a workspace alias alone does not prove the package works.'], links: [{ label: 'Testing', articleId: 'testing' }] },
	], codeSamples: [{ id: 'imports', title: 'Exported TypeScript entry points', language: 'text', code: frameworkAuthority.publicExports.map(entry => entry.importPath).join('\n') }], relatedIds: ['installation', 'api-reference', 'package-pure'],
};

const pure = frameworkAuthority.pure;
const pureTests = (frameworkAuthority.behaviourTestSources as Readonly<Record<string, string>>)['packages/pure/tests/noteTags.test.ts'] ?? '';
export const packagePureArticle: DocArticle = {
	id: 'package-pure', area: 'api', group: 'Packages', label: '@db3.ai/pure', title: '@db3.ai/pure', summary: 'Small portable helpers for ordinary application data. They do not create an App or replace validation and authorization.', packageName: '@db3.ai/pure', sourcePath: 'packages/pure/README.md',
	examplePaths: ['packages/pure/examples/selectNoteTags.ts', 'packages/pure/examples/runNoteTags.ts'], testPath: 'packages/pure/tests/noteTags.test.ts',
	verifiedExample: { description: 'Normalizes allowed note tags, rejects unknown values and recovers with a valid selection.', testPath: 'packages/pure/tests/noteTags.test.ts', command: 'npm test --workspace packages/pure', expectedOutput: 'The note-tag test passes using public Pure imports.', environment: 'Node.js and Vitest; no App, SQL or provider.' },
	sections: [
		{ id: 'setup', title: 'Install and copy the small example', paragraphs: ['Use Installation’s preview tarballs and development tools. App already depends on Pure, but a utility-only application can install just the supplied Pure tarball. After publication the package name is `@db3.ai/pure`.'], codeSampleId: 'copy', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'run', title: 'Normalize a tag selection', paragraphs: ['Run the copied example. Expect tags `Client` and `Internal`, `invalidRejected: true`, then recovery with `Internal`. Exact duplicates and whitespace/case variants collapse without sorting away the original selection order.'], codeSampleId: 'run' },
		{ id: 'use', title: 'Check the result before saving', paragraphs: ['`selectedStrings()` reports unknown entries in `invalid` but also retains them in `values`. This wrapper rejects invalid selections before a caller can persist them. Helpers expose mechanics; your feature decides whether unknown input is an error.', 'The HTTP boundary must still check that input is an array of strings. Normalization is not authorization, Unicode identity policy, HTML sanitization or a SQL escape mechanism.'], codeSampleId: 'source' },
		{ id: 'testing', title: 'Copy and run the test', paragraphs: ['Save the exact test as `tests/noteTags.test.ts`. Its relative import resolves the copied `examples/selectNoteTags.ts`. Change the allowed options and retain the rejected-value and recovery cases.'], codeSampleId: 'test-source' },
		{ id: 'run-tests', title: 'Check the consumer', paragraphs: ['These commands run from your app root. No framework checkout or backend process is needed.'], codeSampleId: 'test-command' },
		{ id: 'reference', title: 'Full public utility declarations', paragraphs: ['The sections below are generated from every typed Pure export in the staged package. They cover strings, collections, dates, records, errors, HTTP/auth/AI value helpers, URLs and ULIDs. The `/ai` helpers are portable value handling, not a provider SDK or agent runtime.', 'The tag scenario tests one common task. Test the utilities you use in your target browser or Node.js environment. Some helpers return an error/null while others throw; check the return type and function comment. URL normalization is not a remote-fetch allowlist.'] },
		...(pure?.publicExports ?? []).map(entry => ({ id: `pure-${entry.subpath === '.' ? 'root' : entry.subpath.slice(2)}`, title: entry.importPath, paragraphs: [], codeSampleId: entry.importPath })),
	], codeSamples: [{ id: 'copy', title: 'Copy the shipped utility lab', language: 'bash', code: 'mkdir -p examples\ncp -R node_modules/@db3.ai/pure/examples/. examples/' }, { id: 'run', title: 'Run the example', language: 'bash', code: 'npx tsx examples/runNoteTags.ts' }, { id: 'source', title: 'examples/selectNoteTags.ts', language: 'typescript', code: serviceExampleSources.selectNoteTags }, { id: 'runner', title: 'examples/runNoteTags.ts', language: 'typescript', code: serviceExampleSources.runNoteTags }, { id: 'test-source', title: 'tests/noteTags.test.ts', language: 'typescript', code: pureTests }, { id: 'test-command', title: 'Test and compile', language: 'bash', code: 'npx vitest run tests/noteTags.test.ts\nnpx tsc --noEmit --target ES2022 --module ESNext --moduleResolution Bundler --types node --skipLibCheck examples/*.ts' }, ...(pure?.publicExports ?? []).map(entry => ({ id: entry.importPath, title: entry.importPath, language: 'typescript', code: pure.declarationSources[entry.declarationPath] ?? '' }))], relatedIds: ['package-app', 'validation', 'url'],
};

export const testingArticle: DocArticle = {
	id: 'testing', area: 'services', group: 'Quality', label: 'Testing', title: 'Test the feature a developer will use', summary: 'Run real framework components through their public boundary. Make failure, recovery and cleanup part of the test.', packageName: '@db3.ai/app', sourcePath: 'packages/app/README.md', includeSourceDocument: false,
	sections: [
		{ id: 'start', title: 'Start in the consuming app', paragraphs: ['Use the generated starter’s `npm test`, `npm run check` and `npm run build`. For a smaller app, each service guide supplies a copyable Vitest test and compiler command. These commands run outside the framework repository.', 'A useful test builds the real App and HTTP factory, makes a request, checks the public response and the persisted result, then closes resources. Do not substitute a mock ActiveRecord for a database test.'], links: [{ label: 'Test private file access end to end', articleId: 'guide-testing' }, { label: 'Test the small HTTP app without SQL', articleId: 'create-app', sectionId: 'testing' }] },
		{ id: 'database', title: 'Use a disposable database', paragraphs: ['`createGeneratedTestDatabase()` creates a unique test-namespaced database and returns its connection plus `destroy()`. Pass that connection at App boot. Use `ActiveRecord.withDb()` for a scoped transaction rather than adding optional DB parameters to feature functions.', 'Framework service labs read `DB_*` and optional `DATABASE_URL`; generated starter tests deliberately use separate `TEST_DB_*` and clear the application URL. Follow the relevant guide’s configuration, not a production shell.', 'Keep cleanup in `finally`/test teardown. A killed process may leave artifacts; inspect exact generated names before removing them. No test should create, reshape or drop a live application database.'], links: [{ label: 'SQL prerequisites', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Starter test configuration', articleId: 'starter-app', sectionId: 'testing' }] },
		{ id: 'providers', title: 'Control only external dependencies', paragraphs: ['Keep framework Auth, Queue, Storage and model conversion real. Replace only external HTTP, email delivery, payment or cloud providers with deterministic responses. Use synthetic credentials and assert that invalid authorization never reaches the provider.', 'A fake provider proves your application behavior, not the provider integration. Separate capped live integration trials from local tests. Do not quietly contact a paid provider from an ordinary test command.'] },
		{ id: 'scenarios', title: 'Cover the boundary, not just one success', paragraphs: ['For each feature cover useful success, invalid input, unauthorized/foreign ownership, a meaningful failure, recovery and cleanup. Assert persisted values or absence of writes, not only the response code.', 'Avoid sleeps when the contract accepts a clock or fixed evaluation time. Run SQL suites serially when they share an active App or schema fixture. Test concurrent calls explicitly when concurrency is the behavior under review.'] },
		{ id: 'contributors', title: 'Framework contributor commands', paragraphs: ['These commands run in a checkout of the public framework repository. Tests live under the owning service’s `tests/`. The service runner rejects an unknown service name. MariaDB and Redis must be available for the complete integration suite.'], codeSampleId: 'contributor-commands' },
		{ id: 'package', title: 'Verify the packed package', paragraphs: ['Consumer-facing framework changes need both runtime imports and TypeScript checks from an installed tarball. The package gate covers public subpaths and selected runtime contracts; documented scenario trials additionally copy and run the shipped examples.', 'When upgrading, run the examples your application depends on against the new package version, including failure and cleanup cases.'], links: [{ label: 'Public API inventory', articleId: 'api-reference' }] },
		{ id: 'coverage', title: 'Name what actually ran', paragraphs: ['Keep fast local tests separate from database, provider and browser checks. Make required checks fail when infrastructure is unavailable, and list any skipped checks in CI so missing coverage is visible.'] },
	], codeSamples: [{ id: 'contributor-commands', title: 'Framework checkout only', language: 'bash', code: 'npm run test:service --workspace packages/app -- storage\nnpm run check --workspace packages/app\nnpm test --workspace packages/app\nnpm run framework:package:test' }], relatedIds: ['guide-testing', 'starter-app', 'api-reference'],
};

const testingEvidence = serviceLabEvidence('media', 'runPrivateFiles', 'Exercises an application-owned HTTP file workflow using real Auth, ActiveRecord, Media and local Storage.', 'Disposable SQL, temporary local files and Fastify injection.');
export const testingWorkflowArticle: DocArticle = {
	id: 'guide-testing', area: 'guides', group: 'Application guides', label: 'Testing', title: 'Test an application workflow across services', summary: 'Use private file access to test authentication, persistence, validation and cleanup together.', packageName: '@db3.ai/app/media', sourcePath: 'packages/app/src/media/README.md', testPath: testingEvidence.testPath, verifiedExample: testingEvidence, examplePaths: ['packages/app/src/media/examples/createPrivateFileServer.ts', 'packages/app/src/media/examples/runPrivateFiles.ts'],
	sections: [
		{ id: 'setup', title: 'Use the private-file application', paragraphs: ['Complete Installation, including the dedicated SQL test account, and install `fastify@5`. This test owns a small application factory; it handles requests in process without a running public server.'], links: [{ label: 'Private-file guide and complete route code', articleId: 'guide-files' }, { label: 'Installation', articleId: 'installation' }] },
		{ id: 'copy', title: 'Copy the maintained workflow', paragraphs: ['Copy the shipped Media examples. They include the real server factory and runner used by this test. Reusing them keeps the guide and test on one source of truth.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Observe the workflow once', paragraphs: ['The runner registers two real users, uploads and reads a file, rejects foreign access and invalid input, deletes the file and retries. Expect the status codes and cleanup flags listed in the private-file guide.'], codeSampleId: 'run-lab' },
		{ id: 'assertions', title: 'Assert both the response and the effect', paragraphs: ['A foreign request must return `404` and must not delete the owner’s bytes. Rejected input must not create another Media row. A successful delete must remove the bytes and make a later read return `404`.', 'Keep a valid retry after each deliberately broken state. A test that merely catches an exception can miss a poisoned connection, retained claim or leaked stream. The runner closes the HTTP server, App, generated database and temporary directory even after failure.'], codeSampleId: 'runner-source' },
		serviceLabTesting('media', 'runPrivateFiles'),
		{ id: 'run-tests', title: 'Run and change the scenario', paragraphs: ['Try another user, changed file content or a stricter size policy. Extend the assertion before changing the route, then run this test and compile the copied examples. No paid provider is involved.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Know the remaining gaps', paragraphs: ['This scenario proves real service behavior through injected HTTP. It does not prove browser cookie handling, proxies, socket disconnects, a cloud storage provider or a deployed migration. Add separate checks for those boundaries when your feature crosses them.'], links: [{ label: 'General testing conventions', articleId: 'testing' }, { label: 'Starter browser and API workflow', articleId: 'guide-api' }] },
	], codeSamples: [...serviceLabSamples('media', 'runPrivateFiles'), { id: 'runner-source', title: 'examples/runPrivateFiles.ts', language: 'typescript', code: serviceExampleSources.runPrivateFiles }], relatedIds: ['guide-files', 'testing', 'auth', 'media'],
};

export const appApiArticle = createApiReference({ id: 'app-api', label: 'App API', packageName: '@db3.ai/app/server', sourcePath: 'packages/app/src/server/README.md', guideId: 'app', references: [['app', 'App and service options', 'dist/server/App.d.ts'], ['active', 'Active application context', 'dist/server/appContext.d.ts'], ['request', 'Request-scoped values', 'dist/server/RequestContext.d.ts']] });
