import type { DocCodeSample, DocContentSection } from '../docs';
import { serviceExampleOutputs, serviceExampleSources } from '../generated/service-examples';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

export const queueGuideEvidence = serviceLabEvidence('queue', 'runQueueReports', 'Restores persisted SQL work in a new App, repairs and replays a failed report, drains a worker and checks duplicate-safe output.', 'Node.js 24, MariaDB and a test-only database account. Local files only; no AI key, email or remote provider.');
export const queueGuidePaths = ['packages/app/src/queue/examples/WriteReportJob.ts', 'packages/app/src/queue/examples/runQueueReports.ts', 'packages/app/src/queue/examples/reportConsole.ts', 'packages/app/src/queue/examples/outputs/queue-reports.json'];
const sources: Readonly<Record<string, string>> = serviceExampleSources;
const outputs: Readonly<Record<string, string>> = serviceExampleOutputs;

export const queueGuideSections: DocContentSection[] = [
	{ id: 'app-start', title: 'Create a job in your app', paragraphs: [
		'Work from the root of your locally installed db3 app. Your app already has configuration, a database and a shared bootstrap in `server/app.ts`. This guide starts by adding a job, dispatching it from application code and running a worker.',
		'Run `npx db3 queue:make-job GenerateReportJob` to create `server/jobs/GenerateReportJob.ts`, then replace the generated template with the class below. Its `handle()` method logs the report ID so you can see the worker execute it. Replace that method with your report-generation logic as you build the feature. Keep payloads small and JSON-safe; pass record IDs rather than model instances or service objects.',
	], codeSampleId: 'app-job', links: [{ label: 'Create and run your app', articleId: 'starter-app' }] },
	{ id: 'app-register', title: 'Register the job with your application', paragraphs: [
		'In `server/app.ts`, import the job and register it on the application before returning it. Keep your existing App options. Both HTTP requests and workers use this factory, so every process can restore a queued job by its class name.',
		'Dispatching a job registers its class in the current process only. Registration in the shared bootstrap is what makes a separate worker able to execute it. The generator creates your file without overwriting existing code. Registration remains explicit. The same `createJob()` operation is available to editor and Studio integrations; a Studio creation screen is separate UI work.',
	], codeSampleId: 'app-register' },
	{ id: 'app-database', title: 'Add the queue tables', paragraphs: [
		'In `server/database/models.ts`, import `QueuedJob` and `FailedJob` from `@db3.ai/app/queue` and append them to the existing `models` array. Retain your other models. Then generate, review and apply the migration below against your development app database.',
	], codeSampleId: 'app-migrate', links: [{ label: 'Application migrations', articleId: 'migrations' }] },
	{ id: 'app-dispatch', title: 'Dispatch from your application', paragraphs: [
		'Call the queue from a route or application service after your app has booted. The returned ID identifies the queued record; it does not mean the report has completed. The worker will call `handle()` in its own process.',
	], codeSampleId: 'app-dispatch' },
	{ id: 'app-console', title: 'Run your worker', paragraphs: [
		'Create `server/console.ts` with the adapter below. It uses the same application factory and `.env` configuration as your HTTP server. It does not start another HTTP listener. The console handles worker shutdown and closes the application after finite commands.',
	], codeSampleId: 'app-console' },
	{ id: 'app-run', title: 'Try the complete workflow', paragraphs: [
		'Run these commands from your app root. The first dispatches a job without needing a route; the second processes one available job from the `reports` queue. You should see `Generating report` with `reportId: weekly`, followed by the processed result.',
		'Leave off `--once` to keep the worker running while you use your app. Stop it with Ctrl-C. The remaining sections explain retries, failed jobs, named queues and deployment. The standalone report lab later in this guide is optional.',
	], codeSampleId: 'app-commands' },
	{ id: 'worker-selection', title: 'Share workers across named queues', paragraphs: [
		'Jobs keep one queue name. Workers can select several names with `queues: ["default", "articles"]`, or discover all names with `queues: "*"`. Add `excludeQueues` to reserve a worker for general work while shared workers use spare capacity across all queues. Put these selections in your console configuration and select a pool when starting each process.',
		'Workers rotate between eligible queues after each claim, skip empty queues and execute one job at a time. Exclusions always win and apply before claiming. A wildcard includes queues introduced later in the same database or Redis namespace. Use an explicit array when new queues should require an intentional configuration change. This is round-robin scheduling, not ordered priority or equal CPU time.',
		'Run one process with `queue:work --pool=general` and additional processes with `queue:work --pool=shared`. The existing `--queue=reports` still selects one queue; `--queues=default,articles` selects several. Quote `--queues="*"` in the shell. `--once` follows the same selection rules. On shutdown, finish the current job and stop claiming more work. Keep consumers for jobs already persisted on old queue names during routing changes.',
	], codeSampleId: 'worker-selection' },
	{ id: 'setup', title: 'Optional: run the standalone report example', paragraphs: [
		'A queue is useful when the request should finish before the work does. We will queue a report, close the producer, restore it in a fresh worker, fix a missing input and replay the failed job. Repeating it leaves one report, not two.',
		'Complete Installation using Node.js 24, matching preview App/Pure tarballs, `tsx`, TypeScript and Vitest. These packages are not published yet. The isolated lab needs a local MariaDB server and a test account allowed to create and drop only `db3_app_test_*` databases. It never uses the starter’s notes database.',
		'Use the test-only `.env` from Installation. `DATABASE_URL` overrides the separate `DB_*` variables, so unset it unless it deliberately targets your test server. The lab creates and removes its own database and temporary files; do not give it production credentials.',
	], links: [{ label: 'Install packages and configure test SQL', articleId: 'installation', sectionId: 'database-labs' }, { label: 'Install MariaDB locally', articleId: 'starter-app', sectionId: 'database' }] },
	{ id: 'copy', title: 'Copy the example', paragraphs: ['Run from your independent app directory. The files are shipped with `@db3.ai/app`; you do not need the framework repository. Keep the `outputs/` directory because the consumer test uses its expected result.'], codeSampleId: 'copy-lab' },
	{ id: 'run', title: 'Run the report lab', paragraphs: ['The first attempt is `released`, the second is `failed`. The lab then writes the missing source, replays the failure and drains a real polling worker. Its final result has `reportFiles: 1`, `remainingJobs: 0` and `retainedFailures: 1`.', 'The deliberate zero-second backoff is for this deterministic lab only. Use a non-zero delay and a bounded retry policy in an application. Nothing is sent to an external provider.'], codeSampleId: 'run-lab' },
	{ id: 'report-job', title: 'Make the job safe to repeat', paragraphs: ['The payload stores an immutable report revision, not a storage path or secret. The constructor validates that identity when dispatching and restoring. `handle()` reads the source and replaces one report file.', 'This makes repeated completion useful, but does not promise atomic file replacement or exactly-once side effects. A payment or email needs an application/provider idempotency key. Avoid a read-then-write “already processed” flag without a database constraint or transactional claim.'], codeSampleId: 'report-job-source' },
	{ id: 'run-source', title: 'Dispatch, repair and replay', paragraphs: ['The producer and worker are separate `App` instances sharing only SQL and configured storage. Dispatching a class auto-registers it in that process only. The worker must register it again.', '`Database.install()` is confined to this disposable lab. It is not a production startup instruction. The worker awaits `stopAndDrain()` before the app and test database are closed.'], codeSampleId: 'queue-lab-source' },
	{ id: 'application-worker', title: 'Add a worker to the starter', paragraphs: [
		'For the migration-first Notes + AI starter, add `QueuedJob` and `FailedJob` from `@db3.ai/app/queue` to the exported `models` array in `server/database/models.ts`, retaining all existing models. Run `npm run db:make:migration -- add_queue_tables`, inspect the generated migration, then run `npm run db:migrate` and `npm run db:check`.',
		'The copied `reportConsole.ts` is a complete database-queue adapter. It loads your app-root `.env`, registers the report job and exposes the framework console. Run this path against your development app database, not the lab’s test-only `.env`.',
		'Its local storage root is `data/queue-reports` or an absolute `REPORT_STORAGE_ROOT`. Both producer and worker must see the same root. Add `data/` and `.env` to `.gitignore`. The local-file example assumes one host or a shared volume; separate hosts need shared storage.',
		'For your own feature, reuse your application bootstrap in the adapter so model registrations, selected driver, storage and configuration cannot drift. Do not start the HTTP server inside a worker.',
	], codeSampleId: 'queue-console-source', links: [{ label: 'Get the migration-first starter', articleId: 'starter-app', sectionId: 'create' }] },
	{ id: 'worker-commands', title: 'Dispatch and run from the terminal', paragraphs: [
		'Run these commands from the app root, after migrating. `report:seed` writes only the fixed demo input; omit it to try a missing-file failure. `queue:failed` is an example-owned command that prints bounded failure metadata. The remaining commands come from `runQueueConsole()`.',
		'Expect a “Dispatched” line, then “Processed” from the one-off worker. The file `data/queue-reports/reports/weekly-v1.txt` contains `Report: Three notes ready`. Without `--once`, leave the worker running in a separate terminal and stop it with Ctrl-C.',
		'`--once` processes at most one available job, not the entire queue. `--max-jobs` is a sequential per-tick bound, not concurrency. Start additional supervised worker processes for parallelism. Queue command names are not globally installed executables.',
	], codeSampleId: 'queue-console-commands' },
	{ id: 'transactions', title: 'Commit records before dispatching work', paragraphs: ['Do not dispatch a job from an uncommitted model transaction through the default `app().queue` and assume it shares that transaction. It has its own database connection. The worker may run before the data exists, and a rollback will not undo that dispatch.', 'The simple path is commit, then dispatch. There is still a crash window between those operations. When missing a job is unacceptable, write an application outbox record in the same transaction and publish it with reconciliation and idempotency. There is no built-in `afterCommit()` or transactional outbox API.'], links: [{ label: 'Scoped model transactions', articleId: 'active-record-api', sectionId: 'record-methods' }] },
	{ id: 'shutdown', title: 'Shut down and deploy workers', paragraphs: ['Use `stopAndDrain()` before closing the App. It finishes the active tick, which can include several sequential jobs. `stop()` only stops future polling; it does not abort a handler. Give the process supervisor enough grace time for that work.', '`App.close()` does not stop queue workers or close a Redis queue driver. When using Redis, construct and retain the `RedisQueueDriver`, inject it into `App` queue options, then drain workers, call `driver.close()` and finally `application.close()`.', 'Restart workers after deploying new code. Keep stable `jobName` values such as `reports.write.v1`, and support old payloads while stored jobs still reference them. Do not remove old classes before queued and replayable work has been dealt with.'] },
	{ id: 'redis', title: 'Choose Redis when you need it', paragraphs: ['The database driver uses `QueuedJob` and `FailedJob` tables. Redis uses a job hash, ready lists, delayed/reserved sets and failed storage behind the same Queue API. Moving to Redis does not move already queued SQL work.', 'Use a dedicated namespace per app and environment, authentication/TLS as appropriate, and a persistence and eviction policy that cannot silently discard jobs. A namespace is not an authorization boundary. The current service suite can exercise real Redis; this report lab proves the database path only.', 'Keep a driver reference so the host can close it. For a console adapter, provide a close callback that closes that driver and then the App after the worker has drained.'], codeSampleId: 'redis-options' },
	{ id: 'troubleshooting', title: 'When a job does not run', paragraphs: ['“No jobs available” can mean the wrong queue, a future `availableAt`, an active reservation or genuinely no work. Check the dispatch queue and worker `--queue` first. A delay is earliest availability, not an exact scheduled execution time.', '“No handler registered” means the worker bootstrap cannot resolve the durable name. Register the class, deploy matching code, then inspect/replay a terminal failure. Missing `jobs` or `jobs_failed` tables mean queue migrations have not run on this database.', '`retryAfterSeconds` is a renewable lease, not a handler timeout. Use explicit timeouts at external API boundaries. A blocked event loop can stop heartbeats. `lease_lost` does not prove the handler did nothing: reconcile side effects before retrying.', 'A delayed or terminally failed attempt can still produce a successful CLI exit. Inspect the result/logged status, not only the shell exit code. An infrastructure exception can reject `workNextJob()` rather than returning an attempt result.'] },
	{ id: 'monitoring', title: 'Track progress without leaking data', paragraphs: ['`queue.events.subscribe()` observes lifecycle transitions and returns an unsubscribe function. Listeners and job hooks are awaited after transitions; their failure cannot roll back the transition. Avoid slow observers that hold up workers.', 'Queue events, stored payloads and failed exceptions can contain sensitive application values. Keep secrets out of payloads and error messages, redact before shipping logs, restrict failure inspection/replay, and define retention. The example CLI lists identities only, not payloads or stack traces.', 'Successful jobs are removed from active storage. Store user-visible report status and output identity on an application model. `QueueMonitor` is development telemetry, not durable progress, an audit ledger or a substitute for alerts on backlog age and failed jobs.'] },
	serviceLabTesting('queue', 'runQueueReports'),
	{ id: 'run-tests', title: 'Run and extend your tests', paragraphs: ['The copied test executes real SQL, local storage and Queue; it does not replace the driver with a fake. It also rejects unsafe report identities. Keep `examples/outputs/queue-reports.json` beside the example.', 'Change the source text and update the expected result. Add a test for an unregistered worker, a deleted source, a second report revision, or a retry that must not repeat an external effect. Mock only the external provider when you add one.'], codeSampleId: 'test-lab' },
	{ id: 'coverage', title: 'Coverage and next steps', paragraphs: ['This walkthrough runs SQL persistence across App lifetimes, named queues, ordinary retry/exhaustion, failure inspection and replay, worker drain, repeatable output and invalid payload rejection. The smaller Queue examples on this page separately exercise chains, batches and backpressure using a deterministic test driver; hooks have additional service tests.', 'The reference lists current service, job, payload, retry, lifecycle and driver contracts. Redis conformance, lease fencing, console and worker behaviour also have service-owned tests; they are not all demonstrated by this lab.', 'Not provided: hard job cancellation/timeouts, built-in unique jobs, atomic chain handoff, first-class tracked batches, retry-all, automatic pruning or a transactional outbox. Follow-up recipes: provider-backed AI budgets, idempotent email delivery and failure-retention operations. Those remain TODO, not available APIs.'], links: [{ label: 'Queue API and driver contracts', articleId: 'queue-api' }, { label: 'Schedule recurring reports', articleId: 'scheduler' }, { label: 'Problem-solving recipe catalogue', articleId: 'solve-a-problem' }] },
];

export const queueGuideSamples: DocCodeSample[] = [
	{ id: 'worker-selection', title: 'server/console.ts', language: 'typescript', code: "import { runQueueConsole } from '@db3.ai/app/queue';\nimport { createApplication } from './app';\nimport { readConfig } from './config';\n\nconst application = createApplication(readConfig());\ntry {\n\tawait runQueueConsole({\n\t\tapp: () => application,\n\t\tworkers: {\n\t\t\tgeneral: { queues: '*', excludeQueues: ['articles', 'article-images'] },\n\t\t\tshared: { queues: '*' },\n\t\t},\n\t});\n} catch (error) {\n\tawait application.close();\n\tthrow error;\n}" },
	{ id: 'app-job', title: 'server/jobs/GenerateReportJob.ts', language: 'typescript', code: sources.generateReportJob ?? '' },
	{ id: 'app-register', title: 'server/app.ts', language: 'typescript', code: "import { App, type AppOptions } from '@db3.ai/app';\nimport type { StarterConfig } from './config';\nimport { GenerateReportJob } from './jobs/GenerateReportJob';\n\n/** Creates the application shared by HTTP, commands and workers. */\nexport function createApplication(config: StarterConfig, options: Pick<AppOptions, 'db' | 'ai'> = {}) {\n\tconst application = new App({\n\t\tai: config.ai,\n\t\t...options,\n\t\tconfig: { auth: { providers: {\n\t\t\tpassword: true,\n\t\t\t...(config.auth.googleClientId ? { google: { clientIds: [config.auth.googleClientId] } } : {}),\n\t\t} } },\n\t});\n\tapplication.queue.registerJob(GenerateReportJob);\n\treturn application;\n}" },
	{ id: 'app-migrate', title: 'From your app root', language: 'bash', code: 'npm run db:make:migration -- add_queue_tables\n# Review the generated migration.\nnpm run db:migrate\nnpm run db:check' },
	{ id: 'app-dispatch', title: 'Inside a route or application service', language: 'typescript', code: "import { app } from '@db3.ai/app/server';\nimport { GenerateReportJob } from './jobs/GenerateReportJob';\n\nconst jobId = await app().queue.dispatch(\n\tnew GenerateReportJob({ reportId: 'weekly' }),\n\t{ queue: 'reports' },\n);" },
	{ id: 'app-console', title: 'server/console.ts', language: 'typescript', code: "import { runQueueConsole } from '@db3.ai/app/queue';\nimport { createApplication } from './app';\nimport { readConfig } from './config';\n\nconst application = createApplication(readConfig());\ntry {\n\tawait runQueueConsole({ app: () => application });\n} catch (error) {\n\tawait application.close();\n\tthrow error;\n}" },
	{ id: 'app-commands', title: 'From your app root', language: 'bash', code: 'npx tsx server/console.ts queue:dispatch GenerateReportJob \'{"reportId":"weekly"}\' --queue=reports\nnpx tsx server/console.ts queue:work --queue=reports --once' },
	...serviceLabSamples('queue', 'runQueueReports').map(sample => sample.id === 'test-lab' ? { ...sample, code: 'npx vitest run tests/queue/runQueueReports.test.ts --maxWorkers=1\nnpx tsc --noEmit --target ES2022 --module ESNext --moduleResolution Bundler --types node --resolveJsonModule --skipLibCheck examples/*.ts' } : sample),
	{ id: 'report-job-source', title: 'examples/WriteReportJob.ts', language: 'typescript', code: sources.writeReportJob ?? '' },
	{ id: 'queue-lab-source', title: 'examples/runQueueReports.ts', language: 'typescript', code: sources.runQueueReports ?? '', output: outputs.queueReports ?? '', outputLanguage: 'json' },
	{ id: 'queue-console-source', title: 'examples/reportConsole.ts', language: 'typescript', code: sources.reportConsole ?? '' },
	{ id: 'queue-console-commands', title: 'Your application, after migrating', language: 'bash', code: 'npx tsx examples/reportConsole.ts report:seed\nnpx tsx examples/reportConsole.ts queue:dispatch reports.write.v1 \'{"reportId":"weekly-v1"}\' --queue=reports --tries=2\nnpx tsx examples/reportConsole.ts queue:work --queue=reports --once\nnpx tsx examples/reportConsole.ts queue:failed\n\n# Continuous worker; Ctrl-C drains and exits.\nnpx tsx examples/reportConsole.ts queue:work --queue=reports --max-jobs=1\n\n# After repairing a terminal failure, replace 123 with its failed-record id.\nnpx tsx examples/reportConsole.ts queue:retry 123 --queue=reports' },
	{ id: 'redis-options', title: 'Redis configuration and explicit ownership', language: 'typescript', code: "import { RedisQueueDriver } from '@db3.ai/app/queue';\nimport { App } from '@db3.ai/app/server';\n\nconst driver = new RedisQueueDriver({\n\turl: process.env.QUEUE_REDIS_URL,\n\tkeyPrefix: 'my-app:development:queue',\n});\nconst application = new App({ queue: { driver, queue: 'reports' } });\n// Register jobs before starting workers. Retain driver for shutdown.\n// await worker.stopAndDrain();\n// await driver.close();\n// await application.close();" },
];
