import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const urlEvidence = serviceLabEvidence('url', 'runApplicationLinks', 'Builds canonical links, checks root versus relative paths, rejects invalid config and external redirects, then repairs the base.', 'Node.js only; no HTTP requests, database or external provider.');
export const urlArticle: DocArticle = {
	id: 'url', area: 'services', group: 'Application', label: 'URLs', title: 'Application URLs', summary: 'Give email, workers and HTTP routes one trusted application address. A URL resolver is not a redirect policy.',
	packageName: '@db3.ai/app/url', sourcePath: 'packages/app/src/url/README.md', examplePaths: ['packages/app/src/url/examples/runApplicationLinks.ts'], testPath: urlEvidence.testPath, verifiedExample: urlEvidence,
	sections: [
		{ id: 'setup', title: 'Configure the browser-facing URL', paragraphs: ['Set `new App({ url: { baseUrl: "https://your-app.example" } })`, or provide `APP_URL`. Resolution is explicit `baseUrl`, then `APP_URL`, then `PUBLIC_APP_URL`, then `localPort`. The frontend’s development port may differ from the backend port.', 'The service requires an HTTP(S) base or a valid local port. It does not read request Host headers. A configured environment base wins over the local fallback, so keep production values out of a local test shell.'], links: [{ label: 'Installation', articleId: 'installation' }, { label: 'Validate configuration at boot', articleId: 'config' }] },
		{ id: 'copy', title: 'Copy the example', paragraphs: ['Use the independent application and tools from Installation. No SQL or running server is needed.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run the links', paragraphs: ['Expect the relative path under `/workspace/`, the root-relative path under the origin, both rejection flags true, and the repaired sign-in URL.'], codeSampleId: 'run-lab' },
		{ id: 'use', title: 'Use the canonical generator', paragraphs: ['`app().url.baseUrl` is normalized without trailing slashes. `to("notes/one")` resolves beneath a configured base path; `to("/notes/one")` resolves from the origin root. Query strings and fragments follow the standard `URL` rules.', 'An absolute or protocol-relative argument can change origin. The example’s `applicationLink()` is an application-owned guard for root-relative same-origin redirects, not another framework method. Never treat `to()` as permission to fetch a URL or redirect a user.'], codeSampleId: 'url-source' },
		{ id: 'scope', title: 'Keep request URLs separate', paragraphs: ['The canonical address is application configuration, not mutable per-request state. SSR receives each request URL on its own render context. Background jobs can use the same canonical service without an HTTP server.', 'There is no named-route registry, signed URL service, URL-shortener or remote-fetch allowlist here. Use explicit paths, and document any application-specific routing policy.'], links: [{ label: 'Server rendering', articleId: 'ssr' }] },
		serviceLabTesting('url', 'runApplicationLinks'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['The tests clear URL environment fallbacks when checking missing configuration and restore them afterwards. Change the base subpath, test your redirect inputs and keep rejection of external origins.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and API', paragraphs: ['Tested: explicit base, subpaths, local fallback, invalid/missing configuration, guarded external references and recovery. Reference: the two configuration options and complete generator. No external service is contacted.'], links: [{ label: 'URL API', articleId: 'url-api' }] },
	], codeSamples: [...serviceLabSamples('url', 'runApplicationLinks'), { id: 'url-source', title: 'examples/runApplicationLinks.ts', language: 'typescript', code: serviceExampleSources.runApplicationLinks }], relatedIds: ['config', 'mail', 'ssr'],
};

const serializationEvidence = serviceLabEvidence('serialization', 'runExportSerialization', 'Reconstructs a registered export request through JSON, rejects an unknown worker registration and invalid state, then repairs both.', 'Node.js; the scalar-identity lab does not need SQL or a worker process.');
export const serializationArticle: DocArticle = {
	id: 'serialization', area: 'services', group: 'Application', label: 'Serialization', title: 'Restore durable application objects', summary: 'Save the state needed to call one registered constructor again. Keep services and connections out of the payload.',
	packageName: '@db3.ai/app/serialization', sourcePath: 'packages/app/src/serialization/README.md', examplePaths: ['packages/app/src/serialization/examples/ExportRequest.ts', 'packages/app/src/serialization/examples/runExportSerialization.ts'], testPath: serializationEvidence.testPath, verifiedExample: serializationEvidence,
	sections: [
		{ id: 'setup', title: 'Register a stable contract', paragraphs: ['Configure `serializer.classes` in App options: `new App({ serializer: { classes: { "notes.export.v1": ExportRequest } } })`. The service is `app().serializer`, with an application-scoped registry. Register the same names and constructors in every producer and worker at boot.', 'Names are durable wire contracts, not filenames. The example uses its own state version in addition to the framework envelope version. Renaming or changing state requires an explicit stored-payload migration or discard policy.'], links: [{ label: 'Install the tools', articleId: 'installation' }] },
		{ id: 'copy', title: 'Copy the request and runner', paragraphs: ['This first lab uses a scalar owner ID, so it has no database dependency. It deliberately does not claim that an ID is authorization.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect `label: "ada:25"`, `privateStateRestored: true`, wire version `1`, both rejection flags true and the repaired label. The runner round-trips through `JSON.stringify()` and `JSON.parse()` rather than passing live objects between calls.'], codeSampleId: 'run-lab' },
		{ id: 'constructor', title: 'Make the constructor the state contract', paragraphs: ['Implement `Serializable<State>`. `toJSON()` returns the full input accepted by the one-argument constructor. Validation runs during both ordinary construction and restoration; private fields are initialized normally.', 'Use plain JSON values deliberately. `undefined`, dates, bigint, functions, non-finite numbers, negative zero, sparse arrays, cycles and nested application-class instances are rejected. Convert special values explicitly. `$platform` is reserved for framework reference markers.'], codeSampleId: 'request-source' },
		{ id: 'restore', title: 'Restore in another process', paragraphs: ['`serialize()` requires the exact registered root class. `deserialize()` validates the envelope, resolves registrations and calls the constructor. Registering a class only while dispatching does not register it in a worker.', 'The generic `deserialize<ExportRequest>()` annotates a result; it is not a separate schema or authorization check. Keep the payload’s expected registered name under application control. The registry is an allowlist, not a safe endpoint for arbitrary untrusted object execution.'], codeSampleId: 'runner-source' },
		{ id: 'models', title: 'Use model references when you want current data', paragraphs: ['Register model names in `serializer.models`. A clean, persisted ActiveRecord inside constructor state becomes a model name and logical primary key, not an attribute snapshot. Restoration reloads the current row through the active application database.', 'Unsaved, dirty, unregistered or soft-deleted records are rejected. Repeated references share a lookup and restored instance. A missing row fails restoration. If deletion should make the work a no-op, store a scalar ID and perform an optional, scoped lookup inside the worker.', 'Authorization still belongs to the workflow. The model-reference lookup is not an organization membership check. This first lab does not exercise model restoration; the service-owned SQL tests cover its contract.'], links: [{ label: 'ActiveRecord', articleId: 'active-record' }, { label: 'Scope queries explicitly', articleId: 'queries' }] },
		{ id: 'errors', title: 'Handle failures without hiding them', paragraphs: ['`SerializationError` carries operation, code, path and an optional cause. `SerializationRegistryError` identifies invalid or conflicting registrations. Return safe application errors rather than exposing constructor state or stack traces.', 'The lab repairs a missing registration, then proves a rejected payload did not stop later valid work. Constructors should validate and initialize state; avoid irreversible side effects while restoring. Ordinary queue jobs already use their own JSON data constructor contract and do not automatically use this service.'] },
		serviceLabTesting('serialization', 'runExportSerialization'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the export limit and add a state field with constructor validation. Verify old payload handling deliberately. The copied tests need no SQL; the complete contributor service suite also includes real database restoration tests.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and API', paragraphs: ['Tested here: registration, JSON durability, private-state reconstruction, invalid state/version, missing worker registration and recovery. Explained: model identity, supported values, duplicate registration, versioning, worker boot and trust boundaries. A model-restoration cookbook with missing-row recovery remains a follow-up.'], links: [{ label: 'Serialization API', articleId: 'serialization-api' }] },
	], codeSamples: [...serviceLabSamples('serialization', 'runExportSerialization'), { id: 'request-source', title: 'examples/ExportRequest.ts', language: 'typescript', code: serviceExampleSources.exportRequest }, { id: 'runner-source', title: 'examples/runExportSerialization.ts', language: 'typescript', code: serviceExampleSources.runExportSerialization }], relatedIds: ['queue-overview', 'active-record', 'serialization-api'],
};

const ssrEvidence = serviceLabEvidence('ssr', 'runPublicPages', 'Renders concurrent public pages, round-trips dangerous-looking JSON safely, preserves literal markup and recovers from a private render failure.', 'Fastify injection and Node.js; no SQL, Vue build, provider or listening port.');
export const ssrArticle: DocArticle = {
	id: 'ssr', area: 'services', group: 'Application', label: 'Server rendering', title: 'Render public HTML', summary: 'SSR owns the document and request boundary. Your application owns the pages, router, data and client hydration.',
	packageName: '@db3.ai/app/ssr', sourcePath: 'packages/app/src/ssr/README.md', examplePaths: ['packages/app/src/ssr/examples/createPublicPageServer.ts', 'packages/app/src/ssr/examples/runPublicPages.ts'], testPath: ssrEvidence.testPath, verifiedExample: ssrEvidence,
	sections: [
		{ id: 'setup', title: 'Set up a small public page', paragraphs: ['Use the installed framework and tools from Installation, then install `fastify@5`. SSR is an optional module, not an `App` service. This lab renders public HTML without Vue or hydration so the request/document boundary is easy to see.'], codeSampleId: 'http-install', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'copy', title: 'Copy the server and runner', paragraphs: ['The server factory does not listen. The runner exercises it through Fastify injection and closes it afterwards.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['Expect `200` for a page and recovery, `500` for the controlled failure, `404` for the unknown API route, and true isolation, safe-state, literal-markup and private-error flags.'], codeSampleId: 'run-lab' },
		{ id: 'render', title: 'Own the routes and template', paragraphs: ['`fastifySsr()` receives explicit routes, a document template and a renderer. `/api/health` stays an ordinary JSON endpoint; unknown API paths do not receive an HTML success page.', 'The app marker is required. Head and state markers are optional for deliberately non-hydrating documents. The renderer returns trusted `appHtml` plus optional status, headers, head or state overrides. The framework does not sanitize arbitrary HTML.'], codeSampleId: 'server-source' },
		{ id: 'state', title: 'Keep state isolated and safe', paragraphs: ['Each render gets a new context with state, head metadata and a module set. Never share a mutable Vue app, router, store or authentication state between requests. In a Vue integration, create them inside each render.', 'Hydration state is escaped JSON inside an `application/json` script. Parse its text content; do not evaluate it. Escaping does not make secrets safe to send to a browser. Only serialize data that the current user may receive.', 'Head attributes are escaped. Inline head scripts and body HTML must come from trusted application code. The lab puts request input only into escaped title/state values and checks that literal replacement-token text is preserved.'], codeSampleId: 'runner-source' },
		{ id: 'vite', title: 'Add Vue and Vite when the app needs them', paragraphs: ['`@db3.ai/app/ssr/vite` supplies `fastifyViteSsr()`. It owns development middleware, transformed templates, server entry loading, production client/server outputs, static assets and manifest-based preload links.', 'The application still supplies Vue entries, router and data loading through its HTTP API. Configure explicit routes and build paths; an SSR adapter does not turn every SPA route into a server-rendered page. Keep the server bundle out of the public asset directory.', 'The detailed source-backed reference and API show Vite options. This lab does not install a Vue app or prove hydration/build behavior; the framework has separate Vite lifecycle tests, and this documentation website uses the adapter. A standalone Vue/Vite walkthrough is a follow-up.'] },
		{ id: 'errors', title: 'Make failure and cache policy deliberate', paragraphs: ['A renderer exception is logged server-side and becomes plain `Internal Server Error` with status `500`. Do not return internal stack traces. The lab deliberately fails one request and proves the next request still renders.', 'Use status `404` and suitable robots metadata for missing pages. Set cache policy from the application’s data sensitivity. The lab uses `private, no-store`; public cache headers require genuinely public content and an invalidation policy.'] },
		serviceLabTesting('ssr', 'runPublicPages'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['Change the page title or add an explicitly owned route. Keep concurrent-request, literal text, escaped state and unknown-API assertions. Injection does not prove proxy configuration, client hydration or browser cache behavior.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and API', paragraphs: ['Tested: real Fastify adapter, route ownership, HTML/head/state rendering, concurrent isolation, safe state and private failure/recovery. Explained/reference: Vue/Vite integration, manifests, static delivery, hydration and deployment policy.'], links: [{ label: 'SSR API and adapters', articleId: 'ssr-api' }] },
	], codeSamples: [...serviceLabSamples('ssr', 'runPublicPages'), { id: 'http-install', title: 'Install the HTTP adapter', language: 'bash', code: 'npm install fastify@5' }, { id: 'server-source', title: 'examples/createPublicPageServer.ts', language: 'typescript', code: serviceExampleSources.createPublicPageServer }, { id: 'runner-source', title: 'examples/runPublicPages.ts', language: 'typescript', code: serviceExampleSources.runPublicPages }], relatedIds: ['url', 'create-app', 'ssr-api'],
};

export const urlApiArticle = createApiReference({ id: 'url-api', label: 'URL API', packageName: '@db3.ai/app/url', sourcePath: 'packages/app/src/url/README.md', guideId: 'url', references: [['generator', 'Canonical URL generator', 'dist/url/UrlGenerator.d.ts'], ['options', 'Configuration', 'dist/url/contracts/UrlGeneratorOptions.d.ts']] });
export const serializationApiArticle = createApiReference({ id: 'serialization-api', label: 'Serialization API', packageName: '@db3.ai/app/serialization', sourcePath: 'packages/app/src/serialization/README.md', guideId: 'serialization', references: [['serializer', 'Serializer', 'dist/serialization/Serializer.d.ts'], ['registry', 'Registry', 'dist/serialization/SerializationRegistry.d.ts'], ['serializable', 'Root instance', 'dist/serialization/Serializable.d.ts'], ['constructor', 'Root constructor', 'dist/serialization/contracts/SerializableClass.d.ts'], ['options', 'Registration options', 'dist/serialization/contracts/SerializerOptions.d.ts'], ['wire', 'Wire values and envelope', 'dist/serialization/contracts/SerializedValue.d.ts'], ['errors', 'Serialization errors', 'dist/serialization/SerializationError.d.ts'], ['registry-errors', 'Registry errors', 'dist/serialization/SerializationRegistryError.d.ts']] });
export const ssrApiArticle = createApiReference({ id: 'ssr-api', label: 'SSR API', packageName: '@db3.ai/app/ssr', sourcePath: 'packages/app/src/ssr/README.md', guideId: 'ssr', references: [['markers', 'Document template markers', 'dist/ssr/constants.d.ts'], ['manifest', 'Apply the manifest: @db3.ai/app/ssr/vite', 'dist/ssr/vite/viteSsrManifest.d.ts'], ['document', 'Document assembly', 'dist/ssr/renderSsrDocument.d.ts'], ['head', 'Head rendering', 'dist/ssr/renderDocumentHead.d.ts'], ['head-contract', 'Head metadata', 'dist/ssr/contracts/DocumentHead.d.ts'], ['context', 'Request render context', 'dist/ssr/contracts/SsrRenderContext.d.ts'], ['create-context', 'Context factory', 'dist/ssr/createSsrRenderContext.d.ts'], ['renderer', 'Renderer', 'dist/ssr/contracts/SsrRenderer.d.ts'], ['request', 'Request', 'dist/ssr/contracts/SsrRequest.d.ts'], ['result', 'Result and headers', 'dist/ssr/contracts/SsrRenderResult.d.ts'], ['state', 'Safe JSON state', 'dist/ssr/serializeSsrState.d.ts'], ['fastify', 'Fastify adapter: /ssr/fastify', 'dist/ssr/fastify/fastifySsr.d.ts'], ['fastify-options', 'Fastify options', 'dist/ssr/fastify/contracts/FastifySsrOptions.d.ts'], ['vite', 'Vite adapter: /ssr/vite', 'dist/ssr/vite/fastifyViteSsr.d.ts'], ['vite-options', 'Vite options', 'dist/ssr/vite/contracts/ViteSsrOptions.d.ts']] });
