import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const evidence = serviceLabEvidence('storage', 'runStorage', 'Writes JSON and a streamed CSV, lists the files, rejects traversal and removes a file on a real local disk.', 'Node.js and an isolated temporary directory; no database or remote storage account.');

export const storageArticle: DocArticle = {
	id: 'storage', area: 'services', group: 'Files', label: 'Storage', title: 'Storage',
	summary: 'Write files to a named disk, stream large payloads and keep paths relative to storage. Add Media when files need durable identities and ownership metadata.',
	packageName: '@db3.ai/app/storage', sourcePath: 'packages/app/src/storage/README.md', examplePaths: ['packages/app/src/storage/examples/runStorage.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Configure a disk', paragraphs: ['Use `storage.default` and `storage.disks` in App options. The example creates a local `exports` disk in a temporary directory. In an application, choose a persistent absolute root or deliberately resolve one relative to the process working directory.', 'Without configuration, the local disk writes under `storage/app` relative to the current working directory. That is convenient locally, but a container filesystem is not automatically durable storage. A standalone script can also construct `Storage` directly.'], links: [{ label: 'Install the runtime and development tools', articleId: 'installation' }] },
		{ id: 'copy', title: 'Copy the export example', paragraphs: ['Use the independent app directory from Installation. This lab does not need a database, an S3 account or an HTTP server.'], codeSampleId: 'copy-lab' },
		{ id: 'run', title: 'Run it', paragraphs: ['The script writes a JSON report and streamed CSV, reads them, lists their relative paths and deletes the report. The result should include `traversalRejected: true` and `deleted: true`. Its temporary disk is removed afterwards.'], codeSampleId: 'run-lab' },
		{ id: 'write-read', title: 'Write and read files', paragraphs: ['`write()` and `put()` write text, bytes or supported stream contents. Use `readToString()` for text and `readToBuffer()` or `get()` when you deliberately want the whole file in memory. `read()` returns a stream, not a string.', 'Choose a named disk with `app().storage.disk("exports")`; normal calls on `app().storage` use the default. `drive()` is an alias for `disk()`.'], codeSampleId: 'storage-source' },
		{ id: 'streams', title: 'Stream uploads and exports', paragraphs: ['Use `writeStream()` and `readStream()` for large payloads. Consume the returned stream or pass it to your HTTP response, with proper stream-error handling. The wrapper does not buffer the whole file before passing it to the driver.', 'The example uses a short CSV stream so the result is easy to inspect. Apply upload limits, client-disconnect handling and temporary-upload cleanup in the HTTP adapter. A streamed API alone does not provide those policies.'] },
		{ id: 'inspect', title: 'List and inspect stored files', paragraphs: ['`exists()` and `missing()` check a path. `size()`, `lastModified()` and `mimeType()` expose file metadata. `list()` returns a lazy async iterable; `toArray()` intentionally collects it. Use `deep: true` only when descendants are needed.', '`delete()` removes the specified file. Treat listing paths as disk-relative names, not application IDs or proof that the caller may read them. Use a scoped Media record when you need that ownership layer.'] },
		{ id: 'remote', title: 'Use S3-compatible storage', paragraphs: ['Configure `driver: "s3"`, `bucket` and `region`. Set `endpoint` for an S3-compatible service, and `forcePathStyle` when that provider requires it. Keep credentials in your environment or the supported provider credential chain, never browser configuration.', 'The service-owned reference includes the full S3 disk configuration. The local lab tests the framework workflow, not credentials, permissions, listing consistency or multipart behaviour on your remote provider. Run a small upload/read/delete smoke test in a dedicated bucket before production.'] },
		{ id: 'delivery', title: 'Paths, URLs and private delivery', paragraphs: ['File paths are relative to the disk root. Absolute paths, parent traversal and null bytes are rejected. Empty paths are allowed for listing the root, not for writing a file. This is path validation, not a sandbox against untrusted filesystem changes or an authorization system.', '`path()` returns a local filesystem path; remote disks cannot supply one. `url()` needs a configured public URL or provider support and only constructs a URL. It does not create a route, sign a private download or grant permission.', 'For private downloads, authorize the caller first, then stream the allowed file with deliberate content type and disposition headers. Never publish a private storage root just to make `url()` work.'], links: [{ label: 'Add durable file IDs and library scopes', articleId: 'media' }] },
		serviceLabTesting('storage', 'runStorage'),
		{ id: 'run-tests', title: 'Run and extend the test', paragraphs: ['The copied test uses a real temporary local disk and removes it in `finally`. Add a named disk or another file and assert the result. Use dedicated test storage, not a production bucket, for destructive cases.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and reference', paragraphs: ['Tested here: named local disks, JSON/text, streamed writes, listing, traversal rejection and deletion. The linked export recipe tests producer interruption and recovery; the private-file guide tests authenticated downloads.', 'Still to build: socket-disconnect and provider-specific S3 integration trials. Those are not implied by local labs passing.'], links: [{ label: 'Full Storage API', articleId: 'storage-api' }, { label: 'Stream failure and recovery', articleId: 'cookbook-streams' }, { label: 'Authenticated files', articleId: 'guide-files' }] },
	], codeSamples: [...serviceLabSamples('storage', 'runStorage'), { id: 'storage-source', title: 'examples/runStorage.ts', language: 'typescript', code: serviceExampleSources.runStorage }], relatedIds: ['installation', 'media', 'create-app'],
};
