import type { DocArticle } from '../docs';
import { serviceExampleSources } from '../generated/service-examples';
import { createApiReference } from './apiReference';
import { serviceLabEvidence, serviceLabSamples, serviceLabTesting } from './serviceLab';

const sources: Readonly<Record<string, string>> = serviceExampleSources;
const evidence = serviceLabEvidence('validation', 'runNoteValidation', 'Rejects malformed note input, repairs it and returns an explicit safe shape without persisting invalid values.', 'Node.js 24. No database, network or credentials.');

export const validationArticle: DocArticle = {
	id: 'validation', area: 'services', group: 'Foundation', label: 'Validation', title: 'Validate application input',
	summary: 'Check a note request, return useful field errors and make the boundary between validation, conversion and authorization explicit.',
	packageName: '@db3.ai/app/validation', sourcePath: 'packages/app/src/validation/README.md', examplePaths: ['packages/app/src/validation/examples/validateNoteInput.ts', 'packages/app/src/validation/examples/runNoteValidation.ts'], testPath: evidence.testPath, verifiedExample: evidence,
	sections: [
		{ id: 'setup', title: 'Validate a note request', paragraphs: ['Follow Installation, then copy the example into your app. This is a plain-data validation lab; it does not need a server or database.', 'Validate at the boundary before business work or persistence. Authentication and ownership are separate checks: a valid title does not give someone permission to edit a note.'], codeSampleId: 'copy-lab', links: [{ label: 'Installation', articleId: 'installation' }] },
		{ id: 'run', title: 'Reject, repair and run again', paragraphs: ['The first request contains a whitespace-only title and priority 9. Expect two field errors, with no submitted values. The repaired request produces exactly `{ title: "First note", priority: 2 }`. An injected `ownerId` is not copied.', 'Change the title or priority in the runner and repeat. There are no resources to clean up and no invalid record can be written by this lab.'], codeSampleId: 'run-lab' },
		{ id: 'rules', title: 'Describe the input you accept', paragraphs: ['`validate(input, rules)` returns `{ valid, data, errors }`. Rules apply to exact top-level keys, in order; validation collects errors rather than stopping after the first rule.', 'This function explicitly selects writable values after validation. In an ActiveRecord workflow, keep field conversion in the model and use its request mapping/fillable policy. Do not duplicate its database conversion in a route.'], codeSampleId: 'validator-source', links: [{ label: 'Field-aware model input', articleId: 'active-record' }] },
		{ id: 'conversion', title: 'Validation is not conversion', paragraphs: ['`data` is the original object, not a sanitized DTO. Unknown properties remain. `integer` accepts a string such as `"2"` without changing it; generic type arguments are TypeScript assertions, not runtime transformations.', 'Our small non-model example converts priority with `Number()` and returns only title and priority. A route should return 422 on failure and continue only on success. Assign owner/workspace IDs from the authenticated context, not the request body.'], codeSampleId: 'runner-source' },
		{ id: 'presence', title: 'Required, optional and nullable values', paragraphs: ['`required` rejects a missing key, `undefined`, `null`, an empty string or an empty array. It does not reject whitespace-only strings; the example adds `/\\S/` and trims after success.', 'Without `required`, missing/null/undefined input skips other rules. `nullable` additionally skips an empty string. Pair the rules deliberately; `nullable` does not override `required`.'] },
		{ id: 'rule-catalogue', title: 'Choose the right rule', paragraphs: ['Type/format rules: `string`, `number`, `integer`, `boolean`, `email`, `url`, `array`, `object`, `ulid`, `uuid`. Number and boolean checks accept common form strings; they do not convert them.', 'Use `minLength` and `maxLength` for text/array length. `min` and `max` interpret number-like strings numerically first: `"123"` exceeds `max:10` but passes `maxLength:10`.', '`in` compares both exact values and their string forms. `regex` accepts a RegExp object or a string pattern. Use non-global, non-sticky patterns: reusable `/g` or `/y` expressions have mutable `lastIndex` state.', '`url` checks HTTP/HTTPS shape and a hostname containing a dot, adding HTTPS for the check when omitted. It is not a public-network/SSRF check, fetch permission or URL normalization. `object` excludes arrays and dates but does not guarantee a plain object prototype.'], links: [{ label: 'All current rule contracts', articleId: 'validation-api' }] },
		{ id: 'errors', title: 'Return errors without reflecting secrets', paragraphs: ['A rule object can provide a custom `message`. The library error includes the original `value` and may include rule `details`. Map to `{ field, rule, message }` before sending or logging user-facing errors, especially for passwords and tokens.', '`assertValid()` returns the same data on success or throws `ValidationException` with `.errors`. Catch that specific error at the boundary; unexpected exceptions should still fail. Unknown rules are programming errors, not a valid user request.'] },
		serviceLabTesting('validation', 'runNoteValidation'),
		{ id: 'run-tests', title: 'Test your boundary', paragraphs: ['The three copied tests cover rejection/recovery, non-disclosure, extra-field selection, length and numeric limits, malformed objects, no coercion, optional/nullable values and throwing validation.', 'Extend the application tests with authorized/unauthorized writers and prove failed requests do not change database state. The isolated lab does not claim that HTTP or SQL behavior.'], codeSampleId: 'test-lab' },
		{ id: 'coverage', title: 'Coverage and limits', paragraphs: ['Taught and tested: note input, explicit output selection/conversion, safe field errors, presence, size, pattern and integer constraints, custom messages and throwing validation. The reference includes every current rule and exported helper.', 'No nested-path traversal, wildcards, async/custom callback rules, uniqueness query, unknown-field stripping, coercion or authorization policy is built in. Validate nested records explicitly or use the owning model field structure.'], links: [{ label: 'Validation API', articleId: 'validation-api' }, { label: 'Authenticated API walkthrough', articleId: 'guide-api' }] },
	],
	codeSamples: [...serviceLabSamples('validation', 'runNoteValidation'), { id: 'validator-source', title: 'examples/validateNoteInput.ts', language: 'typescript', code: sources.validateNoteInput ?? '' }, { id: 'runner-source', title: 'examples/runNoteValidation.ts', language: 'typescript', code: sources.runNoteValidation ?? '' }], relatedIds: ['validation-api', 'active-record', 'fields', 'guide-api'],
};

export const validationApiArticle = createApiReference({ id: 'validation-api', label: 'Validation API', packageName: '@db3.ai/app/validation', sourcePath: 'packages/app/src/validation/README.md', guideId: 'validation', references: [['rules', 'Rules, results, exceptions and helpers', 'dist/validation/index.d.ts']] });
