import { Readable } from 'node:stream';

import sharp from 'sharp';
import { describe, expect, it } from 'vitest';
import { SharpImageProcessor } from '..';

describe('SharpImageProcessor reconstruction', () => {
	it('fully decodes an image and removes trailing source bytes', async () => {
		const trailingPayload = Buffer.from('<script>untrusted()</script>');
		const source = Buffer.concat([
			validPngBytes(),
			trailingPayload,
		]);
		const reconstructed = await reconstruct(source, 'image/png');
		const metadata = await sharp(reconstructed).metadata();

		expect(metadata).toMatchObject({
			format: 'png',
			width: 4,
			height: 3,
		});
		expect(reconstructed).not.toEqual(source);
		expect(reconstructed.includes(trailingPayload)).toBe(false);
	});

	it('rejects signature-prefixed bytes that cannot be completely decoded', async () => {
		const malformed = Buffer.concat([
			Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
			Buffer.from('not a completely decodable png'),
		]);

		await expect(reconstruct(malformed, 'image/png')).rejects.toThrow();
	});

	it('reconstructs every frame of an animated GIF', async () => {
		const reconstructed = await reconstruct(animatedGifBytes(), 'image/gif');
		const metadata = await sharp(reconstructed, {
			animated: true,
		}).metadata();

		expect(metadata).toMatchObject({
			format: 'gif',
			width: 2,
			height: 4,
			pageHeight: 2,
			pages: 2,
		});
	});
});

/**
 * Reconstructs source bytes through the production Sharp adapter.
 *
 * @param source - Encoded source bytes supplied to the processor.
 * @param mimeType - Canonical source and output MIME type.
 * @returns Complete reconstructed image bytes.
 */
async function reconstruct(source: Buffer, mimeType: string): Promise<Buffer> {
	const output = new SharpImageProcessor().reconstruct({
		sourceMimeType: mimeType,
		outputMimeType: mimeType,
	});

	Readable.from([source]).pipe(output);

	const chunks: Buffer[] = [];

	for await (const chunk of output) {
		chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
	}

	return Buffer.concat(chunks);
}

/**
 * Returns a small valid PNG fixture generated by Sharp.
 *
 * @returns Fully decodable four-by-three PNG image.
 */
function validPngBytes(): Buffer {
	return Buffer.from(
		'iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEklEQVQImWPQiNryHxkzEBQAAJJxGn2P50tGAAAAAElFTkSuQmCC',
		'base64',
	);
}

/**
 * Returns a two-frame animated GIF fixture generated by Sharp.
 *
 * @returns Fully decodable two-by-two red and blue animation.
 */
function animatedGifBytes(): Buffer {
	return Buffer.from(
		'R0lGODlhAgACAIAAAExpcf8AACH/C05FVFNDQVBFMi4wAwEAAAAh+QQFCgAAACwAAAAAAgACAAACAoxTACH5BAUUAAAALAAAAAACAAIAgExpcQAA/wICjFMAOw==',
		'base64',
	);
}
