import { defineBlock } from '@db3.ai/app/flows';

import { DEMO_USER_ID } from '../demoData.js';
import { DemoContentPlan } from '../models/index.js';
import { requireArticleState, requireString, type ArticleStatePort } from './articleState.js';

const TARGET_PLANNED_DAYS = 30;

/** Ensures the demo database contains a rolling month of planned content. */
export default defineBlock<ArticleStatePort, ArticleStatePort>({
	type: 'database.ensure-plan-coverage',
	name: 'Ensure 30 Planned Days',
	description: 'Checks plan coverage and inserts deterministic placeholder plans when fewer than 30 future items exist.',
	inputs: { state: { type: 'json', required: true } },
	outputs: { state: { type: 'json', required: true } },
	/**
	 * Counts and fills planned content rows for the demo user.
	 *
	 * @param input - Daily planning state containing the schedule date.
	 * @param context - Runtime context used for durable diagnostics.
	 * @returns Planning state with coverage counts.
	 */
	async run(input, context) {
		const state = requireArticleState(input);
		const date = requireString(state, 'date');
		const existing = await DemoContentPlan
			.where('userId', DEMO_USER_ID)
			.where('status', 'planned')
			.all();
		const missing = Math.max(0, TARGET_PLANNED_DAYS - existing.length);

		await Promise.all(Array.from({ length: missing }, async (_, index) => {
			const plan = DemoContentPlan.create({
				userId: DEMO_USER_ID,
				targetKeyword: `observable workflow topic ${existing.length + index + 1}`,
				plannedDate: addDays(date, existing.length + index),
				brief: 'Generated by the daily Flow Lab coverage block to demonstrate observable scheduled orchestration.',
				status: 'planned',
			});

			await plan.save();
		}));

		const coverage = {
			targetDays: TARGET_PLANNED_DAYS,
			previouslyPlanned: existing.length,
			generated: missing,
			totalPlanned: existing.length + missing,
		};

		await context.log('info', 'Content plan coverage checked.', coverage);
		return { state: { ...state, coverage } };
	},
});

/**
 * Adds whole UTC days to an ISO date string.
 *
 * @param date - ISO calendar date.
 * @param days - Number of days to add.
 * @returns Shifted ISO calendar date.
 */
function addDays(date: string, days: number): string {
	const value = new Date(`${date}T00:00:00.000Z`);

	if (Number.isNaN(value.getTime())) {
		throw new Error('Schedule date must use YYYY-MM-DD format.');
	}

	value.setUTCDate(value.getUTCDate() + days);
	return value.toISOString().slice(0, 10);
}
